infinitered/ignite

.babelrc
App/Reducers/LoginReducer.js
App/Sagas/LoginSaga.js
App/Sagas/StartupSaga.js
Tests/Compiler.js
Tests/Reducers/LoginReducerTest.js
Tests/Sagas/LoginSagaTest.js
Tests/Sagas/StartupSagaTest.js
Tests/Setup.js
Tests/mocha.opts
package.json

This just tests the reducers and sagas.
I brought over your old Compiler even though we're not using it just yet.  We will once we start testing React Native stuff.

Some reducer and saga tests with Mocha.

---

README.md

update readme and add build status badge

---

.github/PULL_REQUEST_TEMPLATE.md
App/Containers/AllComponentsScreen.js
App/Navigation/Routes.js
App/Root.js
App/Styles/AllComponentsScreenStyle.js
App/Styles/LoginScreenStyle.js
App/Styles/NavigationStyle.js
App/Themes/Base.js
App/Themes/Colors.js

Small touchups

---

android/app/build.gradle
android/app/react.gradle
android/app/src/main/java/com/rnbase/MainActivity.java
android/build.gradle
package.json

Just a quick version bump to React Native 0.21.

Up to version 0.21.

---

App/Containers/LoginScreen.js
App/Styles/LoginScreenStyle.js
App/Themes/Colors.js

keyboard avoiding with fancy animation

---

.github/ISSUE_TEMPLATE.md
App/Containers/README.md

Just some `.gitignore` deletions and speeling errors fixed.

Small fixes

---

App/Containers/LoginScreen.js
App/Navigation/NavButtons.js
App/Navigation/NavigationBarRouteMapper.js
App/Navigation/Routes.js
App/Styles/NavigationStyle.js
Tests/Compiler.js

Adds example of setting a nav bar button.

---

App/Navigation/NavButtons.js
App/Navigation/NavigationBarRouteMapper.js
App/Navigation/Routes.js
App/Styles/NavigationStyle.js

--
Uses the new FontAwesome library to render a back button on the login screen.

Give the login page a working "back" button

---

App/Reducers/CreateReducer.js
App/Reducers/LoginReducer.js
App/Reducers/WeatherReducer.js
App/Reducers/index.js

Oopsie.  Let's try this one more time!  Sorry, I should have said something.

Redux persist

---

.github/PULL_REQUEST_TEMPLATE.md

Add instructions to PR template for running tests and linter.

---

ignite-cli/index.js
ignite-cli/src/index.es
ignite-generator/app/index.js
ignite-generator/component/index.js
ignite-generator/component/templates/component-style.js.template
ignite-generator/component/templates/component.js.template
ignite-generator/container/index.js
ignite-generator/container/templates/container-style.js.template
ignite-generator/container/templates/container.js.template
ignite-generator/shared/shared.js
ignite-generator/src/app/index.es
ignite-generator/src/component/index.es
ignite-generator/src/container/index.es
ignite-generator/src/shared/shared.js

I pulled out some common code and put it in `shared/shared.js` so we can use the verification and file system removal in any generator.

Component and Container generators

---

ignite-base/App/Themes/Colors.js

Adds Color.rainbow for a random color.

---

ignite-base/App/Containers/AllComponentsScreen.js
ignite-base/App/Containers/Styles/AllComponentsScreenStyle.js
ignite-base/App/Navigation/Styles/NavigationStyle.js
ignite-base/App/Themes/Base.js
ignite-base/App/Themes/Fonts.js
ignite-base/App/Themes/Images.js
ignite-base/App/Themes/Metrics.js

Move font sizes into Font from Metrics.

---

ignite-generator/app/index.js
ignite-generator/component/index.js
ignite-generator/component/templates/component.js.template
ignite-generator/container/index.js
ignite-generator/container/templates/container.js.template
ignite-generator/screen/index.js
ignite-generator/validation.js

Components were getting generated in scroll views, which is not really useful.  Switched it to them being generated in a regular view.   I also added some commented started code, and did some house keeping.

[Generator] - Simpler components

---

ignite-base/package.json
ignite-base/package.json.template

command updates - partial of #61

[Base] - adding android commands

---

README.md
ignite-generator/container/templates/container.js.template
ignite-generator/screen/index.js
ignite-generator/screen/templates/screen-style.js.template
ignite-generator/screen/templates/screen.js.template
ignite-generator/src/screen/index.es

ability to generate screens, also cleaned up components.

[Generator] - Screen generator

---

ignite-generator/app/index.js
ignite-generator/src/app/index.es

*Examples of good PR Titles*
- [Base] - Adding example of feature X
- [Generator] - Adding new verification
- [CLI] - Changed message colors
- [Generator | CLI] - Adding new command/builder Tacos
closes #65

[Generator] - adding verbose option to app build

---

ignite-base/fastlane/Appfile
ignite-base/fastlane/Fastfile
ignite-base/fastlane/Matchfile
ignite-base/ios/RNBase/AppDelegate.m

fastlane template code.  Should remove the need for anyone to `fastlane init`

[Base] - Add fastlane

---

ignite-base/App/Config/ReactotronConfig.js
ignite-base/App/Services/Api.js
ignite-base/App/Store/Store.js
ignite-base/index.android.js
ignite-base/index.ios.js
ignite-base/index.js.template
ignite-base/package.json
ignite-base/package.json.template

[Base] - Reactotron add

---

ignite-base/App/Reducers/CreateReducer.js

This was inspired by @hknd in issue #81 
cc: @skellock

[Base] - throw friendly error when undefined action is used

---

ignite-base/App/Components/ProgressiveImage.js
ignite-base/App/Containers/AllComponentsScreen.js
ignite-base/App/Containers/LoginScreen.js
ignite-cli/package.json
ignite-generator/component/templates/component.js.template
ignite-generator/container/templates/container.js.template
ignite-generator/package.json

Change generators to use updated import style for 0.25 + version bump

[ALL] 0.25 syntax change

---

ignite-base/App/Lib/Utilities.js

[Base] - simple start of useful utitlity functions

---

ignite-base/App/Containers/APITestingScreen.js
ignite-base/App/Containers/PresentationScreen.js
ignite-base/App/Containers/Styles/APITestingScreenStyle.js
ignite-base/App/Navigation/Routes.js
ignite-base/package.json
ignite-base/package.json.template

[Base] Implemented API Testing Screen with dynamic arguments - resolves #88

---

ignite-base/App/Components/Styles/ProgressiveImageStyle.js
ignite-base/App/Containers/Styles/APITestingScreenStyle.js
ignite-base/App/Containers/Styles/AllComponentsScreenStyle.js
ignite-base/App/Containers/Styles/PresentationScreenStyle.js
ignite-base/App/Containers/Styles/ThemeScreenStyle.js
ignite-base/App/Containers/Styles/UsageExamplesScreenStyle.js
ignite-base/App/Containers/ThemeScreen.js
ignite-base/App/Services/ExamplesRegistry.js
ignite-base/App/Themes/Base.js
ignite-base/App/Themes/Colors.js
ignite-base/App/Themes/CommonStyles.js
ignite-base/App/Themes/Fonts.js
ignite-base/App/Themes/index.js

Small modifications after a meeting with @skellock 
Firstly, to make the Themes screen auto-generate, and secondly to rename Base.

[Base] - Touchups

---

ignite-generator/app/index.js
ignite-generator/package.json
ignite-generator/src/app/index.es
ignite-generator/src/validation.js
ignite-generator/validation.js

* Adds a spinner
* Fixes the `rnpm` command out of band
* Removes auto-installing of rnpm
* Adds a version check of at least 1.7.0 of rnpm instead of just out-of-date
* Silences the verbose logging during install
* Adds next step instructions at the end

Adds a little smoother installation experience.

---

ignite-base/App/Components/AlertMessageComponent.js
ignite-base/App/Components/Styles/AlertMessageComponentStyle.js
ignite-base/App/Containers/AllComponentsScreen.js
ignite-base/App/I18n/I18n.js

- [Base] - AlertMessage added

---

ignite-base/App/Containers/APITestingScreen.js
ignite-base/App/Fixtures/boise.json
ignite-base/App/Fixtures/toronto.json
ignite-base/App/Sagas/index.js
ignite-base/App/Services/FixtureApi.js

[Base] - Implement Fixtures Examples

---

index.html

*Examples of good PR Titles*
- [Base] - Adding example of feature X
- [Generator] - Adding new verification
- [CLI] - Changed message colors
- [Generator | CLI] - Adding new command/builder Tacos

Index Copy changes

---

ignite-base/package.json
ignite-base/package.json.template

To latest API sauce and beyond.

Small updates

---

ignite-base/App/Components/Styles/RoundedButtonStyle.js
ignite-base/App/Containers/APITestingScreen.js
ignite-base/App/Containers/AllComponentsScreen.js
ignite-base/App/Containers/DeviceInfoScreen.js
ignite-base/App/Containers/LoginScreen.js
ignite-base/App/Containers/PresentationScreen.js
ignite-base/App/Containers/Styles/ThemeScreenStyle.js
ignite-base/App/Containers/Styles/UsageExamplesScreenStyle.js
ignite-base/App/Containers/ThemeScreen.js
ignite-base/App/Containers/UsageExamplesScreen.js
ignite-base/App/Services/ExamplesRegistry.js
ignite-base/App/Themes/ApplicationStyles.js
ignite-base/App/Themes/Colors.js

[Base] - Android styling fixes

---

ignite-base/package.json
ignite-base/package.json.template

update to latest RN push lib

---

ignite-generator/component/templates/component-style.js.template
ignite-generator/component/templates/component.js.template
ignite-generator/container/templates/container-style.js.template
ignite-generator/screen/templates/screen-style.js.template
ignite-generator/screen/templates/screen.js.template

Needed to update generated template files.

[Generator] - update generated component container and screens

---

ignite-cli/package.json
ignite-cli/src/index.es

[CLI] - enforce alphanumeric projects

---

ignite-base/App/Containers/LoginScreen.js

[Base] - fixed by keeping in vars

---

ignite-base/App/Containers/Styles/RootStyle.js

Making the internal code documentation better, one typo at a time!

[Base] Typo fix in RootStyle.js

---

ignite-base/App/Root.js
ignite-base/index.android.js
ignite-base/index.ios.js
ignite-base/index.js.template

no more provider issues :star2: fixed!

---

ignite-base/.editorconfig.template
ignite-generator/src/app/index.es

newly ignited projects will grab the `.editorconfig` file, and like it!

[Generator] - added .editorconfig to newly ignited project

---

fireDrill.sh
ignite-base/App/Sagas/StartupSaga.js

startup loop killed

---

ignite-base/Tests/Services/FixtureAPITest.js
ignite-base/Tests/Setup.js

added check on Fixture APIs

---

ignite-base/package.json
ignite-base/package.json.template

add es2015 preset to close #204

---

ignite-generator/src/app/index.es

Though we added fastlane to the template, we never copied it over!
Do so now.

don't forget fastlane

---

README.md

Would like to direct more people to Gitter to discuss Ignite.

Added more obvious Gitter link to README

---

README.md

added mapview generator documentation to readme

---

README.md
ignite-base/App/Containers/UsageExamplesScreen.js
ignite-base/android/app/build.gradle
ignite-base/android/app/src/main/java/com/rnbase/MainActivity.java
ignite-base/android/settings.gradle
ignite-base/package.json
ignite-base/package.json.template
ignite-generator/src/utilities.js

Bye bye maps, come back soon, we miss you!

maps gone for temporary fix

---

ignite-base/fastlane/Fastfile

centralize username

---

fireDrill.sh
fireTest.sh

Updates firedrill to help stop a few errors.

Improve firedrill

---

ignite-generator/package.json

bad repo url (eg. http:://...)

typo(repo url): remove one column

---

ignite-generator/src/app/index.es

Keeps the estimates real.

---

.github/ISSUE_TEMPLATE.md
ignite-cli/src/index.es

Typing `ignite doctor` gives you this:
```
Computer
Platform: darwin
Ignite
Version: 1.3.2
Path: /usr/local/bin/ignite
Node
Version: v6.3.0
Path: /usr/local/bin/node
NPM
Version: 3.10.3
Path: /usr/local/bin/npm
Yeoman
Version: 1.8.4
React Native CLI
Version: 1.0.0
App
React Native Version: 0.29.2
```

[CLI] Adds doctor command for showing dev environment info.

---

fireDrill.sh
ignite-cli/package.json
ignite-generator/package.json
ignite-generator/src/app/index.es
testRelease.sh

If you would like to check on a particular build of ignite before releasing it, this will save you the headache of seeing if it basically builds, etc.

Realease tester

---

ignite-base/README.md.template
ignite-base/git_hooks/pre-commit/lint.sh
ignite-base/package.json
ignite-base/package.json.template

- [✔] Everything works on iOS/Android
- [✔] `ignite-base` **ava** tests pass
- [✔] `fireDrill.sh` passed
Addresses https://github.com/infinitered/ignite/issues/192
Uses the ghooks npm package to implement pre-commit linting. Removes previous git hooks implementation.
@GantMan Please review.

Use ghooks for git hooks

---

ignite-base/App/Navigation/NavItems.js
ignite-base/App/Navigation/NavigationDrawer.js
ignite-base/App/Navigation/NavigationRouter.js
ignite-base/App/Navigation/Styles/NavItemsStyle.js

Add example of overriding and changing buttons

Change hamburger

---

ignite-base/App/Containers/DeviceInfoScreen.js
ignite-base/android/app/src/main/AndroidManifest.xml

- [✔] Everything works on iOS/Android
- [✔] `ignite-base` **ava** tests pass
- [✔] `fireDrill.sh` passed
Addresses https://github.com/infinitered/ignite/issues/168 by adding network info to the DeviceInfoScreen.
@GantMan

Add NetInfo to DeviceInfoScreen

---

ignite-base/package.json
ignite-base/package.json.template

Using the html reporter for nyc coverage.

using nyc html reporter instead of text

---

ignite-base/package.json
ignite-base/package.json.template

Apisauce now supports transforms.  Both request & response.
```js
// install it like a monitor
api.addResponseTransform(response => {
// check for conditions
if (response.data.email === 'gant@infinite.red') {
// and mutate the data before it arrives in your other code
response.data.password = 'p@ntsl3ss_c0d1ng'
}
})
```

Upgrades Apisauce from 0.3.0 to 0.4.0.

---

ignite-base/.gitignore
ignite-base/README.md.template
ignite-base/android/app/build.gradle
ignite-base/android/app/src/main/java/com/rnbase/MainApplication.java
ignite-base/android/app/src/main/res/values/strings.xml
ignite-base/android/settings.gradle
ignite-base/ios/RNBase.xcodeproj/project.pbxproj
ignite-base/package.json
ignite-base/package.json.template

Adds [react-native-config](https://github.com/luggit/react-native-config) support to Ignite. Similar to dotenv.

Add react-native-config support

---

README.md

Small grammar fixes for the readme

pared vs paired, other minor grammar fixes

---

ignite-cli/src/index.es

Fix globally installed react-native

---

ignite-base/App/Navigation/NavigationDrawer.js

give drawer an initial state so that it wouldn't give out warning initially

add initial state for drawer

---

ignite-base/App/Navigation/NavigationDrawer.js
ignite-base/App/Navigation/NavigationRouter.js

fixing my previous PR regarding drawer initial state

simpler way to solving the undefined prop problem

---

ignite-base/App/Containers/ThemeScreen.js
ignite-base/App/Themes/Images.js

Fix Identifier 'tile_bg' not in camel case.
Close issue #328.

Fix Identifier 'tile_bg' not in camel case

---

ignite-base/App/Containers/AllComponentsScreen.js

I am not sure about the warning text if you have a better idea 😄

Add android warning for component screen

---

README.md

adds friendly thanks at the footer

---

ignite-base/App/Containers/ListviewExample.js
ignite-base/App/Containers/ListviewGridExample.js
ignite-base/App/Containers/Styles/ListviewExampleStyle.js
ignite-generator/listview/templates/listview-style.js.template
ignite-generator/listview/templates/listview.js.template

listview fixes for #305

---

ignite-cli/package.json
ignite-cli/src/index.es

Cli now automatically detect version updates.
With  [update-notifier](https://github.com/yeoman/update-notifier).
Close #240

Detect version update

---

README.md

Just fixing three typos in Readme.

Fix Readme.md typos

---

ignite-base/App/Containers/ListviewSectionsExample.js
ignite-base/App/Containers/UsageExamplesScreen.js
ignite-base/App/Navigation/NavigationRouter.js
ignite-generator/listview/templates/listview-sections.js.template
ignite-generator/listview/templates/listview.js.template
ignite-generator/src/listview/index.es

Added nice sections listview example and generator to the project.  
Closes: #291

Sections example template and generator

---

ignite-base/App/Containers/ListviewExample.js
ignite-base/App/Containers/ListviewGridExample.js
ignite-base/App/Containers/ListviewSectionsExample.js
ignite-generator/listview/templates/listview-sections.js.template

Change text written as `Eigth Description` to `Eighth Description`.

Fix spelling typo. Change from Eigth to Eighth.

---

ignite-base/App/Config/DebugSettings.js

Set reduxLogging to __DEV__ as default

---

ignite-base/package.json
ignite-base/package.json.template

Points back to original npm package now that .env issue fixed

---

ignite-base/.ignite.template
ignite-generator/src/app/index.es

Resolves issue #157 to add Ignite and React Native versions, and adds blank objects for options and plugins for future use.

adds .ignite file for holding version and future config stuff

---

ignite-generator/container/templates/container.js.template
ignite-generator/screen/templates/screen.js.template

Updates the references to Redux actions in the Screen and Component templates.
closes infinitered/ignite#366

Updates Screen and Component Templates for change in Redux style

---

ignite-base/App/Containers/DrawerContent.js

Fix [357](https://github.com/infinitered/ignite/issues/357)

Feature, when drawer open, backAndroid close it

---

ignite-generator/component/templates/component-test.js.template
ignite-generator/component/templates/component.js.template
ignite-generator/src/component/index.es
ignite-generator/src/utilities.js

After a bit of gitter chat this PR starts the ball rolling with the idea that we should scaffold out a test when we generate a component/saga/whatever. This PR adds the component test.
I've copied the `context.fs.copyTpl( ...` lines in `index.es` but since there are two similar functions in the same place I'm wondering if another function might be the best. 
🔚

Create a test when a new component is generated

---

ignite-base/package.json
ignite-base/package.json.template

This adds the `npm run flow` command to ignite.

adding flow command and bin

---

ignite-base/.flowconfig
ignite-base/App/Containers/DrawerContent.js
ignite-base/App/Services/RehydrationServices.js
ignite-base/ios/RNBase.xcodeproj/project.pbxproj
ignite-base/package.json
ignite-base/package.json.template

Upgrading ignite to 0.34
Closes #392

Upgrade to 0.34

---

ignite-cli/src/index.es

Make sure you can't ignite a project named `React`

---

ignite-base/package.json
ignite-base/package.json.template
ignite-cli/package.json
ignite-cli/src/index.es
ignite-generator/package.json
ignite-generator/src/app/index.es
ignite-generator/src/testing/index.es
ignite-generator/src/utilities.js
testRelease.sh

If you'd like to test Ignite against FB Master branch
Run with 2nd param latest `./testRelease.sh fb_check latest`
This change goes all the way down through the CLI to the generator.

Master check against FB - For early warning checks

---

ignite-base/App/Config/ReduxPersist.js
ignite-cli/src/index.es

Fix Redux Persist Config whitelist.

---

.travis.yml
README.md
testRelease.sh

This .travis.yml plus changes (some indicated by @juddey) - helps ignite master run against Facebook master every 24 hours.
As you can see there is a problem in the current build, and this identifies an early warning issue.
> @juddey - I know you were augmenting the tests for `./testRelease`.  Please rebase with these changes.  If you need help, let me know.  SORRY!
**ALSO SORRY!**
> Whomever merges this PR, please squash it.  I have mannnnny commits, because that's kind of the only way to test against travis ci.

Add travis

---

ignite-base/App/Redux/CreateStore.js

Corrects Reactotron Blacklist Config

---

README.md

fix a typo on the README file, change graceously to graciously

fix a typo, change graceously to graciously

---

ignite-generator/src/app/index.es

Cleaning up the install process noise, and adding some extra scrubbing

Extra clean

---

ignite-generator/src/app/index.es

igniting an app does a friendly check for android and SDK

adding android checks fixes #448

---

ignite-base/App/Containers/UsageExamplesScreen.js
ignite-base/App/Navigation/NavigationRouter.js
ignite-base/android/app/app.iml
ignite-base/android/app/build.gradle
ignite-base/ios/RNBase.xcodeproj/project.pbxproj
ignite-base/package.json
ignite-base/package.json.template
ignite-base/yarn.lock
ignite-generator/src/app/index.es

Bringing back maps and hopefully solving the conflict for good (in Ignite).
Closes: #471 
Fixes: #468 
Please review @skellock @ryanlntn @fvonhoven

Map return!!!

---

README.md

Troubleshooting section with known errors. Added workaround for #362

Added troubelshooting section

---

README.md
ignite-generator/README.md

As requested at the end of #466

Document Redux and Saga Generators

---

ignite-base/App/Components/README.md

Fixed typo in Components README

---

ignite-base/App/Containers/APITestingScreen.js

This was probably a leftover as a result of creating `APITestingScreen.js` out of `AllComponentsScreen.js`.

Remove comment about AllComponentsScreen.js in APITestingScreen.js

---

ignite-base/App/Containers/RootContainer.js

Just a small name change that someone pointed out in Gitter.

Renames a function that was clearly named under the influence.

---

README.md

- [✓] Everything works on Android
(other checks unrelated to changes)
I believe many developers prefer not to to changes directories when using their tools. If it's required, I personally prefer to put it on one line, as it represents one command to me.

update Readme with one line gradle clean

---

packages/ignite-basic-generators/index.js
packages/ignite-empty-playground/ignite.toml
packages/ignite-empty-playground/package.json
packages/ignite/package.json
packages/ignite/src/plugins/default/commands/add.js
packages/ignite/src/plugins/default/commands/ee.js

[28 days ago](https://github.com/infinitered/ignite/pull/498), I had this same thing working, but this time... GLUE GUN!
**some caveats:**
* to make my life manageable I only worried about adding generators
* no docs
* code reads like a bad script, needs to become functions
* npm hardcoded over yarn for now

Ignite add is working!

---

ignite-base/package.json
ignite-base/package.json.template

Clean script to prevent android errors on react-native run-android

Add clean android script

---

packages/ignite/src/plugins/default/commands/remove.js

Ignite remove

---

ignite-base/App/Containers/AllComponentsScreen.js
lerna.json
packages/ignite-empty-playground/ignite.toml
packages/ignite-empty-playground/package.json
packages/ignite-vector-icons/.gitignore
packages/ignite-vector-icons/ignite.toml
packages/ignite-vector-icons/index.js
packages/ignite-vector-icons/package.json
packages/ignite-vector-icons/templates/vectorExample.js
packages/ignite/package.json
packages/ignite/src/plugins/default/commands/add.js
packages/ignite/src/plugins/default/extensions/ignite.js
packages/ignite/src/plugins/default/extensions/patching.js

theoretical addition of vector icons via plugin.

Vector icons

---

ignite-base/App/I18n/es.json

Added spanish translation

---

packages/ignite/src/plugins/default/commands/doctor.js
packages/ignite/src/plugins/default/commands/version.js

this fixes `ignite doctor` and adds `ignite version`

Fix doctor

---

packages/ignite-basic-structure/index.js
packages/ignite-basic-structure/package.json
packages/ignite-basic-structure/templates/Unholy/Config/DebugConfig.js
packages/ignite-basic-structure/templates/Unholy/Config/README.md
packages/ignite-basic-structure/templates/Unholy/Config/ReactotronConfig.js
packages/ignite-basic-structure/templates/Unholy/Redux/CreateStore.js
packages/ignite-basic-structure/templates/Unholy/Sagas/index.js
packages/ignite-basic-structure/templates/Unholy/Services/ExamplesRegistry.js
packages/ignite-basic-structure/templates/package.json.unholy.ejs
packages/ignite-dev-screens/package.json
packages/ignite-dev-screens/templates/DevscreensButton.ejs
packages/ignite/src/plugins/default/commands/new.js
packages/ignite/src/plugins/default/extensions/ignite.js

the new suckier version of ignite new, hahah.  Does zero checks, just works... kinda.
I can't get link to return for the life of me.  Hopefully someone can help me solve it, until then I'm just commenting it out.

ignite new

---

README.md

Clarify Android Portion of How To in Readme

---

ignite-base/App/Containers/Styles/AllComponentsScreenStyle.js

It wasn't being used in that component :)

Remove groupContainer from AllComponentsScreenStyle.js

---

packages/ignite/src/plugins/default/commands/new.js

adds min max

---

packages/ignite/src/plugins/default/commands/add.js
packages/ignite/src/plugins/default/commands/add/detectInstall.js
packages/ignite/src/plugins/default/commands/remove.js
packages/ignite/src/plugins/default/extensions/ignite.js

Next safety

---

packages/ignite/src/plugins/default/commands/add.js
packages/ignite/src/plugins/default/commands/add/detectInstall.js

Fix add plugin

---

ignite-base/README.md.template
ignite-base/package.json
ignite-base/package.json.template
ignite-base/yarn.lock

`ghooks` is now deprecated and recommends the use of `Husky` instead. This PR replaces it.
See gtramontina/ghooks#166 for more info.

Use Husky rather than deprecated ghooks

---

README.md

Add Slackin badge

---

packages/ignite-animatable/package.json
packages/ignite-basic-generators/package.json
packages/ignite-basic-structure/package.json
packages/ignite-dev-screens/package.json
packages/ignite-i18n/package.json
packages/ignite-vector-icons/package.json
packages/ignite/package.json

This will bust the local cache so `ignite new HolyCrap --max` shows the new designs.

Local Cache Busting

---

packages/ignite/src/commands/remove.js
packages/ignite/src/extensions/ignite.js

I missed this update when we switched to JSON.

Fixes ignite examples no longer appearing.

---

.gitignore
packages/ignite-basic-structure/index.js
packages/ignite/src/commands/new.js
packages/ignite/src/commands/plugin.js
packages/ignite/src/lib/exitCodes.js
packages/ignite/src/templates/plugin/.gitignore
packages/ignite/src/templates/plugin/commands/example.js.ejs
packages/ignite/src/templates/plugin/ignite.toml.ejs
packages/ignite/src/templates/plugin/index.js.ejs
packages/ignite/src/templates/plugin/package.json.ejs
packages/ignite/src/templates/plugin/templates/Example.js.ejs

This adds basic plugin generation to Ignite 2.0.
```
$ ignite plugin new ignite-foo
```

Adds `ignite plugin new` to CLI

---

packages/ignite-basic-structure/package.json
packages/ignite-basic-structure/templates/Unholy/Themes/ApplicationStyles.js
packages/ignite-dev-screens/index.js
packages/ignite-dev-screens/package.json
packages/ignite-dev-screens/templates/APITestingScreen.js.ejs
packages/ignite-dev-screens/templates/ComponentExamplesScreen.js.ejs
packages/ignite-dev-screens/templates/DeviceInfoScreen.js.ejs
packages/ignite-dev-screens/templates/DevscreensButton.js.ejs
packages/ignite-dev-screens/templates/PluginExamplesScreen.js.ejs
packages/ignite-dev-screens/templates/PresentationScreen.js.ejs
packages/ignite-dev-screens/templates/PresentationScreenStyle.js.ejs
packages/ignite-dev-screens/templates/ThemeScreen.js.ejs
packages/ignite/package.json

This is using `react-navigation` and stays true to @justinhuskey and @cindy-nguyen 's design.

new devscreen nav

---

lerna.json
package.json
packages/ignite/package.json

Bumps all dependencies that were out of date.

Upgrades all dependencies.

---

packages/ignite/package.json
packages/ignite/src/cli/cli.js
packages/ignite/src/lib/detectedChanges.js
packages/ignite/tests/brand/header.test.js
packages/ignite/tests/cli/_mockGluegunBuilder.js
packages/ignite/tests/cli/cliConfig.test.js
packages/ignite/tests/cli/cliEmpty.test.js
packages/ignite/tests/cli/cliError.test.js
packages/ignite/tests/cli/cliVersionViaSwitches.test.js
packages/ignite/tests/cli/cliWtf.test.js
packages/ignite/tests/fixtures/ignite-valid-plugin/package.json
packages/ignite/tests/lib/detectInstall.test.js
packages/ignite/tests/lib/detectedChanges.test.js
packages/ignite/tests/lib/exitCodes.test.js

I'll tackle the cli & commands shortly, but this will set the stage.
Check out the `header.test.js` for an example on how to mock stuff.
Really not that much special about testing this setup.  I like that.

Adds some unit tests so we can start sleeping better.

---

packages/ignite/src/commands/add.js
packages/ignite/src/commands/new.js
packages/ignite/src/extensions/ignite.js

The subtasks show as spinners and once complete, they collapse, leaving behind a nice checkmark.
I like it.  
You see the details of the subtasks when they're happening, but go away when the task is finished.  The end result is clean.
But take a test drive before merging to see what you think.
We still need a bit more work on each of the components, but you'll get the gist.

Adds collapsing spinners

---

packages/ignite-animatable/templates/animatableExample.js.ejs

- [x ] Everything works on iOS/Android
- [x ] `ignite-base` **ava** tests pass
- [ x] `fireDrill.sh` passed
Updated styling to Animatable example screen.

updated animateable example screen

---

packages/ignite/package.json

#674 - closed because hopefully this works.

fixing lists with gluegun version bump

---

docs/quick-start/getting-started.md
packages/ignite-integration-tests/package.json
packages/ignite/package.json

TODO: 
This PR will add `/docs/quick-start/getting-started.md`. This page describes how to get started with Ignite 2 by downloading it from NPM.
The directory structure is based off other Facebook Open Source projects, such as Flow, Nuclide and ReactJS. These projects have a "Quick Start" navigation heading (in the sidebar) with a "Getting Started" page/sub-link. 
For example:

Quick Start / Getting Started Page

---

docs/advanced-guides/creating-plugins.md

This finishes the doc for creating an Ignite plugin from a 3rd party plugin

Update "Create Plugin" doc

---

ignite-base/App/I18n/de.json

- [*] Everything works on iOS/Android
- [*] `ignite-base` **ava** tests pass
- [*] `fireDrill.sh` passed
Just provide german as language file

Added german translation

---

lerna.json
package.json
packages/ignite-animatable/package.json
packages/ignite-basic-generators/package.json
packages/ignite-cli/package.json
packages/ignite-dev-screens/package.json
packages/ignite-empty-app-template/package.json
packages/ignite-i18n/package.json
packages/ignite-integration-tests/package.json
packages/ignite-minimal-app-template/package.json
packages/ignite-unholy-app-template/package.json
packages/ignite-vector-icons/package.json

This standardizes the version numbers for publishing.  I'll update to the real numbers (2.x) when we get this process down.
Also switching lerna to independent mode for version numbers.

Updated package.json details.

---

docs/advanced-guides/creating-generators.md

Next docs project structure

---

package.json
packages/ignite-animatable/package.json
packages/ignite-basic-generators/package.json
packages/ignite-cli/package.json
packages/ignite-dev-screens/package.json
packages/ignite-empty-app-template/package.json
packages/ignite-i18n/package.json
packages/ignite-integration-tests/package.json
packages/ignite-minimal-app-template/package.json
packages/ignite-unholy-app-template/package.json
packages/ignite-vector-icons/package.json

Getting ready for first publish.

Resets the version numbers.

---

packages/ignite-cli/src/commands/add.js

In an unexpected turn of events, `yarn` comes through in the clutch.
We're able to properly bust the cache now for local folder-based devs.
Meanwhile, `npm --derp`.

Re-instates yarn support with cache busting.

---

package.json
packages/ignite-animatable/package.json
packages/ignite-animatable/templates/animatableExample.js.ejs
packages/ignite-basic-generators/index.js
packages/ignite-basic-generators/package.json
packages/ignite-basic-generators/templates/examples/GridExample.js.ejs
packages/ignite-basic-generators/templates/examples/RowExample.js.ejs
packages/ignite-cli/src/commands/new.js
packages/ignite-cli/tests/cli/_mockGluegunBuilder.js
packages/ignite-dev-screens/package.json
packages/ignite-dev-screens/templates/APITestingScreen.js
packages/ignite-dev-screens/templates/ButtonBox.js
packages/ignite-dev-screens/templates/ComponentExamplesScreen.js
packages/ignite-dev-screens/templates/DeviceInfoScreen.js
packages/ignite-dev-screens/templates/DevscreensButton.js
packages/ignite-dev-screens/templates/PluginExamplesScreen.js
packages/ignite-dev-screens/templates/PresentationScreen.js
packages/ignite-dev-screens/templates/ThemeScreen.js
packages/ignite-empty-app-template/package.json
packages/ignite-i18n/package.json
packages/ignite-integration-tests/package.json
packages/ignite-unholy-app-template/templates/App/Components/SearchBar.js
packages/ignite-unholy-app-template/templates/App/Navigation/NavigationRouter.js
packages/ignite-unholy-app-template/templates/App/Redux/CreateStore.js
packages/ignite-unholy-app-template/templates/App/Services/ExamplesRegistry.js
packages/ignite-vector-icons/package.json
packages/ignite-vector-icons/templates/vectorExample.js.ejs

Y'all gonna make me lint some code.  Up in here.  Up in here!

Adds linting to all projects.

---

packages/ignite-unholy-app-template/index.js
packages/ignite-unholy-app-template/templates/Tests/Components/AlertMessageTest.js
packages/ignite-unholy-app-template/templates/Tests/Components/DrawerButtonTest.js
packages/ignite-unholy-app-template/templates/Tests/Components/FullButtonTest.js
packages/ignite-unholy-app-template/templates/Tests/Components/RoundedButtonTest.js
packages/ignite-unholy-app-template/templates/Tests/Redux/LoginReduxTest.js
packages/ignite-unholy-app-template/templates/Tests/Redux/TemperatureReduxTest.js
packages/ignite-unholy-app-template/templates/Tests/Sagas/LoginSagaTest.js
packages/ignite-unholy-app-template/templates/Tests/Sagas/OpenScreenSagaTest.js
packages/ignite-unholy-app-template/templates/Tests/Sagas/StartupSagaTest.js
packages/ignite-unholy-app-template/templates/Tests/Sagas/TemperatureSagaTest.js
packages/ignite-unholy-app-template/templates/Tests/Services/FixtureAPITest.js
packages/ignite-unholy-app-template/templates/Tests/Setup.js
packages/ignite-unholy-app-template/templates/package.json.ejs

Adds missing tests from Ignite 1 to unholy.

---

packages/ignite-integration-tests/test/ignite-cli/badCommands.test.js
packages/ignite-integration-tests/test/ignite-cli/noArgs.test.js
packages/ignite-integration-tests/test/ignite-cli/version.test.js
packages/ignite-integration-tests/test/ignite-new/newInvalid.test.js
packages/ignite-integration-tests/test/ignite-new/newMin.test.js

This brings our integration tests back online.

Fixes integration tests.

---

ignite-base/App/Navigation/CustomNavBar.js

* Remove unnecessary 'else' statement
* Fix importing wrong module CustomNavBarStyle

Remove 'else' statement and fix wrong import

---

packages/ignite-cli/src/extensions/ignite.js
packages/ignite-cli/src/extensions/ignite/addComponentExample.js
packages/ignite-cli/src/extensions/ignite/addModule.js
packages/ignite-cli/src/extensions/ignite/addScreenExamples.js
packages/ignite-cli/src/extensions/ignite/copyBatch.js
packages/ignite-cli/src/extensions/ignite/findIgnitePlugins.js
packages/ignite-cli/src/extensions/ignite/generate.js
packages/ignite-cli/src/extensions/ignite/igniteConfig.js
packages/ignite-cli/src/extensions/ignite/ignitePluginPath.js
packages/ignite-cli/src/extensions/ignite/log.js
packages/ignite-cli/src/extensions/ignite/patchInFile.js
packages/ignite-cli/src/extensions/ignite/removeComponentExample.js
packages/ignite-cli/src/extensions/ignite/removeDebugConfig.js
packages/ignite-cli/src/extensions/ignite/removeModule.js
packages/ignite-cli/src/extensions/ignite/removeScreenExamples.js
packages/ignite-cli/src/extensions/ignite/setDebugConfig.js
packages/ignite-cli/src/extensions/ignite/version.js
packages/ignite-cli/tests/extensions/ignite.test.js

Once there lived a giant file and within, functions flourished.  That is, until the explorers came.  They did not know, nor understand what they were seeing.  And they were not pleased.  They demanded order and separation.
And they were right.
Thus began the journey of this PR. And it ends here.  Now.  When you press Merge.
Good luck champion.  The repo (and perhaps the universe) depends on you.
Fixes #689

Refactors the ignite extension.

---

packages/ignite-cli/src/commands/add.js
packages/ignite-cli/src/extensions/reactNative.js

Better fix than #748, thanks to @skellock . Should fix #717. Is there any reason why we need the guard around these lines of code? I can't find any.

Fixes spinner during ignite new

---

packages/ignite-infinite-red-app-template/index.js
packages/ignite-infinite-red-app-template/templates/package.json.ejs

Not a fan of git hooks, but I'll give it another try.  My preference is to catch this these things with CI.
To be truthful, I'm not quite sure what my objection is.  
Fixes #584

Replaces ghooks with husky.

---

packages/ignite-cli/src/brand/header.js
packages/ignite-cli/src/templates/plugin/templates/thing.js.ejs.ejs

I accidentally deleted part of the Ignite header. Sorry Gant!

Reverts accidental CLI header deletion

---

packages/ignite-cli/src/extensions/ignite/addModule.js

The code should be self-documenting.

Adds "version" as an option to addModule

---

packages/ignite-cli/src/extensions/ignite/patchInFile.js
packages/ignite-cli/src/templates/plugin/index.js.ejs

Adds replace as an option to ignite.patchInFile

---

packages/ignite-minimal-app-template/templates/App/Containers/Styles/RootContainerStyles.js
packages/ignite-minimal-app-template/templates/__tests__/index.android.js
packages/ignite-minimal-app-template/templates/__tests__/index.ios.js

Forgot a few files last time around. If we had CI for Ignite 2 it would have caught that. :) Coming soon!

Fixes integration tests for minimal app

---

packages/ignite-cli/src/extensions/ignite/patchInFile.js
packages/ignite-cli/src/templates/plugin/index.js.ejs

Pretty straightforward -- see code.

Adds delete to patching module, cleans up some issues

---

docs/advanced-guides/using-development-build.md
packages/ignite-cli/src/commands/add.js
packages/ignite-cli/src/commands/new.js
packages/ignite-cli/src/extensions/ignite.js
packages/ignite-cli/src/extensions/ignite/pluginOverrides.js
packages/ignite-cli/src/lib/detectInstall.js
packages/ignite-cli/tests/lib/detectInstall.test.js
packages/ignite-infinite-red-app-template/index.js
packages/ignite-minimal-app-template/index.js

You can now run `ignite add elements` to install 3rd party plugins. 
If it's published on npm, you can install it.  Today.
Most of ours plugins aren't there yet, but this is the 👍 to start if they have their proper home & version number (spoiler, ours don't just yet, but other people can!! @dabit3 already has 2 of 'em and @GantMan has 1 or 2, and i believe @robinheinze has one too for radio buttons?).
Now, because we're still developing, this PR introduces another thing: **the ability to override plugin installs.** 🌹 
Lets say you're building `ignite-maps` like @jamonholmgren is.  End users will install with:
```sh
ignite add maps
```
But you don't want to publish that first while you're testing.  If you're building this in `/Users/jamonsux/ignite/maps`, You can:
```sh
export …
```

Plugin Directory Love

---

packages/ignite-cli/src/commands/spork.js

¯\_(ツ)_/¯ about the unicode emoji, but I did want the file output.

Adds output to sporking to show what files were sporked and their paths

---

packages/ignite-cli/src/commands/plugin.js
packages/ignite-cli/src/templates/plugin/index.js.ejs
packages/ignite-cli/src/templates/plugin/package.json.ejs
packages/ignite-cli/src/templates/plugin/test/add.js.ejs
packages/ignite-cli/src/templates/plugin/test/interface.js.ejs
packages/ignite-cli/src/templates/plugin/test/remove.js.ejs

```
$ ignite plugin new wat
$ cd ignite-wat
$ npm install
$ npm test
> ignite-wat@0.0.1 test /Users/jh/Code/ReactNative/playground/ignite-wat
> ava
3 passed
```

Updates generated plugin to include passing tests

---

.gitignore
ignite-base/.gitignore
packages/ignite-basic-generators/.gitignore
packages/ignite-cli/.gitignore
packages/ignite-infinite-red-app-template/.gitignore
packages/ignite-integration-tests/.gitignore
packages/ignite-minimal-app-template/.gitignore

Adds vscode artifacts to .gitignore

---

packages/ignite-basic-generators/commands/component.js
packages/ignite-basic-generators/commands/container.js
packages/ignite-basic-generators/commands/listview.js
packages/ignite-basic-generators/commands/redux.js
packages/ignite-basic-generators/commands/saga.js
packages/ignite-basic-generators/commands/screen.js
packages/ignite-cli/src/extensions/ignite/copyBatch.js
packages/ignite-cli/src/templates/plugin/commands/thing.js.ejs
packages/ignite-infinite-red-app-template/index.js
packages/ignite-minimal-app-template/index.js

A few generators were not printing things.  Now they all do.  Tidied up a few things as I went as well.
Fixes #693

Ensures all generators say things.

---

packages/ignite-cli/src/commands/generate.js

Also hides the plugin generator source behind a `--source` flag.  It's really not that important for most people.  But I didn't want to remove it entirely.
Fixes #685

Improves UI of generators.

---

packages/ignite-cli/src/cli/check.js

I'm not exactly sure if this is what @skellock was going for in #758, but I think it was?
cc @GantMan

Requires Yarn 0.20.0+, if installed.

---

packages/ignite-cli/src/extensions/reactNative.js

In like a lion baby:
https://github.com/facebook/react-native/releases/tag/v0.42.0

Upgrades to React Native 0.42.0.

---

packages/ignite-cli/package.json
packages/ignite-cli/src/cli/cli.js
packages/ignite-cli/src/commands/new.js
packages/ignite-cli/src/extensions/ignite/log.js
packages/ignite-cli/tests/cli/cliConfig.test.js
packages/ignite-cli/tests/cli/cliEmpty.test.js
packages/ignite-cli/tests/cli/cliError.test.js
packages/ignite-infinite-red-app-template/index.js

Per #814, this attempts to better recover from errors. I've confirmed with @robinheinze that this would have displayed somewhat better errors (still need https://github.com/infinitered/gluegun/issues/157 resolved for best errors).

Better errors

---

packages/ignite-ir-boilerplate-2016/package.json

This straightens out the packing list of files inside the package.json of the boilerplate.

Fixes the files list in the boilerplate package.

---

packages/ignite-ir-boilerplate-2016/boilerplate.js

The plugin stuff is no longer needed with boilerplate.js.

Removes old plugin stuff from boilerplate.js.

---

README.md

Bumps the badges up to the top.
Also this is to see if CI works.

Moves the badges up.

---

PLUGINS.md

Updates the plugin list.

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

NO I WILL NOT DESCRIBE THIS PR

Updates README and .github docs for Ignite 2 release

---

lerna.json

Switches lerna back to shared version.

---

lerna.json
packages/ignite-cli/package.json
packages/ignite-dev-screens/package.json

Unfortunately we've got some issue with these tags already claimed. on github, so i'll be switching these up.

Updates to 0.2.0 trial.

---

packages/ignite-cli/src/commands/plugin.js
packages/ignite-cli/src/lib/addEmptyBoilerplate.js
packages/ignite-cli/src/templates/plugin/boilerplate/ignite/ignite.json

Tiny change to generated boilerplate plugins.

Changes createdBy to boilerplate to match naming scheme

---

lerna.json
packages/ignite-cli/package.json
packages/ignite-dev-screens/package.json

i used the npm tag next on this.
```sh
npm i -g ignite-cli@next
```
Will do some testing off that right now.

v1.9.0-alpha.1

---

packages/ignite-dev-screens/templates/DevTheme/Colors.js
packages/ignite-dev-screens/templates/FaqScreen.js
packages/ignite-dev-screens/templates/PresentationScreen.js
packages/ignite-dev-screens/templates/Styles/FaqScreenStyles.js

This adds an actual working FAQ screen with some copy
---
Closes #866

adds FAQ screen

---

lerna.json
packages/ignite-cli/package.json
packages/ignite-dev-screens/package.json

I pushed this up to the next tag on npm.  `npm i -g ignite-cli@next`.  I'm burning version numbers here because i'm having issues getting the deploy right.

v2.0.0-beta.3

---

PLUGINS.md

Adding `ignite-keychain` to the plugins Hall of Fame. 
Also designed to cure @skellock's insomnia. :night_with_stars: :moon:

Added ignite-keychain to Plugins List

---

lerna.json
packages/ignite-cli/package.json
packages/ignite-dev-screens/package.json

v2.0.0-beta.6

---

README.md

add upgrade node to documentation

---

README.md

Add coveralls badge to README

---

packages/ignite-cli/src/cli/check.js

Converts check.js to ES3 syntax

---

packages/ignite-cli/src/extensions/ignite.js
packages/ignite-cli/src/extensions/ignite/addAndroidPermission.js
packages/ignite-cli/src/extensions/ignite/removeAndroidPermission.js
packages/ignite-dev-screens/plugin.js

This creates the awesome new `ignite.addAndroidPermission` function!
@jamonholmgren - I knew we needed it somewhere.
And now we have it.  
@skellock  should I be documenting these additions to `ignite` utils somewhere?
----
Closes:  https://github.com/infinitered/ignite-ir-boilerplate-2016/issues/14

Add android permission

---

README.md
docs/quick-start/getting-started.md
docs/quick-start/nvm-to-n.md

Adds recommendation to use n for node version management and instructions to switch from nvm to n.

Add recommendation to use n and instructions on how to switch from nvm to n

---

packages/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js
packages/ignite-cli/src/extensions/ignite/patchInFile.js
packages/ignite-cli/src/extensions/patching.js

insert should check if item already exists, and then not do it unless forced.

smart patching

---

packages/ignite-cli/src/templates/plugin/boilerplate.js.ejs
packages/ignite-cli/src/templates/plugin/commands/thing.js.ejs
packages/ignite-cli/src/templates/plugin/plugin.js.ejs

Just a few comments in the plugin template to point people in the right direction.

Adds references to gluegun api docs

---

packages/ignite-cli/src/commands/new.js
packages/ignite-cli/src/commands/plugin.js
packages/ignite-cli/src/extensions/ignite/copyBatch.js
packages/ignite-cli/src/lib/detectInstall.js
packages/ignite-cli/tests/cli/_mockGluegunBuilder.js
packages/ignite-dev-screens/templates/ComponentExamplesScreen.js
packages/ignite-dev-screens/templates/FaqScreen.js
packages/ignite-dev-screens/templates/PluginExamplesScreen.js
packages/ignite-integration-tests/test/ignite-cli/noArgs.test.js
packages/ignite-integration-tests/test/ignite-cli/version.test.js
packages/ignite-integration-tests/test/ignite-new/newInvalid.test.js

Fixes #906 and #930. Adds a little more coverage for `ignite new`.

Fixes integration tests and adds a couple more for ignite new

---

lerna.json
packages/ignite-cli/package.json
packages/ignite-dev-screens/package.json

v2.0.0-beta.8

---

docs/quick-start/ignite-commands.md

Fix document typo

---

README.md

This PR will add a note in `README.md` about premium support offered by Infinite Red.
@skellock

Add README section about premium support

---

docs/advanced-guides/creating-plugins.md
packages/ignite-cli/src/templates/plugin/plugin.js.ejs

- [x ] `./docs/` has been updated with your changes, if relevant
- Updates creating-plugins doc with up-to-date info
- Updates plugin.js.ejs with working example of how to remove a line that was patched into a file.

Updating creating-plugins doc and plugin.js.ejs

---

PLUGINS.md

For greater consistency/readability.

Update third party plugins list to table

---

README.md
packages/ignite-dev-screens/templates/PluginExamplesScreen.js
packages/ignite-dev-screens/templates/PresentationScreen.js

Added attributes to `StackNavigator` to fix white flash.
https://github.com/infinitered/ignite-ir-next/issues/14

Fix flash on navigation transitions

---

PLUGINS.md

```sh
ignite add fetch-blob
ignite add img-cache
```
Used for faster image downloads and image caching.

Adds links to 2 new ignite plugins.

---

README.md

Users have had some trouble finding documentation for React Native features, hopefully this will help.

Add a couple links to React Native's Getting Started page

---

README.md

* Adds a Plugins header and direct link to `./PLUGINS.md`
* Update header emojis

Update Readme to include Plugins link - change emojis

---

.github/CONTRIBUTING.md

Less than two months late! :shame: :shame: :shame:

Adds getting started instructions to CONTRIBUTING.md

---

packages/ignite-cli/src/extensions/ignite/addPluginComponentExample.js
packages/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js
packages/ignite-cli/src/extensions/ignite/setDebugConfig.js

Next step will be moving `patchInFile` up into gluegun.

Update calls to insertInFile to patchInFile

---

docs/advanced-guides/tour.md

Minor fixes to tour documentation per @skellock

---

PLUGINS.md

Add 3 new plugins

---

docs/advanced-guides/creating-plugins.md

Improves doc for creating plugins

Improve CreatePlugin doc

---

bin/testRelease

adding integration tests to CI

Integration tests

---

lerna.json
packages/ignite-cli/package.json
packages/ignite-dev-screens/package.json

v2.0.0-beta.9

---

src/commands/new.js

Addresses #975 
Guard against igniting a new project with name `ignite` or `Ignite`. 👍

Guard against ignite new ignite

---

src/commands/new.js
src/lib/detectInstall.js
src/lib/prependIgnite.js
tests/fast/lib/detectInstall.test.js

Properly detects relative paths in boilerplate flag

---

README.md

Removes the codacy badge.

---

README.md

Adds boilerplate cli syntax

---

BOILERPLATES.md

Fixed incorrect link in the boilerplates markdown

Fixed link to the nativebase boilerplate

---

src/extensions/ignite/addComponentExample.js
src/extensions/ignite/addPluginComponentExample.js
src/extensions/ignite/addPluginScreenExamples.js
src/templates/plugin/boilerplate.js.ejs

Fixes #690 and adds deprecation warning so we can fix any plugins soon.

Adds deprecation warning when no .ejs extension for template

---

src/commands/add.js

Use proper terminology and exit code per @skellock

---

bin/ci
src/extensions/ignite/addPluginComponentExample.js
src/extensions/ignite/addPluginScreenExamples.js
tests/integration/ignite-new/new.test.js

Minor tweaks

---

src/extensions/ignite/addPluginComponentExample.js
src/extensions/ignite/addPluginScreenExamples.js

Fix for wrong example files being generated.

---

src/commands/new.js
src/commands/remove.js
src/extensions/ignite/addModule.js
src/lib/detectInstall.js
src/lib/prependIgnite.js
tests/fast/cli/cliConfig.test.js
tests/fast/extensions/findIgnitePlugins.test.js
tests/fast/extensions/ignite.test.js
tests/fast/lib/detectInstall.test.js

This fixes #1093 100% and probably fixes a good bit of other Windows issues.
❤️

lots of windows love

---

README.md

Added the warning on Node V8 debugging as discussed in #1107

Update README.md Node V8 debugging warning #1107

---

src/commands/new.js
tests/integration/ignite-new/newInvalid.test.js

Signed-off-by: Pekka Gaiser <pekka@gmx.de>
Fixes #1116. 
This is actually my first pull request _ever_! So excited! :)
Let me know if anything needs correcting.

Adds check and rejection for numbers-only project name

---

docs/README.md
docs/quick-start/spork.md

I added some basic info to the docs about the spork command. #1146

Added info about the spork command to the docs.

---

PLUGINS.md

- [ X ] Everything works on iOS/Android
- [ X ] `npm test` **ava** tests pass with new tests, if relevant
- [ X ] `./docs/` has been updated with your changes, if relevant
Added a new plugin to plugins.md

Added plugin to PLUGINS.md

---

bin/ci

Fix for #1154 - tested locally and ready to go.

integration tests of new generator command list

---

PLUGINS.md

Update PLUGINS.md with new redux-devtools plugin

---

.travis.yml
README.md
bin/ci
package-lock.json
package.json

Addresses: #876
Updates bin/ci and Semaphore to report test coverage to coveralls.io.

Add coveralls coverage reporting

---

PLUGINS.md
bin/ci

Add redux-persist to plugins list

---

BOILERPLATES.md

Adds a link to ignite-typescript-boilerplate

Add ignite-typescript-boilerplate link

---

docs/README.md
docs/quick-start/frequently-asked-questions.md

Anytime an issue is opened that's a common question, we can encourage the issue author to open a PR adding the question with a link to said issue to `docs/quick-start/frequently-asked-questions.md` (assuming the question is answered)
We can then use the `docs:faq` label to label issues which are linked to from the FAQ.

Add frequently asked questions to docs.

---

docs/README.md
docs/quick-start/frequently-asked-questions.md

Poor shruggy had a broken arm. 😢

Update FAQ Formatting

---

docs/advanced-guides/creating-boilerplates.md
docs/advanced-guides/creating-plugins.md
docs/quick-start/ignite-commands.md
docs/quick-start/project-structure.md
docs/quick-start/using-boilerplates.md

Updating a few minor typos in the docs for consistent legibility.

Update minor typos

---

docs/quick-start/frequently-asked-questions.md

- [x ] Everything works on iOS/Android
- [x ] `npm test` **ava** tests pass with new tests, if relevant
- [x ] `./docs/` has been updated with your changes, if relevant
Added to FAQ an entry about the ChainReact app

Add chainreact faq entry

---

README.md

The README did not have a direct link to the Infinite Red contact page.
This pull request adds one.
Why?
To reduce the amount of effort potential leads may have coming in. :)

Updated readme to include link to contact page.

---

PLUGINS.md

An ignite plugin for react-native-camera.

Update PLUGINS.md with new react-native-camera plugin

---

src/extensions/ignite.js

Fixed failure when missing yarn

---

README.md

[#1232] Update Readme

---

package.json

revert manual version bump

---

README.md
src/commands/new.js

I updated readme and changed Bowser to "Beta"

Change bowser to beta

---

PLUGINS.md

* Re-ordering plugins alphabetically
* Adding native-navigation plugin

Re-order plugins and added native-navigation plugin

---

README.md
src/commands/new.js

We're taking [Bowser](https://github.com/infinitered/ignite-ir-boilerplate-bowser) out of Beta, so this updates text throughout the CLI to no longer refer to Bowser as "beta".

Prepare for taking Bowser out of beta

---

package.json

Bump the version number (to incorporate #1315)

Bump version to 2.1.2

---

README.md

Looks like the conference is over, seems like a good time to drop the note :)

README update: The conference is over

---

src/commands/new.js
tests/integration/ignite-new/new.test.js
tests/integration/ignite-new/newInvalid.test.js

Add project name validation

---

README.md
docs/quick-start/built-with-ignite.md
package-lock.json

Initial list of production apps that were built using Ignite.

Initial implementation of Built With Ignite list

---

BOILERPLATES.md

added my boilerplate

---

.circleci/config.yml
package.json

Added CircleCI Config

---

src/commands/add.js
src/commands/remove.js

- Updated the `add` and `remove` error, if the project is a bare RN one. [See issue](https://github.com/infinitered/ignite/issues/1338)

Updated add/remove error

---

BOILERPLATES.md
README.md
src/commands/new.js
tests/integration/ignite-new/new.test.js

Updates ignite boilerplate references in preparation for renaming those packages. I just wanted to get eyes on the code changes ahead of time to make sure everything looks good and I didn't miss anything.
Depends on:
https://github.com/infinitered/ignite-ir-boilerplate-andross/pull/235
and
https://github.com/infinitered/ignite-ir-boilerplate-bowser/pull/133

Update repo with new boilerplate names

---

src/commands/new.js

Add closing paren to andross boilerplate description (see twitch chat above from byteconf).

Add closing paren to andross boilerplate description

---

src/commands/boilerplate-install.js

Print error stack for requiring boilerplate

---

src/commands/add.js
src/commands/remove.js
src/lib/detectInstall.js

Enables scoped packages to be added and removed
Tested by adding and removing a scoped package from npm.
Fixes https://github.com/infinitered/ignite/issues/1325

Ignite scoped packages

---

README.md

Add quote by Jon Ruddell to readme

---

src/lib/detectInstall.js

Remove console.log

---

.gitignore
package.json
src/commands/doctor.js

Fix issue with ignite doctor when yarn is not installed

---

BOILERPLATES.md
src/commands/new.ts

- Removes `beta` tag from `ignite-jhipster` boilerplate choice
- Fixes name spelling

Remove beta tag from jhipster boilerplate

---

src/cli/check.js

Should resolve #1431 but please check before merging.

Checks for XCode available in CLI

---

package.json
yarn.lock

Upgrades gluegun and properly copies plugin templates

---

README.md

Add RNN badge and link to readme

---

README.md

Adds Jamon's React Live Amsterdam talk to the README.

Update README with Jamon's live coding talk

---

src/lib/show-plugin-directory.ts

Add [Installed] label if ignite plugin is installed when user launch `ignite list`
Fixes #1028

Find locally installed plugins and display [Installed] if found

---

docs/quick-start/ignite-commands.md

- [ x] `./docs/` has been updated with your changes, if relevant
Make available CLI options a bit more explicit in the docs.

Add more cli options to docs

---

README.md

Adding graphic for Jon Ruddell quote requested in this issue: [https://github.com/infinitered/ignite/issues/1467](https://github.com/infinitered/ignite/issues/1467)

Graphic for README

---

src/commands/doctor.ts

Also updated the arrangement of the table to fit a little nicer.

Adds ignite source folder to ignite doctor output

---

PLUGINS.md

Adding ignite-splashscreen to Plugins list

Added ignite-splashscreen to PLUGINS list

---

tests/integration/ignite-new/new-bowser.test.js

Fixing tests on https://github.com/infinitered/ignite/pull/1515
cc @jamonholmgren

Fixed integration test

---

src/commands/add.ts
src/commands/remove.ts
tests/integration/ignite-new/new-bowser.test.js

Use toolbox exec rather than Shell

---

docs/quick-start/ignite-commands.md
src/lib/detect-install.ts
src/lib/import-plugin.ts
src/types.ts
tests/fast/lib/detectInstall.test.js

Hi @jamonholmgren , 
I have added a support for Git source for `detectInstall`, and did some refactoring for `importPlugin`.
now we could initialise with git-url boilerplate
```sh
$ ignite new MyAwesomeApp -b git@github.com:infinitered/ignite-andross.git
$ ignite new MyAwesomeApp -b https://github.com/infinitered/ignite-andross.git
```

feat: Add Git Source Support

---

bin/ignite-cli

**Issue:**
This PR is linked to the issue: https://github.com/infinitered/ignite/issues/1487
**Summary of changes:**
Added a new file for ignite-cli under bin that refers ignite

Add ignite-cli binary command

---

PLUGINS.md

Adding [ignite-code-push](https://github.com/osedea/ignite-code-push) plugin 🙂

Added code-push plugin

---

src/extensions/ignite/patch-in-file.ts

Return if file to patch not found

---

src/commands/doctor.ts

get uniq generator names and join them for display in `ignite doctor`
fixes #1490

fix: format ignite doctor generators nicely

---

README.md

Add TrailBlazers Demo App to Readme

---

.circleci/config.yml
src/commands/help.ts
src/lib/print-commands.ts
tests/integration/ignite-new/new-bowser.test.js
yarn.lock

Fixes #845
I have the desired commands showing in ignited and non-ignited dirs:
(I deleted `ignite.json` to simulate a non-ignite directory`)

Only list commands available in directory

---

BOILERPLATES.md

Based on information provided in this comment, among others: https://github.com/infinitered/ignite-andross/issues/300#issuecomment-578286469
Updates the list of officially maintained boilerplates based on comments provided to the community, such as [this](https://github.com/infinitered/ignite-andross/issues/300#issuecomment-578286469).

Update list of boilerplates actively supported by IR

---

docs/Generators.md

fix typo in generators documentation

docs: fix typo in generators

---

README.md

Just noticed that the Ignite CLI 4.0 blog post url was empty and added it!

docs: fixed Ignite CLI 4.0 blog post url

---

boilerplate/assets/fonts/custom-fonts.md

Just a tiny typo + removing the bowser reference ⌨️

docs: custom font typo + bowser mention

---

src/commands/new.ts
src/tools/pretty.ts

Addresses https://github.com/infinitered/ignite/issues/1619
Adds loading spinner to ignite new command steps (with emojis).
Demo @ 60x speed:
https://user-images.githubusercontent.com/53795920/115897204-688ada00-a419-11eb-8605-8b8327ff3a79.mov

Add spinner to new steps

---

boilerplate/app/components/text/text.props.ts
boilerplate/app/i18n/translate.ts

This is a small typo I noticed.

small typo I18n -> i18n

---

README.md

Replaced ignite by npx ignite-cli in README

Replaced ignite by npx ignite-cli in README

---

boilerplate/ios/HelloWorld.xcodeproj/project.pbxproj
boilerplate/ios/Podfile.lock
boilerplate/package.json
boilerplate/storybook/views/story.tsx
boilerplate/yarn.lock
yarn.lock

Updated React Native to 0.64.1, to handle Xcode 12.5.
More information here https://github.com/facebook/react-native/releases/tag/v0.64.1

Updated React Native to 0.64.1

---

boilerplate/package.json
boilerplate/yarn.lock

This nifty libs helps a lot when ones environment is out of sync or is misbehaving.
Note that this is a dev dependency.
2 scripts has been added, `clean` and `clean-all`. The former is interactive and the latter cleans everything.

Added react-native-clean-project 

---

boilerplate/app/screens/demo/demo-list-screen.tsx

Converts ObservableArray to Array with a spread to make demo FlatList re-render on mst store data change.

fix(boilerplate): make demo flatlist re-render on mst store data change

---

boilerplate/app/components/button/button.tsx
boilerplate/app/components/checkbox/checkbox.tsx
boilerplate/app/components/form-row/form-row.tsx
boilerplate/app/components/switch/switch.tsx
boilerplate/app/components/text-field/text-field.tsx
boilerplate/app/components/text/text.tsx
boilerplate/app/components/wallpaper/wallpaper.tsx

Drop redundant flatten. RN flatten styles by default

---

boilerplate/app/components/auto-image/auto-image.tsx

Just a comment on the new AutoImage HOC

Adds comment for AutoImage HOC

---

docs/Generators.md

Change all "ignite" commands to "ignite-cli"

Update Generators.md documentation

---

.github/ISSUE_TEMPLATE.md

Updating the issue template to have the correct ignite doctor command.

Fix ignite doctor command in issue template

---

README.md
docs/Folder-Structure.md
docs/MobX-State-Tree.md
docs/Tour-of-Ignite.md

This makes some minor updates to documentation and also fleshes out the Tour of Ignite documentation.

chore(docs): Updates to documentation, finished Tour of Ignite

---

boilerplate/app/components/bullet-item/bullet-item.story.tsx
boilerplate/storybook/storybook-registry.ts

This PR adds missing story for bullet-item component.

Add  bullet-item component story

---

boilerplate/ignite/templates/navigator/NAME-navigator.tsx.ejs

Append "Navigator" to name of navigator component in navigator template. resolves #1854
**Note**: I tried to run tests (used both  `yarn test` and `yarn ci:test`) right after cloning the repo but it got stuck at *test/ignite-new.test.ts*, so this PR is not tested :cry:

fix: update component name in navigator template

---

src/commands/new.ts

Related issue: https://github.com/infinitered/ignite/issues/1872

fix(cli): fix react native getting started link

---

README.md

Updated Navigation number from 5 to 6

Updated Navigation number

---

boilerplate/app/components/auto-image/auto-image.story.tsx

Fixing wrong path at ./boilerplate/app/components/auto-image/auto-image.story.tsx which causes error on launch.

Fix Rick - Unable to resolve module ./rick.png #1884

---

.circleci/config.yml
.solidarity
boilerplate/.solidarity
package.json
yarn.lock

Add solidarity to CLI and update versions in boilerplate.

Update solidarity in CLI and boilerplate

---

boilerplate/app/navigators/navigation-utilities.tsx

_( n/a )_
comment typo fix in `boilerplate/app/navigators/navigation-utilities.tsx`
\#firstpr

code comment typo fix

---

boilerplate/package.json

https://github.com/infinitered/reactotron-react-native/issues/768#issuecomment-1124537131

bump reactotron dependency to 5.0.2

---

README.md

Updated Jamon Holmgren's talk which contain better audio.

README.md Updated [youtube link]

---

boilerplate/app/models/character-store/character-store.ts
boilerplate/app/models/character/character.ts
boilerplate/ignite/templates/model/NAME.ts.ejs

After a conversation with Jamon on how the types currently are, the lines could be cleaned up and unified into a single line. This PR updates them to follow that conversation in both the boilerplate demo "character" stores and templates.

TypeScript Udates

---

README.md

Updated Node LTS version to mention v16 instead of v14 🙂

Update README Node LTS to v16

---

boilerplate/bin/postInstall

Resolves: #1972
> Simple patch to check if iOS folder exists before change directory to iOS and pod install.

Fix/ignite expo boostrap 7.14.0

---

.github/ISSUE_TEMPLATE.md
README.md

- Closes #1924 
- Added troubleshooting tips to README
- Updated issue template with a link to troubleshooting section of README

docs(readme): #1924 added more troubleshooting tips

---

boilerplate/app/components/Icon.tsx
docs/Components-AutoImage.md
docs/Components-Icon.md
docs/Components.md

* Update docs for AutoImage
* Update docs for Icon
* Update `IconProps` to type the `onPress` prop
* Update `Icon` component to only pass `color` if present

Update docs for AutoImage and Icon components

---

boilerplate/app/screens/DemoComponentsScreen/DrawerIconButton.tsx

Fixes the drawer icon pointing the wrong direction to close the drawer in RTL mode
|    `Before`    |    `After`    |
| ------------------------------- | ------------------------------- |
|<img width="372" alt="image" src="https://user-images.githubusercontent.com/374022/185702342-38d03981-3e12-4cee-838f-9c09c77d07be.png">|<img width="360" alt="image" src="https://user-images.githubusercontent.com/374022/185702475-c5ce7db8-7ab7-4682-b33a-4b3f8a1f3035.png">|

Fix: properly rotates drawer icon in RTL mode

---

boilerplate/app/components/checkbox/checkbox.tsx
boilerplate/app/theme/colors.ts

Fixing some errors from incompatibilities from https://github.com/infinitered/ignite/pull/2045

Fix checkbox

---

boilerplate/app/models/Episode.test.ts
boilerplate/app/models/Episode.ts
boilerplate/app/models/EpisodeStore.ts
boilerplate/app/screens/DemoPodcastListScreen.tsx
boilerplate/app/theme/spacing.ts
boilerplate/package.json

- Adds metadata to RNR episode cards and persistent like button. 
https://user-images.githubusercontent.com/6894653/186272093-211a4e92-bb90-4f25-989e-66ed5bdd713b.mp4

RNR Metadata And Favorites

---

boilerplate/app/i18n/ar.ts
boilerplate/app/i18n/en.ts
boilerplate/app/i18n/ko.ts
boilerplate/app/models/EpisodeStore.ts
boilerplate/app/navigators/DemoNavigator.tsx
boilerplate/app/screens/DemoCommunityScreen.tsx
boilerplate/app/screens/DemoPodcastListScreen.tsx
boilerplate/app/utils/open-link-in-browser.ts

- Adds link to audio file when use presses on each episode card
- Adds Switch to filter by favorites (NOTE: @yulolimum is working on updating the design of this component in #2044, so it will look better after that)
https://user-images.githubusercontent.com/6894653/186535274-04273c19-3878-4953-8676-67a011e0ef76.mp4
https://user-images.githubusercontent.com/6894653/186535298-ab5a52a2-b51d-4f2e-8e95-bd3818d498d7.mp4

Maverick rnr link

---

src/tools/__snapshots__/path.test.ts.snap
src/tools/path.test.ts

Make snapshot tests consistent across machines

Fix `path.test` snapshot

---

boilerplate/app/screens/DemoCommunityScreen.tsx
boilerplate/app/screens/DemoDebugScreen.tsx

For languages that are RTL, carets or arrow point in the direction that the new window opens. This PR fixes this.

fix(i18n): Fixes direction of caret on links for RTL

---

src/commands/new.ts

Resolves https://github.com/infinitered/ignite/issues/2074

Prevent `new` command error when installing deps

---

README.md

Adds new Maverick home screen to main Ignite README. Fixes #2088

Change README image to Maverick home screen

---

src/commands/new.ts

Closes https://github.com/infinitered/ignite/issues/2084

Explicitly call process.exit(0) at the end of the `new` command

---

src/commands/remove-demo.ts
test/vanilla/ignite-remove-demo.test.ts

Fixes test failures due to remove-demo issues.

Add ignore paths to `remove-demo` command

---

src/tools/generators.ts

Improves generator update output

---

boilerplate/app/navigators/navigation-utilities.tsx
boilerplate/app/utils/is-mounted.ts

fix (#1942): Prevent trying to update the component if component is not mounted

---

docs/Remove-Demo-Code.md
src/commands/remove-demo.ts

Add `--dry-run` to `remove-demo` command

---

boilerplate/app/navigators/AppNavigator.tsx
boilerplate/app/screens/DemoPodcastListScreen.tsx

Thanks for the awesome work with the new Maverick version!
Here's some misc fixes that closes #2152 and #2143
| Before | After |
| ------------- | ------------- |
| ![Simulator Screen Shot - iPhone 13 - 2022-09-13 at 15 05 31](https://user-images.githubusercontent.com/4250593/190017807-c62f6394-d44b-4db7-879b-8a4330419a59.png) | ![Simulator Screen Shot - iPhone 13 - 2022-09-13 at 15 05 49](https://user-images.githubusercontent.com/4250593/190017912-5ba00c7c-cad8-4266-ad37-1a41d94ad0bf.png) |
| ![Simulator Screen Shot - iPhone 13 - 2022-09-13 at 14 51 29](https://user-images.githubusercontent.com/4250593/190015965-8fe4600b-9a70-4e73-8ab4-b974f227aeae.png)  | ![Simulator Screen Shot - iPhone 13 - 2022-09-13 at 14 51 04](https://user-images.githubusercontent.com/4250593/190016462-62595df0-6e1 …

Fix AppNavigator whitespace error, fix EpisodeCard rendering issue

---

boilerplate/app/navigators/AppNavigator.tsx

Move `@demo remove-start-block` to correct line in `AppNavigator.tsx`

Move `// @demo remove-block-start` in AppNavigator

---

boilerplate/ignite/templates/model/NAME.ts.ejs
docs/Generator-Templates.md
test/vanilla/ignite-generate.test.ts

Add tests for model generation and update docs

Add test for `ignite generate model` and update Generator Template docs

---

boilerplate/app/components/Card.tsx
docs/Components-Card.md
docs/Components.md

docs(component): Create documentation for the new maverick Card component

---

src/commands/new.ts
src/tools/pretty.ts

Simplify highlights in `new` command

---

README.md
docs/Guide.md
src/tools/validations.ts

Updates README to be more in line with Maverick.
[Here](https://github.com/infinitered/ignite/blob/dca8a8c8980727178121350452db6f9119a70b14/README.md) is a more readable version of the README.

Maverick readme

---

docs/Guide.md
docs/README.md
docs/Upgrading-Ignite.md

Maverick troubleshooting setup

---

package.json
src/commands/new.ts

Resolves https://github.com/infinitered/ignite/issues/2163

Fix fatal `new` command error

---

docs/Components-Card.md

Just a quick missed markdown formatting to make the `<Card ... />` snippet easier to read

Formatted code snipper for Card docs

---

docs/README.md
docs/Releases.md
docs/Tour-of-Ignite.md
package.json

[maverick] Adds Release docs

---

boilerplate/ignite/templates/screen/NAMEScreen.tsx.ejs
boilerplate/ios/Podfile.lock
boilerplate/package.json

[Maverick] Fix screen template, Detox

---

docs/Theming-Fonts-And-Typography.md

Documents adding a new custom font and closes #2095

docs(fonts): explanation of adding a custom font

---

src/commands/new.ts

Resolves https://github.com/infinitered/ignite/issues/2174

Simplify `.gitignore` copy logic

---

boilerplate/app/components/Button.tsx
boilerplate/app/components/Toggle.tsx
boilerplate/app/i18n/ar.ts
boilerplate/app/i18n/en.ts
boilerplate/app/i18n/ko.ts
boilerplate/app/screens/DemoShowroomScreen/demos/DemoToggle.tsx
boilerplate/ios/Podfile.lock

- Resolves #2180.
- Adds "helper" functionality/props to Toggle.
- Adds error tint to label/helper in Toggle when.
- Removes border from switch variant.
- Fixes switchAccessibility tint.
- Fixes radio variant regression.

More Toggle updates.

---

docs/README.md
docs/Theming-Spacing.md

- Adds a few missing sections to the README (`Backend API Integration`, `Remove Demo Code` and `Navigation`)
- Added sub sections for `Theming` and `Components` to match `Generators`

Updated docs/README.md

---

.github/PULL_REQUEST_TEMPLATE.md
src/commands/new.ts

- Fixes #2188
- Updates PR template with the correct `yarn test` command

Initialize git repository on Windows using separate cmds in `new` command

---

boilerplate/package.json

Closes #2169 and launches successfully after generating a new project

Add `--active-arch-only` to `yarn android`

---

boilerplate/package.json
docs/Testing.md

Resolves https://github.com/infinitered/ignite/issues/2102

Fill out `docs/Testing.md`

---

boilerplate/app/screens/ErrorScreen/ErrorBoundary.tsx
docs/Error-Boundary.md

Resolves https://github.com/infinitered/ignite/issues/2093

Add Error Boundary docs

---

boilerplate/package.json

add expo-file-system to fix error with font loading (#2206)

fix(boilerplate): add expo-file-system dependency (#2206)

---

boilerplate/package.json

Removed unused type definition package

---

boilerplate/app/components/AutoImage.tsx
boilerplate/app/components/EmptyState.tsx
boilerplate/app/theme/colors.ts
boilerplate/app/theme/typography.ts
boilerplate/react-native.config.js
docs/Expo-and-Ignite.md
docs/Navigation.md
docs/Styling.md

Refactor less critical MAVERICKTODO to general TODO for release

refactor(boilerplate, docs): MAVERICKTODOS -> TODOS

---

boilerplate/ignite/templates/component/NAME.tsx.ejs
boilerplate/ignite/templates/navigator/NAMENavigator.tsx.ejs
boilerplate/ignite/templates/screen/NAMEScreen.tsx.ejs

These are already implemented, so they are safe to remove

Remove MAVERICKTODOS from generators

---

boilerplate/app.json
boilerplate/ios/HelloWorld.xcodeproj/project.pbxproj
src/commands/new.ts

Fixes #2216.
Also properly tracks Ignite CLI run timing (doesn't include time spent answering questions).

Fix: rename -- catch all bundle ID instances

---

docs/Releasing-Ignite.md

**before**
**after**
Changing a bit of the copywriting to be crystal clear. 
This is "how we release Ignite" **and not** "How an Ignite app should be released to the stores".

chore(docs): Fixing Releasing Ignite link

---

boilerplate/app/components/EmptyState.tsx
docs/Components-EmptyState.md
docs/Components.md
docs/Folder-Structure.md
docs/README.md

- Adds documentation for the reusable `<EmptyState />` component
- Closes #2204

Added EmptyState documentation

---

src/commands/new.ts

- Adds prompt about removing demo code to the `new` walkthrough
- Closes #2178

Added remove demo prompt to walkthrough

---

docs/Components-Toggle.md
docs/Components.md

docs(components): Add documentation for new Maverick Toggle Component

---

boilerplate/app/i18n/ar.ts
boilerplate/app/i18n/en.ts
boilerplate/app/i18n/ko.ts
boilerplate/app/models/AuthenticationStore.ts
boilerplate/app/navigators/DemoNavigator.tsx
boilerplate/app/screens/DemoDebugScreen.tsx
boilerplate/app/screens/WelcomeScreen.tsx
src/tools/demo.test.ts

- Closes #2215
- Moves Debug tab to the fourth position on the tab bar
- Adds logout button to the Debug screen
- Refactors logout function to store action for Welcome and Debug screen usage

Add Logout button to Debug screen

---

boilerplate/ignite/templates/component/NAME.tsx.ejs

- Update the component generator template to pass the styles into an array of styles

fix: update styles array in component generator template

---

boilerplate/app/services/api/api.ts

Noticed a typo for `// @demo remove-current-line` in `boilerplate/app/services/api/api.ts`. Updated typo and updated `test/vanilla/ignite-remove-demo.test.ts` snapshot

fix(api): remove-curent-line to remove-current-line

---

docs/Testing.md

- Closes #2267 
Just removed some brackets around the markdown link

docs(testing): fixed link to detox readme

---

boilerplate/app/screens/DemoPodcastListScreen.tsx

docs(demo-podcast): FlashList recipe link [skip ci]

---

boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
boilerplate/package.json

fix(expo-web): fixed issue when using yarn

---

boilerplate/app/components/AutoImage.tsx

Fixing typo, shouldn't break anything. I've double-checked with Grammarly for grammar correctness.

Fix typo for useAutoImage hook document

---

docs/Components.md
docs/Generators.md
docs/Ignite-CLI.md
src/commands/cache.ts

- Closes #2291
- Initial go at documenting the power behind the CLI!

docs(cli): added new documentation for Ignite CLI

---

boilerplate/ios/Podfile.lock
boilerplate/package.json

- Upgrades react-native to 0.69.7 to get the Android fixes for https://github.com/facebook/react-native/issues/35210

fix(boilerplate): update RN to 0.69.7 for android fixes

---

README.md

New splash image, thanks to @JenFucci!

Update the README splash image

---

boilerplate/app/components/Card.tsx
boilerplate/app/components/Toggle.tsx
boilerplate/app/screens/DemoPodcastListScreen.tsx
boilerplate/app/screens/DemoShowroomScreen/DemoDivider.tsx
boilerplate/app/screens/DemoShowroomScreen/DrawerIconButton.tsx
boilerplate/app/screens/DemoShowroomScreen/demos/DemoAutoImage.tsx

- Noticed some `marginLeft` and `marginRight` in the `<Card />` component while working in the Chain React app, fixing these upstream for better RTL support

fix: margin/padding left/right to start/end for better RTL support

---

boilerplate/app/models/AuthenticationStore.ts

fix: do not store password  in AsyncStorage by default

---

boilerplate/app/screens/ErrorScreen/ErrorBoundary.tsx

fix(screens): ErrorBoundary invalid should update (#2323)

---

src/tools/generators.ts

fix(cli): fixed frontmatter clean up in generate cmd

---

.circleci/config.yml

Add `context: infinitered-npm-package` to circleci package to source NPM_TOKEN and GITHUB_TOKEN env keys

fix(.circleci): add context: infinitered-npm-package

---

boilerplate/app/screens/LoginScreen.tsx

Just updated the spelling of a the word "credentials," thought i'd make the change.

fix(boilerplate) fixed a misspelling of credentials

---

README.md

- Add a link over to Ignite Cookbook (🎉 ) from the README

Add cookbook link to main Ignite README

---

src/commands/generate.ts
src/tools/generators.ts
test/vanilla/ignite-generate.test.ts

- For this issue https://github.com/infinitered/ignite/issues/2354
- Add possibility to overwrite or not files when using command generate
- Don't remove files that exists when using command generate  unless they specifiy the property --overwrite in it.

enhancement(cli) : add overwrite option when using generate command

---

boilerplate/detox/README.md
boilerplate/detox/firstTest.spec.js

Previous link went to a 404 page.
Help users avoid an extra search by providing the correct link :)

Correct link to Detox README

---

boilerplate/app/services/api/apiProblem.ts

Fix getGeneralApiProblem return type

---

README.md

It updates README with the latest versions of expo and react native.

docs: update readme with latest versions

---

boilerplate/app/components/Button.tsx
boilerplate/app/components/Card.tsx
boilerplate/app/components/EmptyState.tsx
boilerplate/app/components/Header.tsx
boilerplate/app/components/ListItem.tsx
boilerplate/app/components/TextField.tsx
boilerplate/app/components/Toggle.tsx
boilerplate/app/navigators/DemoNavigator.tsx
boilerplate/app/screens/DemoCommunityScreen.tsx
boilerplate/app/screens/DemoDebugScreen.tsx
boilerplate/app/screens/DemoPodcastListScreen.tsx
boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
boilerplate/app/screens/DemoShowroomScreen/DemoUseCase.tsx
boilerplate/app/screens/DemoShowroomScreen/DrawerIconButton.tsx
boilerplate/app/screens/DemoShowroomScreen/demos/DemoAutoImage.tsx
boilerplate/app/screens/DemoShowroomScreen/demos/DemoCard.tsx
boilerplate/app/screens/DemoShowroomScreen/demos/DemoIcon.tsx
boilerplate/app/screens/DemoShowroomScreen/demos/DemoListItem.tsx
boilerplate/app/screens/DemoShowroomScreen/demos/DemoTextField.tsx
boilerplate/app/screens/DemoShowroomScreen/demos/DemoToggle.tsx
boilerplate/app/screens/ErrorScreen/ErrorDetails.tsx
boilerplate/app/screens/LoginScreen.tsx
boilerplate/app/screens/WelcomeScreen.tsx
boilerplate/app/theme/spacing.ts

fix: updated spacing names to be consistent with text sizes

---

boilerplate/app/screens/ErrorScreen/ErrorBoundary.tsx
docs/Error-Boundary.md

docs: migrate link from reactjs.org to react.dev for ErrorBoundary

---

boilerplate/package.json

Adds `@expo/metro-config` explicitly to package.json to resolve https://github.com/infinitered/ignite/issues/1931

Add @expo/metro-config@^0.7.1

---

docs/Components-Button.md

The changes made are grammatical and do not affect the ideas communicated in the file.

grammatical changes made to Components-Button.md

---

README.md

docs: Update README.md -- add Getting Started video link

---

boilerplate/README.md

Updated the boilerplate README.md to include assets directory and how to use and organise them.

docs: add documentation for the assets directory

---

src/commands/rename.ts

In a recent RN version, the AndroidManifest.xml dropped the package name which we were using as part of the bundle id detection (Ignite v8 and earlier), so this command broke
- We're using app.json for the name of the app, so just use the bundle identifier coming from there
- This also will now work for Ignite v9 and up, as we may not always have the native dirs around in a managed or custom dev client workflow
- Ignite v9 Expo Go (no native dirs)
- Ignite v9 prebuild
- Closes #2491

fix(cli): rename command ignite v9 compat

---

src/commands/doctor.ts

- Updates `doctor` command to provide `bun` version and path

feat(cli): adds bun path / version to doctor

---

boilerplate/app/devtools/ReactotronConfig.ts

This adds a custom command to the boilerplate for reactotron to show the react native dev menu.

feat(boilerplate): Adds custom command for reactotron to show the react native dev menu.

---

boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx

- Fixes an intermittent issue the community seems to be having
- Guessing this was masked by the platform check that existed before after this PR https://github.com/infinitered/ignite/pull/2536
- https://infiniteredcommunity.slack.com/archives/C41PK1LAY/p1699625840543869?thread_ts=1699623588.470859&cid=C41PK1LAY
- https://infiniteredcommunity.slack.com/archives/C41PK1LAY/p1699653774616489?thread_ts=1699653727.620679&cid=C41PK1LAY

fix(boilerplate): check params undef

---

src/commands/new.ts

- Closes #2551
- Not every dev machine on Windows has the `unix2dos` utility installed via `git` apparently, so we changed it up to just change line endings more manually
- Also added a try/catch around this region specifically, since it doesn't need to kill the entire `new` command

fix(cli): windows EOL

---

src/commands/new.ts

- Closes #2558 
- Allows spaces to be in the target path of the project on `new pizza-app`

fix(cli): remove demo when spaces in path

---

boilerplate/app/navigators/DemoNavigator.tsx

Tabbar layout aligned, issue mentioned in #2552

fix (boilerplate): web layout tab bar alignment

---

docs/cli/Upgrading-Ignite.md

docs(cli): upgrading ignite added

---

docs/concept/Error-Boundary.md

- Fix error boundary source links
- yolo

docs(error-boundary): link directly to source files

---

README.md
docs/README.md

- Add link to @jamonholmgren's code quest video

docs: added video by @jamonholmgren from code quest

---

boilerplate/app/screens/ErrorScreen/ErrorBoundary.tsx

Correcting a small link that points to a non-existent URL

docs(error-boundary): fixing concept link from component

---

boilerplate/app/i18n/i18n.ts
boilerplate/test/setup.ts

Fallback Locale

---

boilerplate/app/i18n/i18n.ts

Context: https://infiniteredcommunity.slack.com/archives/C41PK1LAY/p1706234516339489
https://infiniteredcommunity.slack.com/archives/C41PK1LAY/p1706940969197049
Resolves #2613

fix(localization): fix default locale issue for non en-US 

---

src/commands/generate.ts
src/commands/generate/splash-screen.ts
src/commands/help.ts
src/commands/ignite.ts
src/tools/generators.ts

To be more consistent with our docs!

docs: use 'npx ignite-cli' in help text instead of 'ignite'

---

.github/PULL_REQUEST_TEMPLATE.md

Adds linter and prettier format checks to the list of tasks the user should do.

chore(github): Update PULL_REQUEST_TEMPLATE

---

.circleci/config.yml

Simple CI version bump for `bun`

chore(ci): Upgrade bun version on on CI

---

docs/README.md
docs/boilerplate/app/app.md

chore(docs): fix broken links from new boilerplate/ directories

---

docs/boilerplate/app.json.md
docs/boilerplate/assets.md

followup of #2634 - fixing a couple broken links

chore(docs): broken links on new docs

---

docs/concept/Concepts.md

edit grammar mistake on Concepts file

edit grammar mistake on Concepts file

---

README.md

^^ i dont believe these are necessary since this PR only adds a line to the readme
One of the common points of confusion for beginners to Ignite is the use of [MobX-State-Tree](https://mobx-state-tree.js.org/intro/welcome).  @jamonholmgren's intro on the topic was helpful to me when getting started so this PR aims to increase its visibility by adding it to the Intro Videos section of the readme.

Add MST intro video to Readme Intro links

---

boilerplate/app/components/Screen.tsx

fix(boilerplate): doc url

---

boilerplate/app/devtools/ReactotronConfig.ts
boilerplate/app/utils/storage/storage.test.ts
boilerplate/app/utils/storage/storage.ts
boilerplate/package.json
boilerplate/test/setup.ts
src/commands/new.ts

- Closes #2639, #2657
- Removes `@react-native-async-storage/async-storage`
- Adds `react-native-mmkv`
- Adds `reactotron-react-native-mmkv` dev plugin

feat: add MMKV for v10

---

boilerplate/app/services/api/api.ts

docs(api): fix backend integration link

---

docs/README.md

- [N/A] `yarn test` **jest** tests pass with new tests, if relevant
- [N/A] `yarn lint` **eslint** checks pass with new code, if relevant
- [N/A] `yarn format:check` **prettier** checks pass with new code, if relevant
Fixes typo in the docs.

Fixes typo

---

boilerplate/app/utils/useSafeAreaInsetsStyle.ts

Only updating the broken link for useSafeAreaInsetsStyle into "see" property

docs: update link to useSafeAreaInsetsStyle docs

---

boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
boilerplate/app/screens/DemoShowroomScreen/DrawerIconButton.tsx
boilerplate/patches/react-native-drawer-layout+4.0.0-alpha.9.patch

- [✅] `yarn test` **jest** tests pass with new tests, if relevant
- [✅] `yarn lint` **eslint** checks pass with new code, if relevant
- [✅] `yarn format:check` **prettier** checks pass with new code, if relevant
- [N/A] `README.md` (or relevant documentation) has been updated with your changes
- Fixes drawer button and contents layout
https://github.com/infinitered/ignite/assets/8325407/6a2cd791-03bd-4c79-9ad1-a920ec1017bb

Fix drawer

---

README.md
docs/README.md

- Updates the docs with Robin's CR 2024 talk link to the YouTube recording

docs: add Robin's CR 2024 talk link

---

boilerplate/app/i18n/i18n.ts
boilerplate/app/i18n/translate.ts
boilerplate/app/utils/formatDate.ts
boilerplate/package.json
boilerplate/test/__mocks__/i18n-js.ts
boilerplate/test/setup.ts
docs/boilerplate/app/i18n/Internationalization.md

- Closes #2705
- Follows migration notes from https://github.com/fnando/i18n/discussions/24

fix(boilerplate): upgrade i18n-js

---

boilerplate/app/components/ListView.tsx

Via https://twitter.com/IndicGames/status/1825949273147716072
Whoopsies 😅

chore(docs): Punjabi is not RTL 😅

---

boilerplate/app/components/Button.tsx

Comment linked to broken documentation link. Fixed it

Fixed documentation link

---

boilerplate/app/components/Text.test.tsx
boilerplate/app/i18n/demo-hi.ts
boilerplate/app/i18n/demo-ja.ts
boilerplate/app/i18n/hi.ts
boilerplate/app/i18n/i18n.ts
boilerplate/app/i18n/ja.ts
docs/boilerplate/app/i18n/Internationalization.md
package.json
src/tools/demo.ts
test/vanilla/__snapshots__/ignite-remove-demo.test.ts.snap
test/vanilla/ignite-new.test.ts

Making a PR for this to make sure CI passes before merging.

Merge master->v10

---

boilerplate/package.json
package.json

Master->v10 merge-up

---

docs/contributing/Contributing-To-Ignite.md

Updating docs to explain expectations for merging PRs.

Explain more about merge strategy for maintainers

---

docs/contributing/Contributing-To-Ignite.md

Putting new recommendations into practice with the smallest mergeup ever :)

master->v10 mergeup

---

docs/Guide.md

Updates the Guide documentation to reflect some of the changes in v10

docs: guide updates for v10

---

README.md

| [Insert before screenshot/video] | [Insert after screenshot/video] |

asyncstorage -> mmkv in readme tech stack

---

docs/boilerplate/app/theme/Theming.md

I was going through the docs and saw some typos, hope this PR helps making ignite even better!

docs: fix typos in the Theming docs

---

boilerplate/package.json
docs/boilerplate/App.tsx.md
docs/boilerplate/Boilerplate.md
docs/boilerplate/app/components/TextField.md
docs/boilerplate/app/models/Models.md
docs/boilerplate/app/navigators/Navigation.md
docs/boilerplate/app/theme/Theming.md
docs/boilerplate/app/theme/typography.ts.md
docs/boilerplate/app/utils/useAppTheme.tsx.md
docs/boilerplate/plugins/Plugins.md
src/commands/new.ts

Small typo fixes and a couple additions to existing pages that needed a little more info.

fix: spelling and small doc updates

---

src/commands/new.ts

Commit 26614c54bb1ba865119c0516ac314a5603f9715c moved the `Generators.md` file to `concept` directory. This PR adjusts sources to changes.
| [Insert before screenshot/video] | [Insert after screenshot/video] |

fix: update `Generators` reference

---

package.json
yarn.lock

- Currently, our generator templates have a multiline string on one line with `\n` and `\t` and so on, which makes it hard to read / debug. An example of this can be found in the [Screen generator template](https://github.com/infinitered/ignite/blob/master/boilerplate/ignite/templates/screen/NAMEScreen.tsx.ejs#L12)
`  insert: "<Stack.Screen name=\"<%= props.pascalCaseName %>\" component={Screens.<%= props.pascalCaseName %>Screen} />\n\t\t\t{/* IGNITE_GENERATOR_ANCHOR_APP_STACK_SCREENS */}"
`
- This upgrades the `yaml` package which was 2+ years behind the latest, which helps support multiline strings better
- So for example, this frontmatter is now valid:
```yml
---
patches:
- path: "app/_layout.tsx"
replace: "{/* APP_LAYOUT_ANCHOR */}"
insert: |
<Stack.Screen
name="<%= …
```

fix(cli): upgrade yaml pkg to support multi line strings properly

---

README.md

- There was some confusion in the Community slack about when Ignite would support react-native 0.76 due to some users just looking at the README
- Maybe we consider removing this and just replace it with "curious with what's inside?" and link to the `boilerplate\package.json`

docs: update rn, expo versions in table

---

boilerplate/test/mockFile.ts

Update mock file URL since the old one is deactivated.

Update mock file URL

---

README.md
docs/README.md

Fixes docusauras compile issues in ir-docs. This is a follow-up to #2944 
When running our `ir-docs` repo with the local instance of ignite symlinked:
| ![Screenshot 2025-05-12 at 12 51 18 PM](https://github.com/user-attachments/assets/5791bca8-16d8-4c79-ab65-c64032751608) | ![Screenshot 2025-05-12 at 12 51 44 PM](https://github.com/user-attachments/assets/3627a594-6c8b-49d3-a738-cda6869028f2) |

chore(docs): update links in docs folder and fix syntax issues with img
