infinitered/ignite

- .babelrc
- Tests/Compiler.js
- package.json
This fixes up the strangeness with the missing 'requires' stuff.
Basically 2 changes.
1.  Get rid of the custom .babelrc.  Everything we need is in the default one.
2.  Since Compiler.js uses its own built-in babelrc, we make sure we use the right preset and include babel-polyfill for generator support. (sigh)
Make sure you `rm -rf node_modules` and `npm i` to ensure everything is sane.
> Straightening out the babel environment mess.

- App/Reducers/CreateReducer.js
- App/Sagas/StartupSaga.js
- App/Store/ImmutablePersistenceTransform.js
- App/Store/Store.js
This:
* promotes the seamless-immutable conversion to its own transform file.
* silences extra chatter in the logger caused by redux-persist
* only triggers the weather check on startup if we don't have one yet
> Separates redux-persist state transformations to its own file.

- App/Navigation/NavigationBar.js
Navigation title can be centered by styles but I think it would be nice if it's default on Android.
> Add navigationStyle

- ignite-base/App/Containers/AllComponentsScreen.js
- ignite-base/App/Root.js
- ignite-base/android/app/build.gradle
- ignite-base/android/app/src/main/AndroidManifest.xml
- ignite-base/android/app/src/main/java/com/rnbase/MainActivity.java
- ignite-base/android/settings.gradle
- ignite-base/ios/RNBase.xcodeproj/project.pbxproj
- ignite-base/ios/RNBase/AppDelegate.m
- ignite-base/package.json
- ignite-base/package.json.template
This PR adds the `react-native-push-notification` project and configures the android and ios builds for push notifications. It also adds a generic configuration to `Root.js` and has an example that requests permissions after the user has logged in on the all components screen.
> Push Notifications

- ignite-base/App/Root.js
I actually don't know anything about this push notification component.
Seems like at startup, it's triggering a request to display a push notification.  This phantom notification is causing itself to trip up.
Setting this value to false seems to dodge that issue, but our app now runs.
> Turns off a mystery PN setting which was breaking fresh apps.

- fireDrill.sh
- ignite-generator/src/validation.js
This is my solution for https://github.com/infinitered/ignite/issues/37
Now when you modify the templates/structure you can modify the tester in the same PR, instead of modifying semaphore. 
Additionally, I've riddled it with comments so people can see WHY we're checking things in the current stage of the project life.   Besides failing, the script will output friendly error messages to help identify why the checks did not pass.
I've also take the liberty of enforcing standard compliance on the CLI and the Generator code bases, and even caught one linting error in the process.
> [ALL] Check script

- ignite-base/package.json
- ignite-base/package.json.template
Guess I should explain.
Adds 3 things.
`npm run android:devices` - gets a list of attached devices
`npm run android:logcat` - captures the output of device logging using android's logcat utility.
`npm run android:shake` - shakes the hell out of every attached device & emulator to bring up the dev menu.
> Adds some npm scripts to help out with android dev lyfe!

- ignite-generator/package.json
Was just missing the `validation.js` from the generator's `package.json` `files` node.
Fixes #75 
Fixes #71
> Adds the missing validation.js to the packing list.

- ignite-base/App/Root.js
YellowBox was not obeying the boolean in DebugSettings - fixed
> - [Base] - Make yellowbox obey DebugSettings boolean

- ignite-base/fastlane/Appfile
- ignite-base/fastlane/Fastfile
- ignite-base/package.json
--
Don't know if you're interested, let me know.  
P.S.:  Interesting threads to keep an eye on:  
[Increment build and version numbers for Android apps using Gradle](https://github.com/fastlane/fastlane/issues/878)    
[Gradle upgrades](https://github.com/fastlane/fastlane/pull/1082)
> [Base] - Adding Android to FastLane

- ignite-generator/container/templates/container.js.template
- ignite-generator/screen/templates/screen.js.template
> [Generator] - properly import proptypes - closes #113

- ignite-generator/component/index.js
- ignite-generator/container/index.js
- ignite-generator/screen/index.js
- ignite-generator/src/component/index.es
- ignite-generator/src/container/index.es
- ignite-generator/src/screen/index.es
Wouldn't mind your opinion on this @GantMan .
My vote is to remove the verification check for the generators that aren't 'app'.
Once your project has gotten started, I think it's safe to assume that `react-native` is installed.
There are other checks I'd like to perform though.  (like verifying the proper directory)
> [Generator] - Fixes the generators by removing the verify check

- ignite-cli/package.json
- ignite-cli/src/index.es
Apparently we want to spawn instead of exec.  Something about keeping the TTY and environment variables?  Oh Unix.  You so crazy.
> [CLI] Keeps the colours when running through the CLI.

- ignite-base/App/Root.js
- [Base] - Fixed bug in Drawer Styles
- [x ] Works on iOS/Android/XDE
- [ x] Tests Pass (run: `npm run test`)
- [ x] Code is StandardJS compliant (run: `npm run lint`)
'react-native-drawer' calls it style property style**s**.
(see: https://github.com/root-two/react-native-drawer)
> Updated react-native-drawer styles property

- ignite-base/App/Config/DebugSettings.js
- ignite-base/App/Config/ReduxPersist.js
- ignite-base/App/Services/RehydrationServices.js
- ignite-base/App/Store/Store.js
Crashes and bugs can be caused when the app rehydrates the store after a reducer shape has changed.
The app has no way to know that the reducer shape has changed since the rehydrate feature will  resurrect the outdated reducers...until now...
* Here we move `reduxPersist` from `DebugSettings.js` to its own file (`ReduxPersist.js`) with its own set of properties.
* Additionally we will configure the store in `ReduxPersist.js` as well and make it a part of ReduxPersist since this store is what we are creating/persisting and it can be accessed by `RehydrationServices.js`
* Finally we will add a `reducerVersion` in `ReduxPersist.js` to track changes in reducer shape and notify `RehydrationServices` that a change has occurred. 
* When the app is loaded, it will check for an update with …
> - [Base] - Adding Rehydration guard

- ignite-base/App/Containers/LoginScreen.js
- ignite-base/App/Containers/Styles/LoginScreenStyle.js
I used the built-in LoginScreen for my project but my logo was a bit larger that the default logo. This pushed the buttons further down the screen so that they were unreachable without scroll.
> - [Base] - Add ScrollView as parent to LoginScreen

- ignite-base/App/Containers/APITestingScreen.js
- ignite-base/App/Containers/AllComponentsScreen.js
- ignite-base/App/Containers/DeviceInfoScreen.js
- ignite-base/App/Containers/PresentationScreen.js
- ignite-base/App/Containers/ThemeScreen.js
- ignite-base/App/Containers/UsageExamplesScreen.js
- ignite-base/App/Themes/ApplicationStyles.js
Fixes  #160 
* Best practice tip: Don't use `<Image>` as a parent container. Always use a`<View>` or `<ScrollVIew>`
* But in our case we wanted an image as a fixed background so we needed to wrap the `ScrollView` in a `View` and `position: 'absolute'` the `Image` between the views with `top, left, right, bottom` set to `0`
_(See changed code for more detail)_
> - [Base] - Device orientation fix

- ignite-cli/src/index.es
- ignite-generator/src/app/index.es
`ignite n NinetyNineCentApp --repo https://github.com/skellock/ignite.git --branch ignite-dev`
You'd really only need this if you're developing features within ignite and want to dry run your new generator end-to-end.
> Adds optional --branch & --repo flags to CLI & Generator.

- ignite-base/App/Components/DrawerButton.js
- ignite-base/App/Components/DrawerContent.js
- ignite-base/App/Components/Styles/DrawerButtonStyles.js
- ignite-base/App/Components/Styles/DrawerContentStyle.js
- ignite-base/App/Containers/Styles/DeviceInfoScreenStyle.js
- ignite-base/App/Containers/Styles/RootStyle.js
- ignite-base/App/Root.js
- ignite-base/App/Themes/Colors.js
- ignite-base/App/Themes/Metrics.js
* First step in establishing a general best practice for a Menu Drawer that is responsible for ancillary navigation
Typically a Menu Drawer can be responsible for navigating to screens when deep into the navigation stack from the "Home Screen." Here we've set up a lean component that's business logic is handled at the highest level (`Root`) that is on par with the navigator - where it should be IMO. This allows the Drawer Content Component to be a "dumb" stand-alone component that functions without any knowledge of state, `navigator`, and `dispatch`. 
**This upgrade method eliminates the pesky issue of passing around `navigator` and `dispatch` to the Menu Drawer, which are necessary when dealing with navigation, as well as consequential async problems that arise from `navigator` handling …
> - [Base] - Upgrade Left drawer

- ignite-base/README.md
the current link seems to be pointing to some older repo structure
> [Base] Changed I18n.js link in README.md

- ignite-base/App/Containers/AllComponentsScreen.js
- ignite-base/App/Containers/PresentationScreen.js
- ignite-base/App/Containers/UsageExamplesScreen.js
- ignite-generator/container/templates/container.js.template
- ignite-generator/screen/templates/screen.js.template
Solves two issues filed by @ahmed1490 
closes #207 and #208
> Fix small issues bundle

- ignite-base/App/Services/Api.js
- ignite-base/package.json
- ignite-base/package.json.template
Now with apisauce 0.2.0, axios 0.12 and react-native 0.25+, we have the ability to detect timeouts and network errors.  Hooray!
> Updates apisauce to use network error & timeout detection.

- ignite-generator/src/app/index.es
- Locks the react-native version used to init the base template to 0.28.0. Since the base directory assumes 0.28, I felt hard-coding the current version was appropriate.
> Quick fix for issue #233. Lock the current react-native version to 0.28

- ignite-generator/src/app/index.es
- ignite-generator/src/utilities.js
The react-native-cli version check would always fail for a few different reasons:
* `Shell.exec` returns the exit code in an object, not as the return value itself
* The grep regex needed to be escaped, otherwise javascript throws in control characters
* The silent option needed to be set so we don't get the version string dumped into the console
Also when some checks did fail, the error message would be displayed in a run-on line instead of its own.
This PR should resolve both these things and avoid more issues like #241
> Fix the react-native-cli version check

- ignite-base/ios/RNBase.xcodeproj/project.pbxproj
I tried running ignite-base on iOS but it was failing because of missing `libAirMaps.a`. I think those links are forgotten in Xcode project after removing `react-native-maps` dependency from `package.json`.
> Fixing iOS build by removing react-native-maps links from xcode project file

- ignite-generator/src/app/index.es
machines without grep cannot use Ignite, this fixes that.  Ticket #263
> warning if no grep command

- ignite-cli/src/index.es
The `ignite doctor` was bombing when trying to load RN's package.json.  
Turns out, the `cwd` and the `require` root can be two different things.
My bad.
> [CLI] Fixes the RN dependency version check.

- ignite-base/App/Config/ReduxPersist.js
- ignite-base/App/Reducers/index.js
Redux-persist has built-in whitelist support, but we weren't exposing it.
> baked-in support for redux persist whitelist

- ignite-cli/package.json
- ignite-cli/src/index.es
Reasoning: When I tell someone to update their ignite, this is what they usually type.  This is now a command.  `ignite update`
> [CLI] - Feature/add update

- ignite-base/App/Navigation/NavItems.js
Make the hamburger just open the menu. Currently it's giving a function to `open` which it doesn't understand and just interpret as *truthy* anyway.
- Fixes propType validation error (`open` can't have value `function`)
- It is not possible to invoke the `onPress` of `hamburgerButton` while the menu is showing, so just having it open the menu seems sensible (in any case it's the same behaviour as currently)
> Change toggle drawer to open drawer.

- ignite-base/App/Components/AlertMessageComponent.js
- ignite-base/App/Components/FullButton.js
- ignite-base/App/Components/MapCallout.js
- ignite-base/App/Components/ProgressiveImage.js
- ignite-base/App/Components/RoundedButton.js
- ignite-base/App/Containers/AllComponentsScreen.js
- ignite-base/App/Containers/DeviceInfoScreen.js
- ignite-base/App/Containers/PresentationScreen.js
- ignite-base/App/Containers/ThemeScreen.js
- ignite-base/App/Containers/UsageExamplesScreen.js
- ignite-base/App/Navigation/NavigationDrawer.js
- ignite-base/App/Root.js
- ignite-base/package.json
- ignite-base/package.json.template
- ignite-generator/Generator.js
- ignite-generator/component/templates/component.js.template
- ignite-generator/mapview/templates/mapcallout.js.template
To format the code correctly according to standardjs, one can use the `standard --fix file` CLI. But the quirk there is that it doesn't like the `static propTypes = {` line within the class. So instead, using `ClassName.propTypes = {` will allow the CLI to work properly. 
I personally also thinks it makes the code cleaner to seperate out the propType from the class. 
ps: If you look at Generator.js in this PR, you can see `standard --fix` at work.
ps: I have `standard --fix` running each time I save js files on my editor, that's why I know it wasn't working.
> standard --fix to fix code according to standardjs

- ignite-base/App/Config/ReactotronConfig.js
- ignite-base/App/Containers/DeviceInfoScreen.js
- ignite-base/App/Services/Api.js
- ignite-base/App/Store/Store.js
- ignite-base/Tests/Setup.js
- ignite-base/index.android.js
- ignite-base/index.ios.js
- ignite-base/index.js.template
- ignite-base/package.json
- ignite-base/package.json.template
Heads up, there's a warning about peer dependency of React Native with `reactotron-react-native`.  I'm going to loosen up the requirement on my end from `^0.31.0` to `>=0.31.0`.  
But it's harmless.  You're welcome to hold off on this merge, but it might not be for a few days before I can get to that task.
https://github.com/reactotron/reactotron/issues/186
> Updates Reactotron to 1.1.0 and adds some in-app samples.

- ignite-base/index.js
We stopped updating the index.js for exponent builds.  Might as well officially remove it.
> we're not really supporting exponent anymore

- ignite-base/android/app/build.gradle
- ignite-base/android/app/src/main/java/com/rnbase/MainApplication.java
- ignite-base/package.json
- ignite-base/package.json.template
Finishes hooking up `react-native-config` to Android and temporarily switch to a branch which doesn't die when building projects missing an `.env` file.
https://github.com/luggit/react-native-config/pull/31
> Fixes problem with chicken-and-env for react-native-config.

- ignite-base/package.json
- ignite-base/package.json.template
Switched Reactotron's React Native dependency from `~0.31.0` to `>=0.31.0` because it was throwing warnings.  Sorry about that.
> Bumps Reactotron due to version warning inside that dependency.

- ignite-base/App/Services/RehydrationServices.js
Refactored `RehydrationServices.js` so that store gets purged on `reducerVersion` change in `ReduxPersist.js`
Cool Reactotron logging
> Rehydration services repair

- ignite-cli/src/index.es
Added an early exit with a nice message when the project folder already exists in the target directory.
Since there were no tests (understandably) I've done some manual before and after testing below to verify results:
If there's anything that needs changing, let me know. (I'm a first time node-r but long time code-r)
And thanks for a great starter package! 😄
> Early exit (with a nice message!) when project folder exists.

- testRelease.sh
testRelease didn't fail on bad Android builds because bad android builds would not return a non-zero.  This is detected now via `grep`
Additionally, a failing `test_command` could have been overwritten before, this is now fixed.  1 failure of `test_command` will result in the final report.
> testRelease catches failing Android builds

- ignite-generator/src/app/index.es
As of #361 we started getting a strange error on Android.  As reported here in #362 
This PR now automatically does some buttwiping for React Native Android so the dex files don't complain.  Not sure if this symptom should be be further investigated, but this fixes it for now.   Someone like @darinwilson  or @skellock might know why this was needed?
If not, the screw it, this PR does all the fixing necessary.
> gradlew clean android now

- ignite-cli/src/index.es
* Early exit when generators are not being run in an ignite directory
* Also added an early exit if the new command is being run in an ignite directory.
Verification Tests:
Let me know if there's anything else :)
> Added early exit if generators are being run in an ignite directory.

- ignite-base/App/Containers/RootContainer.js
- ignite-base/App/Services/RehydrationServices.js
Fix [340](https://github.com/infinitered/ignite/issues/340)
Check if redux persist is not active and then fire startup action.
Else... The rehydration service will fire the startup action after complete.
> Fix Startup before rehydration

- ignite-base/package.json
- ignite-base/package.json.template
Currently the HTML coverage reports don't open on Linux because there is no `open` executable. This PR fixes that by falling back to use `xdg-open` if the `open` command fails.
> fix html coverage report opening on Linux

- testRelease.sh
This PR adds a method to ./testRelease.sh which will run the component, container and screen generators and ensure that the files were generated to the appropriate directory. It doesn't check the content of the files that were generated though! 😄 
Also regarding `mapview` and `listview` : ⏬ 
---
> Add generator file creation tests to ./testRelease.sh

- ignite-base/App/Components/MapCallout.js
Fixes warning in simulator for "child keys must be unique".
> Fix warning of duplicate key for MapCallout

- ignite-base/App/Containers/LoginScreen.js
@GantMan Seems like this should be there by default.
> Disable autocorrect and autocapitalize for login screen text inputs

- ignite-generator/src/app/index.es
Check if yarn is installed and use it instead of npm to install packages
in ignite-generator.
Only checked the iOS app and everything works.
```
standard: Use JavaScript Standard Style (http://standardjs.com)
/.../ignite/ignite-cli/src/index.es:39:32: Unnecessary escape character: \'.
/.../ignite/ignite-cli/src/index.es:44:32: Unnecessary escape character: \'.
/.../ignite/ignite-cli/src/index.es:44:60: Unnecessary escape character: \'.
/.../ignite/ignite-cli/src/index.es:52:32: Unnecessary escape character: \'.
/.../ignite/ignite-cli/src/index.es:52:71: Unnecessary escape character: \'.
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
/.../ignite/ignite-generator/src/utilities.js:14:1: More than 1 blank line …
```
> feat: Add yarn to install packages

- ignite-generator/src/app/index.es
Addresses #401. Uses `--depth 1` and specifies requested branch when cloning Ignite.
The branch is printed in the step description:
```
$ ignite new test --branch 1.9.1
🔥 Setting test on FIRE! 🔥
... snip ...
✔︎ Running React Native setup version 0.35.0 (~ 2 minutes-ish)
✔︎ Downloading latest Ignite files from https://github.com/infinitered/ignite.git#1.9.1
```
One functional change is that previously if an invalid branch name was specified, the clone would succeed, the checkout would fail, and `ignite new` would continue using either master or the latest tag. Now, however, the clone will fail and `ignite new` will bail out:
```
$ ignite new test --branch foobar
🔥 Setting test on FIRE! 🔥
... snip ...
✔︎ Getting ready for guests
✔︎ Running React Native setup version 0.35.0 (~ 2 minutes-ish) …
```
> Use shallow clone when downloading latest Ignite [Fixes #401]

- ignite-generator/.gitignore
- ignite-generator/package.json
- ignite-generator/redux/templates/redux.ava.template
- ignite-generator/redux/templates/redux.jest.template
- ignite-generator/redux/templates/redux.js.template
- ignite-generator/saga/templates/saga.ava.template
- ignite-generator/saga/templates/saga.jest.template
- ignite-generator/saga/templates/saga.js.template
- ignite-generator/src/redux/index.es
- ignite-generator/src/saga/index.es
- ignite-generator/src/utilities.js
Way back in #367 I got the idea I should refactor to reduce the code repetition we were doing when copying the template files. 💥  - that's included in 67cce4a. You can now define a config object in the class constructor which contains parameters for the files to be copied. It looks a little bit like:
```
this.fileConfig = {
templatePath: 'component.js.template',
destinationPath: 'Components',
style: true,
test: true }
} 
```
This config object will cause:
- the app template to be copied to `./App/Components/`
- the style template to be copied to `./App/Components/Styles`
- a test to be generated to:
- `./Tests/Components/` if the `.ignite` file specifies `ava`
-  `./__tests__/Components/` if the `.ignite` file specifies `jest` (so forward looking 🚀  )
Both style and test parameters are …
> Moar Generators!

- ignite-base/App/Config/ReactotronConfig.js
- ignite-base/App/Redux/CreateStore.js
- ignite-base/package.json
- ignite-base/package.json.template
- ignite-base/yarn.lock
Highlights:
* brings us up to 1.3.x of Reactotron
* we can now use snapshots
* moves redux integration out of `CreateStore.js` and into `ReactotronConfig.js` where it belongs
* simplifies redux integration by calling `Reactotron.createStore()` in dev mode
* clears Reactotron on each app startup
> Updates Reactotron to 1.3.x and simplifies the configuration. 💃

- README.md
When trying to install the cli for the first time on mac os using the new Facebook backed Yarn packaging system, a non-obvious issue occurs where a binary application is not available in your path despite you following the detailed and correct install notes.
This PR updates the documentation to cover a bug in how yarn install notes explain how to set your path and how globally installed binaries are added to a system. Hopefully in the future the getting started notes will explain that if you install binaries globally on a system you need to add that global path to your environment path.
This should be reviewed in the future to check if required given Yarn's fast development.
This PR fixes #477 
Anyone but @dhilton
> Updated docs to add yarn install note

- ignite-base/App/Containers/ThemeScreen.js
I couldn't get fireDrill.sh to run at first, confusing error: `Wrong version of Flow. The config specifies version ^0.33.0 but this is version 0.34.0`. I added flow-bin@0.33.0 in fireDrill.sh and it worked
Very small change, the name of the class in `ThemeScreen.js` class was 'UsageExamplesScreen'
Loving Ignite so far, thanks!
> fix ThemeScreen name

- ignite-base/App/Config/ReactotronConfig.js
- ignite-base/App/Redux/CreateStore.js
- ignite-base/App/Sagas/StartupSagas.js
- ignite-base/App/Services/Api.js
- ignite-base/package.json
- ignite-base/package.json.template
- ignite-base/yarn.lock
For people with existing Ignited apps:
* upgrade existing reactotron dependencies in your `package.json` to `1.5.2`
* `npm i --save-dev reactotron-redux-saga`
* register `reactotron-redux-saga` plugin within `ReactotronConfig.js`
* configure `createSagaMiddleware()` to use a custom `sagaMonitor` in your `CreateStore.js`
And now you get this:
You can download the Reactotron app with Homebrew on macOS:
```sh
brew update && brew cask install reactotron
```
To upgrade from an old version:
```sh
brew update && brew cask upgrade reactotron
```
To just [download the binaries like a savage](https://github.com/reactotron/reactotron/releases/tag/v1.5.0).
> Reactotron 1.5 - Sagas, Timeline Filter + More 💃

- ignite-generator/src/app/index.es
Still need to verify that this works @GantMan. Can't remember how to test the generators locally.
> Remove generated jest tests for now. Fixes #484

- ignite-base/App/Containers/ListviewExample.js
- ignite-base/App/Containers/ListviewGridExample.js
- ignite-base/App/Containers/ListviewSearchingExample.js
- ignite-base/App/Containers/ListviewSectionsExample.js
- ignite-generator/listview/templates/listview-sections.js.template
- ignite-generator/listview/templates/listview.js.template
- ignite-generator/src/app/index.es
- ignite-generator/src/listview/index.es
- ignite-generator/src/mapview/index.es
Fixes #509 
I only have removed underscore prefixing for React components and its generators (templates). Let me know if I missed any.
> Remove underscore prefixing for “private” methods in React components

- ignite-base/App/Config/DebugSettings.js
- ignite-base/App/Config/ReactotronConfig.js
- ignite-base/App/Redux/CreateStore.js
While Reactotron is very helpful, it often affects the performance of the app in DEV mode to a point where it gets frustrating (mainly on navigation animations).
These changes allows to quickly disable Reactotron in DEV mode by just editting `DebugSettings.js` in the same fashion that we can disable Redux logging.
> Move Reactotron switch to DebugSettings.js

- ignite-base/Tests/Sagas/TemperatureSagaTest.js
> Improve TemperatureSagaTest

- .gitignore
- ignite-base/Tests/Sagas/TemperatureSagaTest.js
- ignite-base/Tests/Setup.js
Updates Setup for Ava tests to add support for I18n interpolated strings
> Add I18N support for Ava tests

- ignite-base/package.json
- ignite-base/package.json.template
- [ x] Everything works on iOS/Android
Git commits would fail with no standard command as it wasn't getting installed on project init.
> Missing dev dependency on 'standard' command

- ignite-base/App/Redux/OpenScreenRedux.js
- ignite-base/App/Sagas/OpenScreenSagas.js
- ignite-base/App/Sagas/index.js
- ignite-base/Tests/Sagas/OpenScreenSagaTest.js
- ignite-base/Tests/Setup.js
This adds an action ('OPEN_SCREEN') & saga to enable users to dispatch a command to open any screen. 
For Reactotron users, when generating a new app via Ignite, users can retain the useful screens generated by ignite-base, such as 'componentExamples', even if their new app bypasses any Ignite-generated screens on startup, simply by dispatching to Reactotron, like this:
```{type: 'OPEN_SCREEN', screen: 'componentExamples'}```
In addition, 'OPEN_SCREEN' is helpful while developing screens for an app that have not been set up with any nav links in the app. The developer can work on the new screen and test it via a direct dispatch from Reactotron.
The saga sets the react-native-router-flux option param to type: ActionConst.RESET by default, but users can easily override this by passing in …
> Add OPEN_SCREEN action and saga

- ignite-generator/redux/templates/redux.js.template
The documentation for reduxsauce states that it converts the key names into
"SCREAMING_SNAKE_CASE".  The existing code didn't account for file names
with more than one word or upper case letter.  For instance, the command: ignite g redux
"CorrectHorseBatteryStaple" would have resulted in template naming the
request key "CORRECTHORSEBATTERYSTAPLE_REQUEST".  My fix splits the string
at the uppercase letters, using regex, and joins the resulting array using
"_" as the delimiter.  In the above use case the resulting request key
would now be "CORRECT_HORSE_BATTERY_STAPLE_REQUEST".
Signed-off-by: Keith Center <keith.center@excella.com>
> Bug fix: redux template

- packages/ignite/package.json
- packages/ignite/src/cli/cli.js
This will help debug issues loading plugins, commands, and extensions.
```
❯ bin/ignite --wtf
---------------------------------------------------------------
plugin generate
src/cli/../plugins/generate
command container -- Problem parsing file
Generates a redux smart component.
src/cli/../plugins/generate/commands/container.js
{ Error: Cannot find module '../shared/generate-utils'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at require (internal/module.js:20:19)
at Object.<anonymous> (/Users/steve/src/ir/ignite/packages/ignite/src/plugins/generate/commands/container.js:3:18)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at …
```
> Adds a script debugging command.

- packages/ignite/package.json
This gets us the fixed default plugin and a better printCommands.
> Upgrades to gluegun 0.5.0.

- packages/ignite-empty-playground/devignite
- packages/readme.md
For developer convience, made a copy of the ignite script in the ignite-empty-playground folder. For now I've left the old script where it was so people who are already used to using it from there can continue to do so.
> make copy of devignite script in empty-playground and update readme

- ignite-base/App/Navigation/Styles/NavigationDrawerStyle.js
- [x ] Everything works on iOS/Android
- [ x] `fireDrill.sh` passed
Fixes a flash of pink in a screen from an Ignited project when the project uses the default NavigationRouter (with the drawer!) by setting the backgroundColor of main in NavigationDrawerStyle.js from Color.ember to Color.clear. Word on the street is that this has been an issue for other ignited projects, and this proposed fix should solve it. It fixed the pink flash issue for my current ignited project
Note: fireDrill.sh passed, unit tests pass, lint passes, tested in iOS and it passes, but could not test in Android.
> fix flash of pink when opening screen

- packages/ignite/package.json
- packages/ignite/src/cli/cli.js
All plugins living in `node_modules/ignite-*` will now be hidden from the command line.
> Hides user-defined plugins from the CLI.

- ignite-generator/redux/templates/redux.js.template
This is a fix for #578.
The redux generator now will uppercase the `createReducer()` keys.
> Ensures uppercase when creating reducers with the redux generator.

- packages/ignite-empty-playground/ignite.toml
- packages/ignite-empty-playground/package.json
- packages/ignite-vector-icons/index.js
- packages/ignite-vector-icons/templates/vectorExample.js.ejs
- packages/ignite/src/plugins/default/commands/add.js
- packages/ignite/src/plugins/default/extensions/ignite.js
This PR adds a round of fun to the `ignite add` command.
* Gluegun now supports configurable template directories, so here's support for that + 1 example (vector-icons). Basic structure is next, but not part of this PR because I want to do something awesome with bulk template generation in gluegun.
* Switched `Shell.exec` to `context.system.run`.
* Added a switch called `--npm` to `ignite add` because `yarn` insists on validating existing modules against npm.  Since ignite 2.0 isn't shipped, this blows up `yarn`.  But not `npm`.
* Adds better code docs inside the `ignite` gluegun plugin.
* Adds support for ignite 3rd party folk to opt-in to `react-native link` and installing modules as dev dependencies.
* Added some try/catches in order to centralize error messages.
> Adds ignite plugin path and improves ignite add support.

- packages/ignite-basic-generators/index.js
- packages/ignite-basic-generators/package.json
- packages/ignite-basic-structure/index.js
- packages/ignite-basic-structure/package.json
- packages/ignite-vector-icons/package.json
- packages/ignite/package.json
- packages/ignite/src/lib/detectedChanges.js
- packages/ignite/src/lib/exitCodes.js
- packages/ignite/src/plugins/default/commands/add.js
- packages/ignite/src/plugins/default/commands/add/detectInstall.js
- packages/ignite/src/plugins/default/extensions/ignite.js
This gives us the ability to add plugins from our file system.
First, this is working really well for me:
```sh
cd packages
export IGNITE_STUFF=$(pwd)
cd ignite
npm link
```
Create a brand new React Native project (`ignite new` will handle this in the near future)
```sh
mkdir -p ~/tmp/ignite
cd ~/tmp/ignite
react-native init Fun
cd Fun
```
Then play around!
```sh
ignite add $IGNITE_STUFF/ignite-basic-structure --unholy
ignite add $IGNITE_STUFF/ignite-basic-generators
ignite generate screen GreatOdinsBeardThisIsActuallyWorking
ignite add $IGNITE_STUFF/ignite-vector-icons
```
A few other notable changes:
* temporarily turned off `yarn` support
* mucking about with console logging
* i took out `Exists` checking as not all npm modules live on npmjs.com
Things to chat about tomorrow.
* I'd …
> Adds Ignite 2.0 Plugin Developer Quality of Life

- ignite-base/App/Config/DebugSettings.js
The ezLogin flag wasn't used anywhere, I think it was a leftover from the initial commits.
> Remove ezLoging flag

- ignite-generator/src/mapview/index.es
MapView Generator is crashing without this fix.
- [x ] Everything works on iOS/Android
- [ x] `ignite-base` **ava** tests pass
- [ x] `fireDrill.sh` passed
Fixes crashing of generator because spinner the doesn't exist.
> Fix MapView Generator Crash

- packages/ignite/src/cli/cli.js
Adds a few additional ways to ask for the version number.
```sh
ignite version
ignite --version
ignite -version
ignite -v
```
The last 3 are what this PR adds.  And they do that by manually calling the version command.  :)
Requested by https://github.com/infinitered/gluegun/issues/131.
> Adds additional ways to show the version number.

- .travis.yml
Updates the `android update sdk` command on Travis to be less brittle by referring to packages by their names, not index numbers.
If Semaphore passes, we're good to go.
> Updated auto-install packages for Travis

- packages/ignite-basic-structure/templates/Unholy/Components/SearchBar.js
- packages/ignite-basic-structure/templates/Unholy/Containers/DrawerContent.js
- packages/ignite-basic-structure/templates/Unholy/Containers/LoginScreen.js
- packages/ignite-basic-structure/templates/Unholy/Transforms/ConvertFromKelvin.js
- packages/ignite/src/plugins/default/commands/new.js
Closes #620.
- Make all prompts use `list` for consistency and ease of use.
- Make all prompts default to `none` or `no` for consistency and ease of use.
- Fixed lingering I18n references in Unholy that only appear if you chose not to install I18n.
- Fixed lingering drawer navigation items for moved dev screens.
> Next prompt

- ignite-base/package.json
- ignite-base/package.json.template
- [x ] Everything works on iOS/Android - Nothing changed in that regard
- [x ] `ignite-base` **ava** tests pass
- [x ] `fireDrill.sh` passed
Android shake command fails for me as the previous command greps "List" out of the result and adb fails with unknown device "List"
This change greps all devices out of the device List and then omits the line containing "List".
> Update android shake command to not fail

- packages/ignite/package.json
- packages/ignite/src/plugins/default/commands/add.js
- packages/ignite/src/plugins/default/commands/new.js
- packages/ignite/src/plugins/default/extensions/ignite.js
This brings us back into a good place again with 2.0.
* fixes `react-native link` does something weird which causes a hang.
* temporary comments out the directory safety checks.  will sync up with @kevinvangelder to fix 'er up.
* fixes & re-enables yarn support
Don't forget to `cd packages/ignite && yarn` to grab the latest deps.
> Fixes outstanding 2.0 project setup issues

- packages/ignite/src/plugins/default/commands/add.js
- packages/ignite/src/plugins/default/commands/add/detectInstall.js
- packages/ignite/src/plugins/default/commands/new.js
- packages/ignite/src/plugins/default/extensions/ignite.js
* Standardizes the printing to be consistent.
* Fixes another dreaded `&` call i had missed in `addModule` causing `react-native link` to sometimes hang.
* specifying `--max` when calling `ignite new` now skips the questions.
* Yarn's cache busting `--force`  is broken, so now forcing `npm` when using `ignite add`.
> Fixes more linking, yarn, and printing issues.

- packages/ignite/src/lib/exitCodes.js
- packages/ignite/src/plugins/default/commands/new.js
Bumps our default to React Native 0.41.1.
Also this is a thing now:
```sh
ignite new OldAndTired --react-native-version 0.40.0
```
This will allow us to test newer versions easier.
> React Native 0.41.1 + configurable versions

- packages/ignite-basic-structure/templates/package.json.unholy.ejs
This clears the whole build folder under ios when using `newclear`.  Fixes #624.
> Clears the build folder in ios when newclearing.

- packages/ignite/package.json
- packages/ignite/src/commands/doctor.js
- packages/ignite/src/extensions/ignite.js
This started by moving `which` into gluegun.  Ended up reworking the whole command.
I think there's even more we can do as well.  Like list the current installed android sdks and more.
```
❯ ignite doctor
-----------------------------------------------
(                  )   (
)\ )   (        ( /(   )\ )    *   )
(()/(   )\ )     )\()) (()/(  ` )  /(   (
/(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
(_))    /(_))_   _((_) (_))   (_(_())  ((_)
|_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
| |     | (_ | | .` |  | |     | |    | _|
|___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------
An unfair headstart for your React Native apps.
https://infinite.red/ignite
-----------------------------------------------
System
platform           darwin
arch …
```
> Upgrades ignite doctor.

- packages/ignite-basic-structure/index.js
- packages/ignite-basic-structure/templates/package.json.unholy.ejs
- packages/ignite/src/commands/new.js
The unholy template copies it's `package.json` overtop of the one installed by React Native so we end up losing the user's choice.
This fixes that.
> Fixes unholy package.json clobbering RN version.

- packages/ignite-animatable/package.json
- packages/ignite-basic-generators/commands/component.js
- packages/ignite-basic-generators/commands/redux.js
- packages/ignite-basic-generators/commands/saga.js
- packages/ignite-basic-generators/package.json
- packages/ignite-basic-generators/shared/generate-utils.js
- packages/ignite-basic-structure/index.js
- packages/ignite-basic-structure/package.json
- packages/ignite-basic-structure/templates/ignite.json.ejs
- packages/ignite-basic-structure/templates/ignite.toml
- packages/ignite-dev-screens/index.js
- packages/ignite-dev-screens/package.json
- packages/ignite-i18n/package.json
- packages/ignite-vector-icons/package.json
- packages/ignite/package.json
- packages/ignite/src/cli/cli.js
- packages/ignite/src/commands/add.js
- packages/ignite/src/commands/generate.js
- packages/ignite/src/commands/new.js
- packages/ignite/src/commands/remove.js
- packages/ignite/src/extensions/ignite.js
Ignite's configuration (`ignite/ignite.json`) is now `json`.  
I also dropped the `ignite` key which removes 1 level.  It wasn't needed because we're not sharing this with gluegun any longer.
If you need to work with this config from a plugin:
```js
// to read
const config = context.ignite.loadIgniteConfig()
// to write
config.omg = 'yussss'
context.ignite.saveIgniteConfig(config)
```
This also changes the API a bit.  These two functions were renamed.
```js
`setGlobalConfig` -> `setIgniteConfig`
`removeGlobalConfig` -> `removeIgniteConfig`
```
I kept wonder just what config `Global` meant.  It means the Ignite config.
`setGlobalConfig` also no-longer has a 3rd parameter.  I couldn't find any examples of it in action. @kevinvangelder lemme know if that's the case.
See all those …
> Ignite app configuration is now JSON.

- ignite-generator/.gitignore
Not really changing much here (I think) but when I went to update an environment variable, I noticed that the file was tracked by git. This should keep your secrets safe and sound.
> exclude .env from generated gitignore

- ignite-base/App/Components/Styles/CustomNavBarStyle.js
- ignite-base/App/Containers/Styles/ListviewExampleStyle.js
- ignite-base/App/Containers/Styles/ListviewGridExampleStyle.js
- ignite-base/App/Containers/Styles/LoginScreenStyle.js
- ignite-base/App/Containers/Styles/RootContainerStyle.js
- ignite-base/App/Navigation/Styles/CustomNavBarStyle.js
- ignite-base/App/Navigation/Styles/NavigationContainerStyle.js
- ignite-base/App/Navigation/Styles/NavigationDrawerStyle.js
- ignite-base/App/Themes/Colors.js
- ignite-base/App/Themes/Fonts.js
- ignite-base/App/Themes/Images.js
- ignite-generator/container/templates/container-style.js.template
- ignite-generator/listview/templates/gridlistview-style.js.template
- ignite-generator/listview/templates/listview-style.js.template
This PR decouples default themes (Colors, Fonts, Images) generated by ignite-base from themes that developers need to create for their Ignited apps. Each of these theme files now provide an empty object with a comment that tells the developer to add values for their own Ignited app.
> Decouple Ignite themes from ignited app

- packages/ignite/src/commands/add.js
It's awkward to have to bump package.json version numbers everytime you want to end-to-end test something.   
This skips caching.  And also, I can't get it work on yarn either, so I'm falling back to `npm` for directory based `ignite add`'s.
⭐️
> Fixes local dev caching of packages.

- README.md
- docs/contributors.md
- packages/ignite-cli/src/commands/add.js
- packages/ignite-cli/src/commands/new.js
- packages/ignite-cli/src/extensions/ignite.js
- packages/ignite-cli/src/extensions/reactNative.js
- packages/ignite-minimal-app-template/index.js
- packages/ignite-unholy-app-template/index.js
* adds a debug switch `ignite new Something --debug` for better tracing
* adds a temporary `package.json` during install to prevent node from walking up directories
* removes bad advice about Ignite 1 from the readme.md.
Fixes #709 
Example:
> Debug switch + placebo package.json during install

- packages/ignite-cli/src/commands/new.js
- packages/ignite-cli/src/extensions/reactNative.js
- packages/ignite-empty-app-template/index.js
- packages/ignite-minimal-app-template/index.js
- packages/ignite-unholy-app-template/index.js
- packages/ignite-unholy-app-template/package.json
- packages/ignite-unholy-app-template/templates/package.json.ejs
`ignite new Something --react-native-version 0.41.0` is working again.
Also, in unholy, we don't just copy our package.json overtop of the one that `react-native --init` creates.  We merge them together.  This will help us with subtle bugs when dependencies change in future releases on React Native.
> Fixes RN Version + Safely merges package.jsons

- packages/ignite-unholy-app-template/index.js
For Unholy, we use `ava` currently.  This deletes that `__tests__` directory.
If we do switch to `jest` it won't be before 2.0 launches.
Fixes #724
> Removes __tests__ during an unholy ignite.

- packages/ignite-cli/src/commands/new.js
- packages/ignite-cli/src/extensions/reactNative.js
- packages/ignite-cli/src/lib/exitCodes.js
Closes #730.
```sh
ignite new SweetBabyJesus \
--empty \
--react-native-version 0.42.0-rc.3 \
--react-native-template navigation
```
This was quick & dirty, but it'd be nice to integrate at a deeper level.  
For example, I'd like to explore embracing their templates as being the blessed way to do our app templates.  It's kinda awkward having both.
Their fallback of checking `react-native-template-*` on npm is 💯 (see https://github.com/facebook/react-native/pull/12548).
> Adds support for React Native templates.

- packages/ignite-cli/bin/ignite
- packages/ignite-cli/package.json
- packages/ignite-cli/src/cli/check.js
This PR makes node 7.6 a requirement now.
`async` and `await` are now part of the core.   No more living in `--harmony`.
Don't forget to upgrade to Node 7.6 `n 7.6` and `npm run bootstrap` after grabbing master.
> Bumps gluegun to require 7.6

- packages/ignite-cli/src/extensions/reactNative.js
Fixes #612.
When `react-native-cli` is not installed:
When `react-native-cli` is already installed:
> Updates ignite new to check/install react-native-cli

- packages/ignite-cli/package.json
- packages/ignite-cli/src/commands/add.js
- packages/ignite-cli/src/commands/generate.js
- packages/ignite-cli/src/commands/new.js
- packages/ignite-cli/src/commands/remove.js
- packages/ignite-cli/src/commands/spork.js
- packages/ignite-cli/src/lib/exitCodes.js
- packages/ignite-cli/src/lib/isIgniteDirectory.js
- packages/ignite-cli/tests/lib/isIgniteDirectory.test.js
You can only run `add`, `remove`, `spork`, and `generate` in an ignited project.
You can no longer run `new` in an ignited project.
Fixes #643
> Validates the directory before running commands.

- README.md
- packages/ignite-cli/src/commands/add.js
- packages/ignite-cli/src/commands/plugin.js
- packages/ignite-cli/src/commands/remove.js
- packages/ignite-cli/src/lib/detectInstall.js
- packages/ignite-cli/src/lib/prependIgnite.js
Per #702 , this PR adds a warning if you try to remove via a path.
I also fixed a bug where doing `ignite remove ignite-<plugin>` would try to remove `ignite-ignite-<plugin>`, and also refactored the prepending function to be used consistently from everywhere. Also a bit less Rambda/Rambdasauce and more vanilla JS.
I then snuck in a launch deadline update to the README. Steve will kill me for so many unrelated things in this PR if he notices.
> Adds a warning if trying to ignite remove /path/to/plugin

- packages/ignite-cli/src/commands/plugin.js
- packages/ignite-cli/src/templates/plugin/ignite.json.ejs
There's an issue with `ignite plugin new <x>` where it's looking for an ignite.json file. This PR adds one.
> Adds an ignite.json to plugin template with optional command

- packages/ignite-cli/src/templates/plugin/templates/thing.js.ejs.ejs
Since we're emitting an ejs file from an ejs file, things get wonky. This fixes that and adds a comment to make it better later.
> Escapes plugin command template properly

- packages/ignite-cli/src/commands/doctor.js
One test failure, I believe is unrelated. 
This is for https://github.com/infinitered/ignite/issues/710.
Adds a line to the output of `ignite doctor` that is the directory in which `ignite doctor` was run.
> Add current working directory to ignite doctor

- packages/ignite-cli/src/lib/detectInstall.js
- packages/ignite-cli/tests/lib/detectInstall.test.js
- packages/ignite-integration-tests/test/ignite-new/newMin.test.js
`ignite-` was being prepended to absolute paths.  
`ignite-/Users/steve/plugin` when it should have been `/Users/steve/ignite-plugin`.
> Fixes path resolving issues.

- docs/quick-start/ignite-commands.md
- packages/ignite-cli/src/commands/remove.js
This will be especially useful when we do CI, checking to see if a plugin cleans up properly after itself.
> Adds ignite remove <plugin> --confirm

- docs/quick-start/ignite-commands.md
- packages/ignite-cli/src/commands/remove.js
Per #787, you can now use `-y` or `--yes` in addition to `--confirm`.
> Adds the flag '-y' as an alias of '--confirm' to ignite remove

- .vscode/settings.json
- packages/ignite-cli/src/cli/cli.js
- packages/ignite-cli/src/commands/doctor.js
- packages/ignite-cli/src/commands/new.js
More judicious use of the Ignite header too.
> Adds ignite --help and modifies the output slightly.

- packages/ignite-basic-generators/index.js
- packages/ignite-cli/src/commands/add.js
- packages/ignite-cli/src/extensions/ignite.js
- packages/ignite-cli/src/extensions/ignite/addComponentExample.js
- packages/ignite-cli/src/extensions/ignite/addPluginComponentExample.js
- packages/ignite-cli/src/extensions/ignite/addPluginScreenExamples.js
- packages/ignite-cli/src/extensions/ignite/addScreenExamples.js
- packages/ignite-cli/src/extensions/ignite/removeComponentExample.js
- packages/ignite-cli/src/extensions/ignite/removePluginComponentExample.js
- packages/ignite-cli/src/extensions/ignite/removePluginScreenExamples.js
- packages/ignite-cli/src/extensions/ignite/removeScreenExamples.js
- packages/ignite-cli/src/templates/plugin/index.js.ejs
- packages/ignite-cli/src/templates/plugin/test/add.js.ejs
- packages/ignite-cli/src/templates/plugin/test/remove.js.ejs
- packages/ignite-cli/tests/extensions/ignite.test.js
This is for issue: https://github.com/infinitered/ignite/issues/636
Renamed Methods:
`addComponentExample` -> `addPluginComponentExample`
`addScreenExample`s ->`addPluginScreenExamples`
`removeComponentExample` -> `emovePluginComponentExample`
`removeScreenExamples` ->` removePluginScreenExamples`
Left old methods in place that call the new methods and print
deprecation warnings
> Rename plugin methods

- packages/ignite-dev-screens/index.js
This doesn't entirely fix #819 but I think it helps by making it less painful if they're not using our folder structure.
> Adds a more helpful error if DevScreens can't auto-insert itself

- packages/ignite-dev-screens/plugin.js
* `print` wasn't in scope globally, so we couldn't bring it up to the top level.
* `darkGray` isn't a colour, but `muted` is.
> Fixes the broken instructions in dev screen.

- packages/ignite-cli/package.json
Until mock-fs accepts that patch, this will hook us up.
This is what eslint did (https://github.com/eslint/eslint/commit/0fd9d2712aeeebc65399083f5249729da91c7bf6) as a temporary work around.
I've tested this on 7.6 and 7.7.1.
> Temporary fix for mock-fs.

- packages/ignite-ir-boilerplate-2016/boilerplate.js
If `android` isn't in your path or `ANDROID_HOME` doesn't point to a directory, this displays an error.
This is added at the boilerplate level, because different boilerplates will have different requirements.
Fixes #483
> Adds warning if Android not installed properly. Fixes #483

- packages/ignite-cli/package.json
- packages/ignite-cli/src/extensions/ignite/addModule.js
- packages/ignite-cli/src/extensions/reactNative.js
- packages/ignite-cli/src/lib/importPlugin.js
Just kidding, no we don't.  Only @kevinvangelder does.  
But!!! We will support it because it's damn popular!
So, some of the commands we shell out and don't work on windows.  
Specifically `react-native link` (again... we had issues with this on the mac which is why we had to switch to `stdio: ignore`).
This PR bumps gluegun as I've added `cross-spawn` to power `context.system.spawn` now.  It works the same as Node's spawn but ensures things work properly with Windows.
I don't know the who story, but apparently grandchild processes don't inherit the path, and there's some issues with escaping with the out-of-the-box node spawn experience.
Cross-spawn makes this patching invisible to us.  👍 
Address #862 .  I won't say "fixed" just yet, but I will say, it's working on my machine.  Will …
> We love Windows too!

- packages/ignite-cli/src/commands/new.js
- packages/ignite-cli/src/extensions/ignite/addModule.js
- packages/ignite-cli/src/extensions/reactNative.js
- packages/ignite-cli/src/lib/importPlugin.js
Windows gets cranky when you pass it blank parameters.  So this trims it up where necessary.
Also `spawn` is only necessary with `react-native link` and `react-native unlink`, so I'm changing spawn to exec everywhere else.  
I'd like to minimize the footprint of spawn in gluegun because I'd like for it to go away shortly.  Once I get to the bottom of `react-native link`.
> Adds more fixes to support windows.

- docs/README.md
- docs/advanced-guides/creating-plugins.md
- docs/advanced-guides/creating-project-plugins.md
- packages/ignite-cli/src/cli/cli.js
- packages/ignite-cli/src/extensions/ignite/findIgnitePlugins.js
- packages/ignite-cli/tests/cli/cliConfig.test.js
- packages/ignite-cli/tests/extensions/findIgnitePlugins.test.js
- packages/ignite-cli/tests/extensions/ignite.test.js
Adds support for creating project-based plugins.
From the docs:
>
> * generators that make little sense outside your project
> * scripts that are a bit more complex than a one liner inside your `package.json`
> * a playground for exploring ignite
> * a proving arena for plugins you intend to build & release, but aren't quite ready yet
>
Fixes #861
> Plugins that only live in your project.

- docs/quick-start/getting-started.md
- packages/ignite-cli/src/commands/attach.js
If you have an existing project and still want to use ignite:
`ignite attach`
This works great for:
* [create-react-native-app](https://github.com/react-community/create-react-native-app)
* [Expo](https://expo.io)
* [create-react-app](https://github.com/facebookincubator/create-react-app)
* normal React JS projects
* empty directories ( not even joking! you can use this with other programming languages.  :O )
Gluegun FTW.
> Adds support for create-react-native-app, Expo, and more!

- packages/ignite-dev-screens/templates/DevscreensButton.js
On android, the onRequestClose prop is required for Modals to instruct how to handle the hardware back button.  I just implemented a quick check to quell this message and toggle the modal in the same fashion as the 'X' button.
I know things have changed for ignite 2, so let me know if there's anything I need to address.
> updated dev screen modal to quell android propTypes

- packages/ignite-cli/src/commands/new.js
React Native doesn't allow kebab case project names, and neither will we...
Check for kebab case (dashes) project naming when a user is igniting a new project, and return a useful error if found.
> Check for kebab case project names and return useful error

- README.md
The 'code style | standard' badge appeared to be broken
Fixed a badge on the README.md
> Fixed a badge on README.md

- README.md
- docs/README.md
* I added a link to docs/README.md from the initial README.md doc under a 'Documentation' header so users can easily find the detailed documentation without having to search the codebase for the /docs directory
* New docs have been added under docs/advanced-guides and docs/quick-start without having links from docs/README.md. I added the missing links.
> Added links to README docs

- packages/ignite-cli/src/commands/new.js
- packages/ignite-cli/src/lib/exitCodes.js
Fixes #913 .
`react-native init` already checks for this condition.  We didn't.  Now we do.
> Prevents new from running when node_modules/react-native exists.

- packages/ignite-cli/package.json
- packages/ignite-cli/src/cli/check.js
- packages/ignite-cli/src/cli/enforceGlobalDependency.js
- packages/ignite-cli/src/extensions/reactNative.js
- packages/ignite-cli/src/lib/exitCodes.js
We have 2 global dependencies.
`react-native-cli` is required and needs to be `>=2.0.0`.  Older versions of this cause an `ENOENT` error when using `nvm`.  So we now enforce this.
`yarn` is optional and if installed needs to be `>=0.21.0`.
Heads up @jamonholmgren, i removed the auto-installing of the `react-native-cli` in favour of a message.  We don't want to install global dependencies because we don't know the environment.  The only requirement is that it is installed, not that it is installed via `npm i -g`.
A good example of this is when people installed on linux and they `sudo`.  Our command will fail, so it's better to just show them the command and let them run it.
I understand this is a step back from what you had, but this is safe.
Fixes #919
> Enforces global dependencies are available.

- packages/ignite-cli/package.json
This will shrink `ignite-cli` by 13mb.
> Bumps gluegun to 0.17.1.

- packages/ignite-cli/src/cli/check.js
- packages/ignite-cli/src/cli/enforceGlobalDependency.js
Currently, Ignite warns if you have the wrong react-native-cli version installed:
```
~/Documents/Ignite2Experiments > ignite new fontfix
Ignite requires react-native >=2.0.0 to be installed.
You currently have 1.3.0 installed.
To install: npm i -g react-native-cli
```
However, it's misleading. This allows specifying the npm package name to more accurately reflect what is missing.
> Allows specifying the package name when checking dependencies

- packages/ignite-cli/src/cli/check.js
> Adds sanity check for presence of `react-native` conflict

- PLUGINS.md
> add source map to list

- bin/testRelease
- packages/ignite-cli/package.json
- packages/ignite-cli/src/cli/check.js
- packages/ignite-cli/src/cli/enforceGlobalDependency.js
Fixes #949
[According to @skellock](https://github.com/infinitered/ignite/issues/949#issuecomment-291283847):
> when we shell out, node is giving precedence to the node_modules/.bin/react-native executable instead of the global one on the path.
This change calls `$(which react-native) --version` rather than `react-native --version` which should address the problem in issue #949 and others.
> References proper react-native binary - Fixes #949

- README.md
Added note about Yarn global not working on Windows.
I thought it was strange that we say to install Yarn, and then the final install command uses npm.
This adds a little clarification.
> Add clarification about final npm install command after saying to install Yarn

- packages/ignite-cli/src/cli/cli.js
- packages/ignite-cli/tests/cli/cliConfig.test.js
I have a suite of gluegun extensions incoming, and I'd like them to be available in ignite as well.
For example https://github.com/skellock/gluegun-prettier.
This makes these extensions auto-detectable.
```sh
yarn add --dev gluegun-prettier
```
```js
context.prettier.reformat('/path/to/the/ugly.js')
// or
const pretty = context.prettier.format(` console\n.tab(   'lol'\t\t\t)\n\n\n`)
context.print.info(pretty)
```
> Adds gluegun plugin detection.

- BOILERPLATES.md
- PLUGINS.md
- README.md
Issue: https://github.com/infinitered/ignite/issues/943
Adds list of boilerplates (3rd party and IR supported) to the README
> Add boilerplate list

- .travis.yml
- bin/ci
Simplifies Semaphore to run `./bin/ci` and that takes care of setup, linting, tests, and integration tests.
> Adds testRelease script back in as bin/ci

- src/cli/enforceGlobalDependency.js
- src/lib/importPlugin.js
Closes #1007. My yarn isn't installed to a directory with a space on this machine, so I'll try to test it later on another machine.
> fix for issue when space in yarn install path

- bin/ci
- src/cli/check.js
- src/commands/add.js
- src/commands/boilerplate-install.js
- src/extensions/reactNative.js
- src/lib/importPlugin.js
This PR does two things:
• Shaves about 2-3 seconds off of startup time by avoiding costly and probably over-cautious checks
• Adds some perf numbers to the output:
I spent a lot of time pouring through the code here. There's not a lot of additional optimizations that I could find that made a large difference. Most of the improvements came from [the boilerplate](https://github.com/infinitered/ignite-ir-next/pull/33).
> Performance updates

- src/extensions/reactNative.js
We are going to require boilerplates to specify a RN version during their `install()`.
Add warning of deprecation and a fallback version.
> Add condition for rn version deprecation & fallback to default

- src/extensions/ignite/addModule.js
- src/templates/plugin/plugin.js.ejs
> Warn on plugin addModule if no version specified

- .sibbell.yml
Per @kevinvangelder , this will help us keep on top of dependencies. I've already added the integration to `infinitered` org, so you can add your own .sibbell.yml file to any of the other repos to do the same.
Sibbell files Github issues whenever a new release happens on a monitored repo, and includes the release notes.
> Adds Sibbell config file for monitoring dependencies

- src/cli/cli.js
Because of the way Gluegun and Ignite CLI work together, it's a little messy to accept either `--debug` or `--verbose`. So, given the late hour and wanting to get another release out, I cheated a little -- we just error and tell the user to use `--debug` instead of `--verbose`.
I'm happy to review and accept pull requests if this is unacceptable to you. ;) ;) ;)
"Fixes" #786 .
> Adds error if you use --verbose instead of --debug

- package.json
This also pins all dependencies. We should run `npm outdated` before every release. Couldn't update gluegun because of #1040.
> Upgrades dependencies and adds npm run shipit

- package.json
Upgrades to the latest `gluegun`.
Various fixes, but one nice feature we can start using is:  all `context.*` extensions are now exported and available.
```js
import { system } from 'gluegun'
system.which('node')
```
🎉 
Sad side note:  `0.18.0` had some unwanted breaking changes that I patched up in `0.18.1`.  I also upgraded all the deps.  Which had 3 broken enquirer packages, which i rolled back in `0.18.2`.  😢 
I've tested this branch against `ir-next` and `ir-boilerplate-2016` and it's compatible.
> Bumps gluegun to 0.18.2.

- bin/ci
- docs/quick-start/ignite-commands.md
- src/commands/new.js
- tests/integration/ignite-new/newInvalid.test.js
Allows for `--overwrite` flag on `ignite new MyApp` to overwrite an existing folder. Useful for testing over and over. Will also ask (rather than just abort) if it encounters an existing folder without the flag.
> Adds overwrite project on ignite new

- src/commands/add.js
- src/lib/detectInstall.js
- tests/fast/lib/detectInstall.test.js
Prior to this change, doing `ignite add i18n@0.1.2` would result in an error.
Related to https://github.com/infinitered/ignite-ir-next/issues/57.
> Allows setting @ version on ignite add

- src/extensions/ignite/addPluginComponentExample.js
- src/extensions/ignite/addPluginScreenExamples.js
- src/templates/plugin/plugin.js.ejs
Plugin examples retained their `.js.ejs` extension, causing a crash. This fixes that.
> Fixes bug where .ejs was left on plugin examples

- .gitignore
- src/commands/spork.js
- src/extensions/ignite/copyBatch.js
- tests/integration/ignite-new/new.test.js
- tests/integration/ignite-new/newInvalid.test.js
Spork was broken in `copyBatch` generators. This fixes issue #1043.
I also added an end-to-end test. The assertions can be filled out much more, but I'm happy to have what we have here. Should be very useful to catch `ignite new` issues, and it also tests a generator and of course sporking. This fixes #1050.
I also had to add the ability to specify a spork file from the initial command. Example: `ignite spork component.ejs` should spork just that file and not wait for input. Truthfully, that's how I thought it worked already!
> Fixes sporking issue, adds better tests

- BOILERPLATES.md
- README.md
- bin/ci
- docs/advanced-guides/creating-boilerplates.md
- docs/quick-start/ignite-commands.md
- docs/quick-start/using-boilerplates.md
- src/commands/new.js
- src/templates/plugin/boilerplate.js.ejs
Moving from the venerable `ignite-ir-boilerplate-2016` to the fresh, hot `ignite-ir-boilerplate` version 2.0.0 (Andross), which is currently released as `2.0.0-rc.1`.
> Switches default boilerplate from ir-boilerplate-2016 to ir-boilerplate

- package.json
This dependency was missing causing the integration tests to fail.
> Adds missing `tempy` dependency from package.json.

- PLUGINS.md
This adds the json-server plugin to PLUGINS.md.
NOTE: do not merge until someone -anyone - has tested this plugin in their own environment: `https://github.com/infinitered/ignite-json-server`
> Add json-server to plugins list

- bin/ci
- package-lock.json
Rather than running integration tests in `./testgrounds`, this change will run those tests in a temporary directory. This solves #1058 and other potential issues.
> Updates ci script to run in a temp directory

- PLUGINS.md
Update the docs to add redux-thunk to the plugins list. This is an ignite plugin that provides redux-thunk.
> Add redux-thunk to plugins list

- src/extensions/reactNative.js
Just a suggestion. It allows being sure if the error is inside the ignite command or install command
> Adds log command after install

- docs/quick-start/project-structure.md
react-native no longer has two platform specific entry files, but instead has consolidated them into one `index.js`
> replace `index.android.js` and `index.ios.js` with `index.js`

- src/lib/isIgniteDirectory.js
This PR fixes #1206 by moving the negation into the expression.
This does not change semantics, it just makes use of `return false` on line 13 immediately in some cases instead of waiting for an error to cause `return false` on line 21 to be used.
Since this does not change semantics, a test can not easily be written for it (we could monitor for exceptions within the fs-mock, but that seems excessive).
> Fix precedence error for file existence check in isIgniteDirectory

- BOILERPLATES.md
- 🤷🏼‍♂️* Everything works on iOS/Android
- ✅ `npm test` **ava** tests pass with new tests, if relevant
- N/A `./docs/` has been updated with your changes, if relevant
(*) **This PR contains a singe change to `BOILERPLATES.md` so I did not smoke test a build of ignite to generate an app.**
I have added my fork to the list of 3rd party boilerplates.
> Adding ignite-expo-boilerplate to the list of Boilerplates.

- PLUGINS.md
I had made `ignite-fabric` a while back, but since Fabric has been bought by Google (Firebase), the instructions to get started have changed, and now Crashlytics is replacing Crash detection on Firebase, so I revamped the plugin with the new setup instructions and renamed it to `ignite-crashlytics` (because that's actually the only thing it sets up).
Right now, the other plugin is still working, though, so I marked it as `(to be deprecated)`.
Is that good for you guys?
> Upgraded crashlytics plugin and changed name

- bin/ci
- src/cli/check.js
- src/commands/new.js
- src/commands/plugin.js
- src/extensions/ignite.js
- src/extensions/ignite/copyBatch.js
- src/extensions/ignite/generate.js
- src/lib/importPlugin.js
- tests/fast/lib/detectInstall.test.js
- tests/integration/ignite-new/new.test.js
Hey guys, 
I'm preparing to try to add support for `create-react-app` thru ignite, first though I thought I would lint things, and whaddya know.... found there were these errors:
```
/home/justin/projects/node/ignite/src/cli/check.js:37:78: Trailing spaces not allowed.
/home/justin/projects/node/ignite/src/cli/check.js:90:1: Too many blank lines at the end of file. Max of 0 allowed.
/home/justin/projects/node/ignite/src/commands/new.js:74:47: Redundant use of `await` on a return value.
/home/justin/projects/node/ignite/src/commands/new.js:187:1: Too many blank lines at the end of file. Max of 0 allowed.
/home/justin/projects/node/ignite/src/commands/plugin.js:21:10: Redundant use of `await` on a return value.
/home/justin/projects/node/ignite/src/extensions/ignite.js:36:23: 'system' is …
```
> A little linting cleanup

- BOILERPLATES.md
Hello! Adding a link to a boilerplate I've developed for react single page apps, based on`andross`. Uses `create-react-app` under the hood to create the initial skeleton and then writes the boilerplate from there.
Designed to answer the question: _Is there an ignite boilerplate for web?_
:smile:
> Add ignite-kryptonite web boilerplate

- docs/advanced-guides/using-development-build.md
This is a small update to the doc: using-development-build.md
Tested in https://dillinger.io/ to make sure markdown looks right. The update to the doc covers a scenario where the user cannot run `yarn link` without errors because a symlink exists in a directory. It covers how to solve this issue.
> Update documentation to solve a potential issue

- docs/quick-start/ignite-commands.md
- src/lib/importPlugin.js
This allows developers to generate an app using a specific version of a boilerplate, such as a past release or a beta release.
I plan on releasing some big breaking changes to my boilerplate and it would be nice to allow users to generate using an older version if they wish.
> enable using specific version of a boilerplate

- src/extensions/reactNative.js
Fixes https://github.com/infinitered/ignite/issues/1142
with https://github.com/infinitered/ignite-andross/pull/241
Ensures that running `boilerplate-install` with `--npm` uses npm
> Pass npm option to react-native cli

- src/templates/plugin/boilerplate.js.ejs
Just a minor update to the way the Git repository is initialized. A Git commit message subject line should _not_ end with a period.
This changes
Initial commit.
to
Initial commit
Also see: [Rule 4 "How to Write a Git Commit Message"](https://chris.beams.io/posts/git-commit/#end)
> Remove trailing period from 'Initial commit'

- src/lib/detectInstall.js
Lookbehind might not always be supported
> Use regex without lookbehind in detectInstall

- src/commands/new.js
Closes #1389 
Warns the user appropriately in case more than one arguments were provided for `<projectName>`
> `ignite new <projectName> arg` shows up suitable warnings
> Warns the user if multiple arguments are provided as part of new command

- src/commands/attach.ts
- src/commands/doctor.ts
- src/commands/new.ts
- src/extensions/ignite.ts
- src/extensions/ignite/ignite-config.ts
- src/lib/add-empty-boilerplate.ts
- src/lib/attach-ignite.ts
- src/lib/boilerplate-install.ts
- src/templates/plugin/boilerplate/ignite/ignite.json
- src/types.ts
This updates Ignite CLI to do the following:
1. Adds the boilerplate version into the `./ignite/ignite.json` project config file
2. Ensures `ignite attach` is run after every boilerplate to remove requirement to have `ignite/ignite.json` in boilerplates
4. Adds git initialization to Ignite CLI, to remove requirement to handle git in boilerplates
5. Updates `ignite doctor` to show everything in the `ignite/ignite.json` project config file
Fixes #1406.
> Updates ignite doctor to show boilerplate version

- src/commands/add.ts
- src/commands/remove.ts
There's no compelling reason to error when you're not in an Ignited project. This removes that requirement. If plugins want to write to a non-existent Ignite config, it'll be created for them (as long as they use `setIgniteConfig`).
This also fixes an issue I'm having with Ignite CLI 3.1.0.
> Removes requirement to have Ignite attached to add a plugin

- src/commands/plugin.ts
The goal of this PR is to fix issue 1418. It seems that, according to the parameters list, second should be used for the plugin name instead of third:
```
{ plugin: 'ignite',
command: 'plugin',
array: [ 'new', 'toto' ],
options: {},
raw:
[ '/Users/ghemmen/.nvm/versions/node/v10.15.3/bin/node',
'/usr/local/bin/ignite',
'plugin',
'new',
'toto' ],
argv:
[ '/Users/ghemmen/.nvm/versions/node/v10.15.3/bin/node',
'/usr/local/bin/ignite',
'plugin',
'new',
'toto' ],
first: 'new',
second: 'toto',
third: undefined,
string: 'new toto' }
```
> 1418 - Use parameter second instead of third for plugin name

- package.json
- src/types.ts
- yarn.lock
This upgrades Gluegun and updates IgnitePlugin `commands` to use `GluegunCommand<IgniteToolbox>[]` generic.
> fix(types): Updates GluegunCommand type for Ignite plugins

- src/commands/spork.ts
Fix #1433
[This section of code](https://github.com/infinitered/gluegun/blob/b158829a991fe33fc48d7da4a35387bed874620a/src/toolbox/prompt-tools.ts#L37-L48) would normally handle old enquirer prompt types, but we are passing a single object instead of an array so the `map` doesn't happen.  
Replacing `checkbox` with `multiselect` fixes it.  The other option is to make the prompt pass an array instead of a single object but this fix seems better.
> fix prompt type for spork command

- src/commands/doctor.ts
Added a "naive" check for CocoaPods if user is on mac, since it is now a RN core "prerequisite".
> Added "naive" check for cocoapods.

- src/lib/import-plugin.ts
- [ not sure if applicable ] Everything works on iOS/Android
In response to #1474 i stopped printing the error message, logging it instead. This will hide it from everyday output while still making it easily available via the --debug flag
> Do not print import-plugin error, log instead

- src/commands/doctor.ts
fixes #1473
Generators where empty in ignite doctor command due to empty value in project's `ignite/ignite.json` file. This fix adds generators found from runtim commands.
fixes #1473
> fix: generators is empty in ignite doctor

- PLUGINS.md
Added two new plugins:
* navigation : Adding `react-navigation`
* netinfo : Adding `Netinfo`, now that it has been removed from the core
> Added navigation & netinfo plugins + Note about registry

- src/commands/new.ts
This fixes the commit message format used for the initial commit.
The second line in a Git commit message **must be empty**, since it separates the subject line from the body.
References:
https://chris.beams.io/posts/git-commit/#separate
https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
> Fix initial commit message

- .github/CONTRIBUTING.md
- src/cli/check.js
- src/commands/doctor.ts
- src/extensions/reactNative.ts
Hi there 👋
I notice that this cli still forces having `react-native-cli` to be installed, while it is no longer recommended by its maintainers ( [React Native CLI](https://github.com/react-native-community/cli#using-npx-recommended)).
So i have update the code to use `npx react-native init` instead of `react-native init` and update the checker and doctor scripts to not check for `react-native-cli`.
Thanks
> feat: use npx for react-native-cli

- package.json
- yarn.lock
Upgrades all deps to latest.
Gluegun 4.1.0 will support plugins in a `./build` folder, which we will need for converting [boilerplates to TypeScript](https://github.com/infinitered/ignite-bowser/pull/284).
> Upgrade all deps -- mainly Gluegun

- package.json
- tests/integration/ignite-new/new-bowser.test.js
- yarn.lock
When I run commands like `ignite generate` in a Bowser app, I was getting a screenful of warnings:
```
$ ignite g
(node:44309) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:44309) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:44309) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:44309) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
[...]
```
Traced this to [this issue](https://github.com/nodejs/node/issues/32987#issuecomment-635726114) - turns out our problem was also a need to upgrade to a newer `shelljs`, which fixed …
> Fix shelljs warnings & test failures

- boilerplate/package.expo.json
- boilerplate/package.json
- src/commands/new.ts
- src/tools/generators.ts
- src/tools/spawn.ts
- test/ignite-new.test.ts
Fix `ignite new AppName --expo` in Flame, which was failing because it tries to run `npm prepare` (in the context of the boilerplate's package.json) at some point before it's actually copied the boilerplate to the new app's directory... and since we have a "prepare" script in the boilerplate's package.json that runs `npm-run-all patch hack:*`, it tried to run that -- but since it hadn't installed dependencies yet, `npm-run-all` isn't available.
I fixed this by (in the --expo case) ~~copying the boilerplate to a temp directory and removing the "prepare" script from the copy's package.json before passing that temp path to `expo-cli`. I added the "prepare" script to the boilerplate's `package.expo.json` so it gets added back when we merge that in later.~~ removing the "prepare" script from …
> Fixes for `ignite new --expo` in Flame

- boilerplate/README.md
- boilerplate/app/app.tsx
- boilerplate/index.js
- boilerplate/storybook/toggle-storybook.tsx
Wraps the whole app in a new component that (in `__DEV__` mode only) adds an item to the shake menu to toggle Storybook mode; this replaces the `SHOW_STORYBOOK` constant in `index.js`.
(@fvonhoven and I did this together. FYI, Frank - I also did a few doc updates for it, and ended up renaming the new component and moving it into the /storybook directory since it's such a special-purpose component.)
> Toggle storybook from the Dev menu

- boilerplate/ignite/templates/model/NAME.test.ts.ejs
- src/commands/new.ts
- src/tools/spawn.ts
- test/_test-helpers.ts
- test/ignite-new.test.ts
A few things:
- Fixed the generated model test template - it was wacky.
- Improved the formatting of to-get-started message output.
- Made spawnProgress produce more error output when running a command that exits with non-zero status.
- If we're generating a new app with `--debug`, run the CLI commands more verbosely.
- De-duplicated much of the code in the generated-app tests.
- Fixed a lint complaint (outside the boilerplate; our generated apps still have lots of lint complaints - might work on this next)
- Our generated apps don't have storyshots files; had to add `--updateSnapshots` to the ignite-new tests to get them to pass on CI; also, CI tests were exceeding the 5-minute timeout, so I extended it to 8 minutes.
> Flame test fixes

- src/commands/new.ts
When a user installs `ignite-cli`, `npm` & `yarn` play games with `.gitignore` and `.npmignore` files: they're merged and the result is stored in `.npmignore`. Because we only have `.gitignore`, this means that when running a production-installed `ignite new`, our `.gitignore` can be found at `.npmignore`. Neither base installer (`expo-cli init` or `react-native init`) copies it; This leads to #1578.
This fixes that by checking for .gitignore after the base installer is done (as before), and copying either `.gitignore` or `.npmignore` from the boilerplate, whichever is present.
> Fix production `ignite new`'s failure to copy .gitignore

- boilerplate/app/screens/demo/demo-screen.tsx
* Add verbiage about the storybook debugger menu option to the demo screen
* Also reordered the `<BulletItem/>`s on the `demo-screen.tsx` for better context and readability
> Add storybook info & instructions to demo screen

- boilerplate/test/i18n.test.ts
No updates to the README, no new tests added (`yarn ci:test` passes).
The current boilerplate test in `test/i18n.test.ts` named "There are no missing keys" is incorrect because the `grep` path is _ever-so-slightly_ off. The relative path should be `'./app'` and not `'../app'`, as child processes spawned in Jest tests using `exec` run in Jest's [root directory](https://jestjs.io/docs/en/configuration#rootdir-string), not the directory containing the test file ([original code commit](http://lab.cloudpresser.com/root/ignite-cloud-presser/commit/d0cae5484a96f4d686ab61c87428ec5749b194d6)).
I won't detail how I found this bug, but it involves creating an Ignite app named "app", i.e. running `npx ignite-cli new app`.
Here's some evidence of the problem:
- inserting `console.log(stdout);` into …
> Fix grep path in i18n test

- boilerplate/app/screens/demo/demo-screen.tsx
- src/commands/doctor.ts
- src/tools/packager.ts
- src/tools/spawn.ts
@nirre7 had a problem that was caused by an older version of react-native-cli being installed globally (which is no longer recommended); he suggested having Ignite warn when this happens. https://infiniteredcommunity.slack.com/archives/CD8UA5RJ4/p1609336353033800?thread_ts=1609248567.028100&cid=CD8UA5RJ4
I think that's a great idea, and I thought it'd be useful as a preliminary step to see _all_ the globally-installed packages in `ignite doctor`'s output, so that's what this PR adds. Because `npm` and `yarn` store global packages in different places, it lists them separately -- the Javascript section of its output now looks like this (I just have one package in each group):
```
JavaScript (and globally-installed packages)
node                14.15.1 …
```
> Show globally-installed packages in `ignite doctor`

- README.md
The link was redirecting to an anchor which does not exist anymore on this page. I think you should redirect to the doc file MobX-State-Tree.md.
Best Regards,
Ruben
> Fix the "MobX-State-Tree [(Why not Redux?)]" Link

- src/commands/doctor.ts
This PR should fix #1579 by unifying the Java command with the macOS version, and also double protection by adding optional chaining.
> Fix issue #1579 -- ignite doctor on Windows -- adds optional chaining

- boilerplate/android/gradle.properties
- boilerplate/ignite/templates/model/NAME.ts.ejs
- boilerplate/package.json
- Add `npm start`, `npm build-ios`, `npm build-android` into package.json to help generate bundlejs faster
- Add create new model to import in root-store
- Upgrade flipper version and react native 0.63.4
> [Fixes #1601] - Add podinstall prapare and add some script for package.json and model

- .circleci/config.yml
- test/ignite-new.test.ts
I just realized that the changes made to get CI passing for #1617 will also override the git config for anyone running tests locally. 🙀 
Since we only needed to make sure CircleCI has a configured git user I moved that into the CircleCI config.
Thanks @dlaynes for bringing it to my attention! Hope this answers your question.
> Only configure git user for CircleCI

- boilerplate/app/models/character/character.test.ts
- boilerplate/app/models/character/character.ts
- boilerplate/app/models/root-store/root-store.ts
- boilerplate/app/screens/demo/demo-list-screen.tsx
- boilerplate/app/screens/demo/demo-screen.tsx
- boilerplate/app/services/api/api.types.ts
- boilerplate/app/services/api/character-api.ts
- src/commands/new.ts
- src/tools/packager.ts
The `new` command was assuming `yarn` is installed. This PR fixes that and adds another method to the `packager` module, `packager.is("yarn" | "npm")`.
Fixes #1597.
> Fix issue where yarn was required when it shouldn't be

- src/tools/generators.ts
- Adds an exception to exclude adding files containing name `.styles` to `index.ts` in `generators.ts`. This is needed to avoid manual deletion of styles file from index.ts if we add a custom template to generate separate styles file.
> Add .styles to barrel export exception

- boilerplate/app/components/button/button.props.ts
- boilerplate/app/components/checkbox/checkbox.props.ts
- boilerplate/app/components/header/header.props.ts
- boilerplate/app/components/text-field/text-field.tsx
- boilerplate/app/components/text/text.props.ts
- boilerplate/app/i18n/en.json
- boilerplate/app/i18n/i18n.ts
- boilerplate/app/i18n/index.ts
- boilerplate/app/i18n/translate.ts
- boilerplate/app/screens/demo/demo-screen.tsx
- boilerplate/ios/HelloWorld.xcodeproj/project.pbxproj
- boilerplate/ios/Podfile.lock
- boilerplate/tsconfig.json
- boilerplate/yarn.lock
- package.json
I noticed that none of the tx props were autocompleting. I updated the the tx prop types to use a recursive type built from the default locales json. Now translation keys will autocomplete in VSCode:
> Add tx types for autocomplete

- boilerplate/app/components/screen/screen.props.ts
- boilerplate/app/components/screen/screen.tsx
- boilerplate/storybook/views/story.tsx
Exposes ScrollView's keyboardShouldPersistTaps prop on Screen component. Sets "handled" as a reasonable default.
> Add keyboardShouldPersistTaps to screen

- boilerplate/package.json
Refer to [readme](https://github.com/prettier/eslint-config-prettier/tree/v7.0.0) of eslint-config-prettier, they require the `"prettier"` config must to be last to override other configs.
Moreover, there is a conflict between eslint rule `@typescript-eslint/no-extra-semi` and prettier's rule. It can be checked by command `npx eslint-config-prettier ./app/app.tsx` and the output is:
```
The following rules are unnecessary or might conflict with Prettier:
- @typescript-eslint/no-extra-semi
```
In current used version (eslint-config-prettier v7.0.0), we can fix it by adding additional config `"prettier/@typescript-eslint"`. But an easier way is just update it to the latest version, after v8.0.0 it applies all configs by default.
> Modify eslint config to apply prettier config correctly

- boilerplate/app/components/button/button.presets.ts
Improving the typings on the buttons preset by using `Record<string, VIewStyle | TextStyle>`.
I ran into a cryptic error that took a very long time to debug until I realized one of the custom presets I added in the `textPresets` was not inline-typed with an `as TextStyle`. Putting these top-level types on the object made the blunder easier to spot.
> Improve types for button.presets.ts

- boilerplate/app/components/screen/screen.tsx
- boilerplate/storybook/views/story-screen.tsx
Fix the values passed to KeyboardAvoidingView `behaviour` prop.
As per React Native documentation `behaviour` is an enum ([link](https://reactnative.dev/docs/keyboardavoidingview#behavior)) which means one of the values must be provided. In case there is no need to use behaviour, the correct value should be `undefined`.
Please see screenshot below for the TS warning:
> Fix keyboard avoid view behaviour

- boilerplate/app/components/button/button.props.ts
- boilerplate/app/components/button/button.tsx
- boilerplate/app/components/checkbox/checkbox.props.ts
- boilerplate/app/components/checkbox/checkbox.tsx
- boilerplate/app/components/form-row/form-row.props.tsx
- boilerplate/app/components/form-row/form-row.tsx
- boilerplate/app/components/header/header.props.ts
- boilerplate/app/components/header/header.tsx
- boilerplate/app/components/icon/icon.props.ts
- boilerplate/app/components/icon/icon.tsx
- boilerplate/app/components/screen/screen.props.ts
- boilerplate/app/components/switch/switch.props.ts
- boilerplate/app/components/switch/switch.tsx
- boilerplate/app/components/text-field/text-field.tsx
- boilerplate/app/components/text/text.props.ts
- boilerplate/app/components/text/text.tsx
- boilerplate/app/components/wallpaper/wallpaper.props.ts
- boilerplate/app/components/wallpaper/wallpaper.tsx
- boilerplate/ignite/templates/component/NAME.tsx.ejs
I discovered that I could not use false in array styles while working on a top secret project:
By using react native's `StyleProp` generic we can support array styles just like base components do:
This also meant a bunch of `mergeAll`s could be removed which I think cleans up the components a little bit.
> Fix style prop types

- src/commands/new.ts
Fix problems for windows caused by 'file://' syntax that should only be used in linux
> fix(windows): Fix issue #1639 -- remove "file://" from template address

- src/commands/new.ts
Addresses: https://github.com/infinitered/ignite/issues/1632
Adds a check for an existing directory when running new. Throws if directory exists unless an overwrite flag is passed in which case it will remove the existing directory before continuing.
> Add overwrite option to new

- boilerplate/app/components/screen/screen.presets.ts
- boilerplate/app/utils/validate.ts
- boilerplate/ios/Podfile.lock
- boilerplate/package.json
Using ramda depends on team/project and can be avoided from using in boilerplate.
In all cases where imported ramda utils, we can use simple plain js:
1. As `preset` is runtime type of string `!preset` - will cover all from ramda isNil - undefined and null, plus !preset.length. Same for !presets[preset]
2. ramda `contains` is deprecated and not needed.
> Cut out ramda

- boilerplate/app/navigators/main-navigator.tsx
- boilerplate/app/navigators/root-navigator.tsx
- boilerplate/app/screens/demo/demo-screen.tsx
- boilerplate/app/screens/welcome/welcome-screen.tsx
- boilerplate/app/theme/palette.ts
Fixes #1627 white flash.
Adds a background color (to match the app) and transparency to the root and main navigators. This prevents the flash of white during navigation animations.
Demo with fix:
https://user-images.githubusercontent.com/57374/116876359-f4eb8880-abe1-11eb-962d-5c609be2d053.mp4
> fix: add background color to navigators

- src/commands/new.ts
- src/tools/filesystem-ext.ts
- src/tools/pretty.ts
- src/tools/react-native.ts
- test/ignite-new.test.ts
This was spurred on by some (apparently local?) problems I was having with the react-native CLI. However, I think it's worth a look even if react-native-cli works fine.
This PR removes our dependency on `@react-native-community/cli` aka `react-native-cli` and instead undertakes copying over the boilerplate files ourselves (when not using Expo).
Since the boilerplate is essentially already a runnable project, this is a pretty straightforward copy operation. We still do some cleanup by removing any stray Expo files that make it in and also run `npx react-native-rename` on it -- since your app is probably not named `HelloWorld`.
It seems that most of the time spinning up a new Ignite app is still when it's `yarn install`ing. We probably need to spend time stripping our dependencies down a …
> Remove react-native-cli and copy over files ourselves

- src/commands/new.ts
Currently, Ignite provides the wrong name ("Foo") on the overwrite error.
This fixes that.
> Proper error message when folder already exists

- boilerplate/package.json
```
react-native @0.64.1 sometimes it comes up:
Command line invocation:
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace PizzaApp.xcworkspace -configuration Debug -scheme PizzaApp -destination id=40CDF333-C994-4927-BCEB-CA9D58606E4F
User defaults from command line:
IDEPackageSupportUseBuiltinSCM = YES;
...
```
Two day ago, [react-native](https://github.com/facebook/react-native/releases/tag/v0.64.2) fix this!
So, we need use rn the latest version!
> modify react-native version

- boilerplate/ignite/templates/model/NAME.ts.ejs
As 'ramda' package has been complete removed, as has the ```import {omit} from 'ramda'``` on top of file, I believe this comment section should be removed as well.
> Remove ramda-omit leftovers from NAME.ts.ejs

- README.md
metadata updates to readme. Point to the correct npm repo instead of the incorrect one.
> The npm badge in the readme is pointing to ignite instead of ignite-cli

- boilerplate/package.json
Since we removed ramda from this release, we shouldn't need the types anymore either
> Remove  `"@types/ramda": "0.27.32",` from package.json

- boilerplate/storybook/views/story-screen.tsx
`StoryScreenProps` is an unused variable since it is not used in the file.
Typescript adjustment to include the aforementioned `StoryScreenProps` as the defined interface.
as a result, the eslint for `react/prop-types` on the props.children element is now satisfied.
> Typescript: prop types added

- boilerplate/android/app/src/main/java/com/helloworld/MainActivity.java
> Fix: Add missing RNGH android setup

- .gitignore
- src/commands/new.ts
In issue #1725, Expo builds were failing on `react-native-rename`, which isn't necessary since we are using `expo-cli` anyway.
This avoids calling the rename functionality when using Expo.
Additionally, we discovered that using some older versions of our CLI dependencies was causing issues, so we are locking major versions.
After implementing these changes, running `npx ignite-cli new MyApp --expo` with Node 16.4.2 succeeded.
cc @derekgreenberg
> Fixes Expo error on ignite new -- fixes issue #1725

- boilerplate/app/models/extensions/with-root-store.ts
This fixes type resolution when using the withRootStore extension.
fixes #1720
> Explicitly type rootStore in withRootStore extension

- src/commands/new.ts
In the `new` command, the step to rename the new project from the default HelloWorld is happening after `pod install` is run.  In testing locally, this is not reliable -- some Pods directories were not renamed, leading to breakage of `react-native run-ios` for the TV platform changes I've been testing.
I found no issues introduced by this change.  The change only affects non-expo projects.
> fix(cli): rename should happen before pod install

- README.md
- src/commands/help.ts
- src/commands/new.ts
- src/tools/validations.ts
- test/ignite-new.test.ts
In #1765, the issue is that on Android (vanilla apps), the bundle identifier is not being set.
This PR fixes that (thanks @carlinisaacson) and also provides the ability to pass in `--bundle` to your `ignite-cli new` command to customize that.
> Ensures that bundle ID is set and customizable

- README.md
Fix up a typo in the markdown which meant that the MacOS link wasn't rendering.
Just a small fix to a typo in the readme
> Fix up typo in readme.MD

- .gitignore
- package.json
- src/commands/new.ts
In #1776, `npm pack` seems to no longer copy over the .gitignore (nor the .npmignore that @bryanstearns used in #1582).
So, we're doing what [everyone else seems to do](https://github.com/facebook/create-react-app/blob/bb64e31a81eb12d688c14713dce812143688750a/docusaurus/docs/custom-templates.md#the-template-folder), and that is rename the file (in this case, we're copying it to `.gitignore.template`) for publishing and then copy it back for `npx ignite-cli new`.
I'll release this and test it after release, since that's the only reliable way to really test it.
> Copy over gitignore properly; fixes #1776

- src/commands/new.ts
With #1781, we fixed an issue where gitignore wasn't being copied. Our solution unfortunately left _two_ copies of gitignore, so this removes the extra one.
> Remove template file after generation

- boilerplate/ios/HelloWorld.xcodeproj/project.pbxproj
On my Mac M1, I was running into this error:
```
ld: warning: Could not find or use auto-linked library 'swiftCore'
```
(among many others)
<details>
<summary>Expand error</summary>
```
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
ld: warning: Could not find or use auto-linked library 'swiftUIKit'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use …
```
> Adds library search path for Swift error

- src/commands/new.ts
- [☑️] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [☑️] `README.md` has been updated with your changes, if relevant
It's been reported that some users are stuck on `install-colo-loco` while creating a new app, however, I was only be able to recreate it when omitting `--defaults` flag but that's just an intended hang for waiting a user input. I assume it's the package managers so let's run it via `npx` for now. (Investigation is still in progress)
> Run install-colo-loco via npx

- boilerplate/app/app.tsx
- boilerplate/app/navigators/app-navigator.tsx
- boilerplate/app/navigators/navigation-utilities.tsx
- [☑️] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [☑️] `README.md` has been updated with your changes, if relevant
- This fixes `canExit` not functioning (Issue: https://github.com/infinitered/ignite/issues/1841)
- There were two reasons
1. useBackButtonHandler() was called prematurely so the hook might not be able to detect the event from the screens.
2. When a screen `canExit`, just let the react-native listener know that we're not handling the event manually by returning `false`. We should "exit" properly and let the react-native listener know that we handled it.
- Created a temporary screen and its route name is `test`
- Continue button on the initial screen navigates to `test` screen
- Added `test` route to `exitRoutes` in `app-navigator.tsx`
```
const …
```
> Fix canExit not functioning

- src/commands/new.ts
- [☑️] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [☑️] `README.md` has been updated with your changes, if relevant
- Ref: https://github.com/infinitered/ignite/issues/1800
- When a user creates a new Ignite app without `git config` setup in the global environment(`user.name` and `user.email` to be precise) it fails on committing the initial changes after setting up the app.
- I wasn't able to recreate it when deleting `user.name` and `user.email` even deleting the items Keychain Access, but then I was when setting the items with empty(`""`) to trigger the error.
- This workaround fixes it and let the `ignite new` process complete - And let the user commit it after setting up the git config.
- Note: Didn't update the tests for when git config isn't setup, since …
> Continue "new" process when there's no git config

- boilerplate/app/navigators/app-navigator.tsx
- boilerplate/ignite/templates/screen/NAME-screen.tsx.ejs
- boilerplate/package.json
- package.json
DOES NOT PASS, looks like a `colo-loco` error? 
- [N/A] `README.md` has been updated with your changes, if relevant
- Addresses #1857 by adding in the requested types, along with some instructions for adding the screen to navigation config. 
Here's what the user sees in the generated screen: 
And here's what they see in `app-navigator.tsx` before adding their own config (arrows show what was changed):
- I'm thinking about the value of establishing a system where users can look for 🔥 in the code as a sign that they may need to add their own customization various places? This is an idea I stole from Kent C. Dodds courses.
> Add better typings and instructions to screen generator

- boilerplate/test/i18n.test.ts
Adds optional values in regex for i18n tests to support possible brackets in components for translation values.
Closes #1870
``` 
PASS  app/services/api/api-problem.test.ts (13.064 s)
PASS  app/utils/storage/storage.test.ts (13.115 s)
PASS  test/i18n.test.ts (13.162 s)
PASS  app/models/character/character.test.ts
PASS  app/models/character-store/character-store.test.ts
Test Suites: 5 passed, 5 total
Tests:       19 passed, 19 total
Snapshots:   0 total
Time:        17.856 s
Ran all test suites.
Done in 18.97s.
```
> Add optionals for brackets. Add an either statement for capital T or lowercase t.

- boilerplate/android/app/src/main/res/drawable/rn_edit_text_material.xml
- boilerplate/android/app/src/main/res/values/styles.xml
- boilerplate/android/build.gradle
- boilerplate/android/gradle.properties
- boilerplate/android/gradle/wrapper/gradle-wrapper.properties
- boilerplate/ios/HelloWorld.xcodeproj/project.pbxproj
- boilerplate/ios/Podfile.lock
- boilerplate/package.json
- boilerplate/yarn.lock
- src/commands/new.ts
fixes #1877
Upgrades the boilerplate project default version to React Native 0.67.2, which is the latest stable version.
Followed the [upgrade helper guide](https://react-native-community.github.io/upgrade-helper/?from=0.66.3&to=0.67.2).
Note that I did not add any of the Ruby/Bundler stuff, as we'll continue to rely on globally installed CocoaPods for now.
> Upgrades boilerplate to React Native 0.67.2

- src/commands/new.ts
- src/tools/packager.ts
When we added react-native-colo-loco, we sort of violated one of the rules of Ignite -- that we would have battle-tested every component of Ignite in a real project before including it in Ignite.
To be clear, I still think [react-native-colo-loco](https://github.com/jamonholmgren/react-native-colo-loco) is awesome! I think everyone should use it. But I also don't want to violate the trust of our Ignite users by using something that isn't as battle-tested in our default stack.
Fixes #1845.
> Removes react-native-colo-loco by default

- boilerplate/app/components/auto-image/auto-image.tsx
AsyncImage does a callback to resize the image when it is finished downloading. However, if you unmount the component while the download is in-flight, you'll get an error:
```
ERROR  Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
This PR will ensure that the state update only happens if the component is still mounted.
> Fix AsyncImage bug when component is unmounted quickly

- boilerplate/ios/Podfile.lock
- package.json
Fixes #1893.
Apparently `postinstall` runs even if you're installing globally, such as `npm install -g ignite-cli` or `npx ignite-cli`, which then fails because Solidarity is a devDependency.
This PR removes the `postinstall`. It doesn't appear there's a straightforward way to only run Solidarity in development mode, which is a bummer.
Thanks to everyone over at #1893 who reported this.
> Fixes global Solidarity installation failure (v7.10.3)

- boilerplate/patches/@storybook+addons+5.3.21.patch
Closes https://github.com/infinitered/ignite/issues/1860, https://github.com/infinitered/ignite/issues/1826?, https://github.com/infinitered/ignite/issues/1769
As discussed in a different PR #1863 there is an issue with react native storybook breaking promises due to the @storybook/addons dependency which includes a corejs Promise polyfill that doesn't work in react native.
For 5.3 the easiest fix without switching to beta is to patch this package.
- added a patches folder in the root of the boilerplate
- added the @storybook/addons patch 
Since the boilerplate is already configured to work with patch-package this should be all that is needed. In a quick test I did it seemed to work also.
The easiest way to test is to create a promise and call `.finally` on the resolved promise and it …
> fix: add patch for storybook/addons to resolve promise bug

- boilerplate/android/app/build.gradle
Fixes #1907 
Issue in app/build.gradle with relative paths caused an error when running `assembleRelease` for Android. Fix was found in this issue thread https://github.com/expo/expo/issues/16266#issuecomment-1039993702. I believe it will also be fixed in Expo 45 once that is available.
> fix: Fix absolute paths in app/build.gradle

- src/commands/new.ts
Removes the `build-ios` and `build-android` scripts from the generated package.json when using Expo flag. 
Fixes #1901
> Remove build commands for Expo Projects

- boilerplate/metro.config.expo.js
- src/commands/new.ts
Fixes #1904 by removing the custom metro config file if using Expo and replacing with the default Expo metro config. Expo doesn't work with pnpm anyway, so we won't bother trying to enable symlinks if using Expo.
If you want to try @AlexanderLindkjaer's experimental symlink support, check #1904's comments.
Also fixes #1899 (I think)
> Removes custom metro config & symlinks if using Expo

- src/commands/doctor.ts
There's a preinstalled `java` executable on mac, but it's not java (https://apple.stackexchange.com/a/348686).
Running doctor without installing java fails because the output of this executable is this:
> % java
> The operation couldn’t be completed. Unable to locate a Java Runtime.
> Please visit http://www.java.com for information on installing Java.
This pull request checks if the command ran successfully.
---
```
% ignite-cli doctor
System
platform           darwin                                                 
arch               x64                                                    
cpu                8 cores      Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz 
directory          ignite       /Users/truetiem/Desktop/ignite            
JavaScript (and globally-installed packages)
node …
```
> fix(doctor): java version throws error

- boilerplate/ios/Podfile.lock
- boilerplate/package.json
- boilerplate/yarn.lock
- yarn.lock
This is a follow-up to the [live stream](https://www.youtube.com/watch?v=-6oCo7lTRTw) with Adam from a few weeks back. I actually found the issue the same night, but forgot to submit it over the weekend.
Some of the tools are relying on a new behaviour introduced in `@rnx-kit/tools-node` 1.2.7. Things broke because Yarn decided that the older version should be hoisted instead.
> chore(deps): avoid 'path' issues with @rnx-kit tools

- boilerplate/package.json
prettier/@typescript-eslint was removed in eslint-config-prettier v8.0.0
see https://github.com/prettier/eslint-config-prettier/issues/173
also see more - https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
> removed `prettier/@typescript-eslint` in package.json

- README.md
- boilerplate/app/components/screen/screen.presets.ts
- boilerplate/app/components/screen/screen.tsx
- src/tools/react-native.ts
This PR updates how we "rename" the boilerplate project to the new specified project name. Issue #1963 brought up that android wasn't renaming correctly when we have a specific bundle identifier like `com.infinitered.pizzaapp`. The result was android would keep `helloworld` instead.
> Updating how we rename the boilerplate project to the new name

- boilerplate/ignite/templates/model/NAME.ts.ejs
When you create a model, you must manually import SnapshotIn.
> SnapshotIn import missing

- src/tools/packager.test.ts
- src/tools/packager.ts
Resolves https://github.com/infinitered/ignite/issues/1993 by using a regex to remove any command output that has `npm WARN` at the beginning of the line
- Adds unit test to ensure that packager `list` function handles input described in issue
- Adds unit test to ensure that valid json input is parsed correctly
> Handle "npm WARN" output in npm packager list command via regex replace

- boilerplate/README.md
Remove mention of plugins and ignite.json that were removed in [ignite v6: flame](https://github.com/infinitered/ignite/releases/tag/v6.0.0)
Fixes #1652
> fix (#1652): Remove outdated mention of ignite plugins and ignite json config

- boilerplate/app/components/Icon.tsx
See [discussion here](https://github.com/infinitered/ignite/pull/2014#discussion_r946208895) for more info.
> fix: Specify Icon onPress prop is inherited from TouchableOpacity

- src/commands/new.ts
During the `new` command process, the header makes mention of the package manager to the user but a later status message indicates the use of `npm` regardless, this could be confusing to a newer user of Ignite. 
For example, the header is written out with:
`Using ignite-cli with yarn` 
but later followed with:
`Unboxing npm dependencies`
This PR updates that message so it's consistent with the package manager in use.
> Enhancement: package manager message consistency

- boilerplate/app/models/AuthenticationStore.ts
- boilerplate/app/screens/DemoComponentsScreen/DemoComponentsScreen.tsx
- boilerplate/app/screens/DemoComponentsScreen/demos/DemoTextField.tsx
- boilerplate/app/screens/DemoPodcastListScreen.tsx
- boilerplate/app/screens/LoginScreen.tsx
- boilerplate/ios/Podfile.lock
- boilerplate/package.json
- boilerplate/test/mock-react-native-image.ts
- boilerplate/tsconfig.json
- Adds a default email / password to the auth store which allows the user to just click login when they first boot up their Ignited app. 
- Adds observer to the RNR episodes screen to fix the initial data load bug
- Fixes the ESlint no unused var rule to allow _ prefixing to ignore
> Fixes RNR screen initial load and first-run UX on login screen

- boilerplate/app/components/checkbox/checkbox.props.ts
- boilerplate/app/components/checkbox/checkbox.story.tsx
- boilerplate/app/components/checkbox/checkbox.tsx
By default, using storybook to view checkbox component text will be white and invisible, so I changed the default color to `color.palette.black` to get a better presentation.
And I think adding labelStyle will make better use of the checkbox component.
> Checkbox component add labelStyle, modify the default label color

- boilerplate/app/components/TextField.tsx
By default the TextField component has a problem with draggable text up and down on Android.
So I changed the default `20` to `24` to ensure proper display.
> Fix the problem of TextField component in Android height

- boilerplate/app/components/bullet-item/bullet-item.tsx
- boilerplate/app/components/checkbox/checkbox.tsx
- boilerplate/app/screens/DemoPodcastListScreen.tsx
- boilerplate/app/screens/WelcomeScreen.tsx
- boilerplate/app/theme/spacing.ts
- docs/Theming-Spacing.md
- docs/Theming.md
- Change the spacing scale to have more user friendly names, vs an array. Also add better typeahead hints by exporting `as const`
- Updated the descriptive documentation and moved it to `docs`
> (feat): more user-friendly spacing scale

- boilerplate/app/components/Button.tsx
- boilerplate/app/components/ListItem.tsx
- boilerplate/app/components/TextField.tsx
- boilerplate/app/components/bullet-item/bullet-item.tsx
- boilerplate/app/components/checkbox/checkbox.tsx
- boilerplate/app/models/Episode.test.ts
- boilerplate/app/models/Episode.ts
- boilerplate/app/screens/DemoCommunityScreen.tsx
- boilerplate/app/screens/DemoComponentsScreen/demos/DemoListItem.tsx
- boilerplate/app/screens/DemoComponentsScreen/demos/DemoTextField.tsx
- boilerplate/app/screens/DemoPodcastListScreen.tsx
- boilerplate/app/utils/format-date.ts
- docs/Components-Checkbox.md
- docs/Components.md
This PR address some changes to the work @yulolimum did in another [PR](https://github.com/infinitered/ignite/pull/2065). The two main aspects are how we're stying left/right/top/bottom for margins and padding and updating our dates formatter to take locale into account.
Since we're supporting RTL, we should move away from using `{margin/padding}Left` and `{margin/padding}Right`. 
For LTR: start = left, end = right
For RTL: start = right, end = left
In [Android 4.2's support for RTL layouts](http://developer.android.com/about/versions/android-4.2.html#RTL) they give an example of how to use this flow following the above mentioned.
Added a new `/app/utils/format-date.ts` util file that makes our `date-fns` format function locale specific. 
NOTE: there is a known bug where this package …
> Maverick Styling and Date to account for i18n (and RTL)

- src/commands/new.ts
- src/tools/flag.ts
- src/tools/react-native.ts
Resolves https://github.com/infinitered/ignite/issues/2056 by checking if directory exists or not before moving into target directory
> Fix `new` command target directory flag for non-default arguments

- src/commands/new.ts
- Wrap all boolean options in `boolFlag` utility so that options match type signature
- Shorten suggested command output for true values: `--install-deps=true` -> `--install-deps`
> Convert all values to boolean in `new` command, shorten suggested command flags

- src/commands/new.ts
When a flag value (like `--git=false`) is suggested from the chosen options, a dangling `}` is added.
Example:
```
npx ignite-cli new PizzaApp --bundle=com.pizzaapp --git=false} --install-deps=false} --packager=yarn --target-path=/Users/joshuayoes/Code/PizzaApp
```
This PR removes that dangling `}` from output
> Remove `}` from `false` flag suggestion after `new` command

- boilerplate/app/screens/DemoPodcastListScreen.tsx
Found an issue when spinning up a new app, `DemoPodcastListScreen` is empty: #2075 
I think the favorites feature was related. The length of favorites doesn't change on initial load so extra data doesn't change and the flatList never re-renders. But I still don't understand why the lists would show up on the reload.
|Fixed|Favorite List persists|
|-|-|
|![CleanShot 2022-08-29 at 11 08 27](https://user-images.githubusercontent.com/53795920/187257526-f6ab45ca-ebea-4722-87cd-4daa6cec578b.gif)|![CleanShot 2022-08-29 at 11 09 38](https://user-images.githubusercontent.com/53795920/187257336-24458aba-8e70-4f5e-ae61-6349418cbdd0.gif)|
> fix(boilerplate): Demo podcast list screen initial render

- src/tools/__snapshots__/demo.test.ts.snap
- src/tools/demo.test.ts
- src/tools/demo.ts
@yulolimum discovered that `demo.removeNextLine` would remove the first line of a file, even if it didn't have a comment
Only check whether the previous line has a comment in `demo.removeNextLine` if it is not the first line of a file
> Fix `remove-demo` command from removing the first line of every file with `@demo remove-next-line`

- src/commands/new.ts
`--overwrite` was deleting the relative path of the project name, not the actual target directory. So if we had a different path from the present working directory, it wasn't actually deleting the target directory
Delete the target path, not a relative path of the project name
> Fix `--overwrite` in `new` command for not default target path

- package.json
- src/commands/cache.ts
- src/commands/new.ts
- src/tools/cache.ts
I noticed the CLI spinners were locking up when doing certain operations, so I made them async and parallelized them, and gained a little speed when restoring from a cache, plus not locking up the UI.
Before (no cache): 90s
After (no cache): 85s
Before (cached): 21s
After (cached): 19s
> Switching to async for copy/remove

- test/vanilla/ignite-new.test.ts
While we currently have `--use-cache` set to `false` by default for end users, we want to still have cache turned on for CI
> Add `--use-cache` flag to `new` command test

- boilerplate/ignite/templates/model/NAME.ts.ejs
Also fix the path to the newly-created model that's added to the RootStore
Creating a new model store on maverick uses an incorrect path for the RootStore leading to an error. This PR fixes the path the the RootStore and also the path to the newly-created model
> [maverick] Fix path of RootStore in model template

- src/commands/new.ts
Closes https://github.com/infinitered/ignite/issues/2141
> Handle relative paths and `~` character in `--target-path` of `new` command

- docs/Generators.md
The names of the icon files had "iOS-" before all of them. This fixes that and reorders to match the file tree.
> fix(docs): update docs for icon generator

- boilerplate/ignite/templates/navigator/NAMENavigator.tsx.ejs
- boilerplate/ignite/templates/screen/NAMEScreen.tsx.ejs
- docs/Generator-Templates.md
- src/tools/generators.ts
Per the discussion https://github.com/infinitered/ignite/discussions/2133, the users can now configure the case of the generated filenames. The default is still `pascalCaseName` but it is configurable to both `kebabCaseName` or `camelCaseName`
|Using Generator|`camelCaseName` in template|
|-|-|
|<img width="609" alt="CleanShot 2022-09-09 at 14 19 44@2x" src="https://user-images.githubusercontent.com/53795920/189436556-f4f3a6d6-a0bf-470d-8a15-845c99d051af.png">|<img width="575" alt="CleanShot 2022-09-09 at 13 46 45@2x" src="https://user-images.githubusercontent.com/53795920/189435963-3b20949b-41a7-45f8-b31d-e9ff2430e9d0.png">|
|List of screens|index.ts|
|<img width="200" alt="CleanShot 2022-09-09 at 14 15 19@2x" src="https://user-images.githubusercontent.com/53795920/189435987-6c2e9e47-2e15 …
> feat(generator): custom file names

- src/tools/validations.ts
Resolves: https://github.com/infinitered/ignite/issues/2145
Solves the issue by extracting existing `validateBundleIdentifier` validations into guard functions. Now, each guard can be used both by the enquirer prompt and the cli flag arg
> Add `validateProjectName` guards to prompt

- src/commands/new.ts
Resolves https://github.com/infinitered/ignite/issues/2163
Path can be undefined, so we want to wrap the `startsWith` call an optional chain to prevent undefined error
> fix(new): add optional chain to 'startsWith' in parsePath

- boilerplate/app/screens/DemoComponentsScreen/DrawerIconButton.tsx
Resolves https://github.com/infinitered/ignite/issues/2148
After
https://user-images.githubusercontent.com/37849890/190528683-202301ab-dbc4-4ee6-b7cd-9b5df5ae8edc.mp4
> fix(DrawerIconButton): animate pressible instead of view

- src/tools/cache.ts
```
npx ignite-cli new PizzaApp --use-cache
cd PizzaApp
yarn ios
```
Xcode would throw a build error. It would not throw a build error when the previous commands are run without the `--use-cache` flag.
This is fixed by copying the `ios/.xcode.env.local` file generated by Cocopods so it will point to the users Node binary
> fix(cache): copy .xcode.env.local

- src/commands/doctor.ts
- Closes #2198 
```
System
platform           darwin
arch               arm64
cpu                10 cores          Apple M1 Pro
directory          IgniteFlashList   /Users/fcalise/code/IgniteFlashList
JavaScript (and globally-installed packages)
node                16.14.2                              /Users/fcalise/.nvm/versions/node/v16.14.2/bin/node
npm                 8.5.0                                /Users/fcalise/.nvm/versions/node/v16.14.2/bin/npm
corepack          0.10.0
eas-cli           0.60.0
expo-cli          6.0.2
gatsby-cli        4.21.0
npm               8.5.0
yarn              1.22.19
yarn                1.22.19                              /Users/fcalise/.yarn/bin/yarn
create-expo-app   1.1.1
pnpm                -                                    not installed
expo …
```
> feat(doctor): added git version

- boilerplate/app/screens/DemoPodcastListScreen.tsx
- Closes #2197
- With the toggle getting rework, an old style didn't apply anymore and ended up hiding the text label - now fixed!
| Before   |      After      |
|----------|-------------|
| ![image](https://user-images.githubusercontent.com/374022/191839144-a5bf6c2f-b21e-4cc4-ac32-8d16f180b7c6.png) | ![image](https://user-images.githubusercontent.com/374022/191839262-7a6694a1-462d-43e8-b7e9-31eebba46f03.png) |
> Fix missing "Only Show Favorites" label on Demo Podcast screen

- boilerplate/bin/postInstall
- boilerplate/package.json
We have a couple open issues around calling jetifier post install being deprecated: 
- https://github.com/infinitered/ignite/issues/1978
- https://github.com/infinitered/ignite/issues/2208
Specifically #2208 has some good relevant articles.
It appears that `react-native run-android` now handles using `jetifier`, and most modules should have made the migration to AndroidX by now. 
I've run through the existing android workflows with this PR, and they work for me https://github.com/infinitered/ignite/issues/2135#issuecomment-1256562340
> Remove jetify from post install

- boilerplate/ios/Podfile
When running `pod install`, it generates `ios/.xcode.env.local` and it's throwing "Command PhaseScriptExecution failed with a nonzero exit code" error when trying to build. With this PR, the `./xcode.env.local` file should be deleted post install.
> fix: post pod install error

- src/tools/cache.ts
[ios/xcode.env.local is removed post](https://github.com/infinitered/ignite/pull/2214) `pod install`, so it's throwing an error when we try to copy a file that doesn't exist
> fix(cache): remove ios/xcode.env.local copy

- boilerplate/package.json
This is a fix for #2220
Users were experiencing a dependency error only when using npm. It was a dependency issue in reactotron-react-native. That has been fixed, and I verified updating reactotron-react-native from the current 5.0.2 to the new 5.0.3 fixes this issue.
> Fix: unable to resolve react

- boilerplate/app/components/Screen.tsx
There is an issue with the SafeAreaView from react-native-safe-area-context that causes the top inset to not be set on first render. So you see the content, then it re-renders and jumps down to it's final resting place. The fix is to not use SafeAreaView and use the useSafeAreaInsets hook instead.
This PR changes the Screen component to use the hook and apply the insets as screen padding if they are passed in, which fixes #2234.
https://user-images.githubusercontent.com/1761434/193369617-27e9df6b-5489-4ee2-bc25-2026ae9e1414.MP4
https://user-images.githubusercontent.com/1761434/193369658-838e3a9b-2469-43c5-b4c2-f47e6d5ae0f3.MP4
Ugly, but it shows it still works
> fix: 2234 - Remove SafeAreaView in favor of useSafeAreaInsets hook

- boilerplate/package.json
Resolves #2233. Implements fix for https://github.com/infinitered/ignite/pull/2237, but could not resolve merge conflict
> fix(package.json): pin "react-error-overlay": "6.0.9"

- docs/Guide.md
Addressing this, when reading the Getting Started Guide form Github at https://github.com/infinitered/ignite/blob/master/docs/Guide.md
> Fix typo (casing issue) inside Getting Started Guide causing a 404 when clicking on the Components link

- src/commands/remove-demo-markup.ts
- Closes #2241 
- Originally the `remove-demo-markup` command had to have dependencies installed to properly run prettier
- Substituted the local command for `npx prettier` so this can be run prior to installing deps
> fix(rdm): allow prettier formatting w/o deps installed

- boilerplate/ios/Podfile.lock
- Closes #2260 
- Podfile.lock to be in sync with package dependency versions
1. Observe `npx ignite-cli new Pizza app --yes` throws an exception during pod install on Mac OS
2. Checkout this branch
3. Run `npm link` from the ignite cli dir
4. Run Step 1 again and observe the error is gone
5. Run `npm unlink ignite-cli` from the ignite cli dir (you can discard any yarn lock changes)
> fix(boilerplate): Podfile.lock update

- boilerplate/metro.config.js
- For expo projects, get default metro config from @expo package
> fix: use expo default metro config

- boilerplate/android/gradle.properties
- boilerplate/ios/Podfile.properties.json
I was trying to publish the app with expo new EAS, and was hitting this issue:
```
sergio@leviathan MyAppProject % yarn eas update                                                                                                                                                                   [4/10/22 | 11:32:44]
yarn run v1.22.11
warning ../package.json: No license field
$ /Users/sergio/Developer/MyAppProject/node_modules/.bin/eas update
Found eas-cli in your project dependencies.
It's recommended to use the "cli.version" field in eas.json to enforce the eas-cli version for your project.
Learn more: https://github.com/expo/eas-cli#enforcing-eas-cli-version-for-your-project
Found eas-cli in your project dependencies.
It's recommended to use the "cli.version" field in eas.json to enforce …
```
> Fix expo-cli hermes sanity checks on publish

- boilerplate/ios/Podfile.lock
- boilerplate/package.json
- Closes #2280 
`expo-linear-gradient` was left over from an old pre Maverick component that we don't have anymore.
> vendor: remove expo-linear-gradient

- boilerplate/ignite/templates/model/NAME.ts.ejs
- test/vanilla/ignite-generate.test.ts
- Closes #2218
- Enhances model generator to include withSetPropAction helper
- Updated test for model gen
```
import { Instance, SnapshotIn, SnapshotOut, types } from "mobx-state-tree"
import { withSetPropAction } from "./helpers/withSetPropAction"
/**
* Model description here for TypeScript hints.
*/
export const Test4Model = types
.model("Test4")
.props({})
.actions(withSetPropAction)
.views((self) => ({})) // eslint-disable-line @typescript-eslint/no-unused-vars
.actions((self) => ({})) // eslint-disable-line @typescript-eslint/no-unused-vars
export interface Test4 extends Instance<typeof Test4Model> {}
export interface Test4SnapshotOut extends SnapshotOut<typeof Test4Model> {}
export interface Test4SnapshotIn extends SnapshotIn<typeof Test4Model> {}
export const …
```
> fix(generators): added withSetPropAction to model gen

- README.md
- src/commands/issue.ts
- Closes #932 
- Adds new `npx ignite-cli issue "my bug title here"` command
- Opens browser window to `https://github.com/infinitered/ignite/issue/new` with title prefilled and prefilled issue body with `npx ignite doctor` output for issue reporter to easily paste
- Fixes title for user if they forget to double quote the title string
Tested
> feat(issue-cmd): added new GH issue command

- boilerplate/app/screens/DemoShowroomScreen/demos/DemoTextField.tsx
- [✅] `yarn test` **jest** tests pass with new tests, if relevant
- [✅] `README.md` has been updated with your changes, if relevant
In the DemoShowroomScreen, in the DemoTextField, in the Left and Right Accessory it says "This props". Clearly, it was intended to say "This prop" as it is referring to an individual prop.
> Fix typo in DemoTextField from "props" to "prop"

- boilerplate/ios/Podfile.lock
- Closes #2301
- For some reason updating the Podfile.lock missed the `hermes-engine` version, causing pod install issues unless `npx pod-install` was run to fix things
The `new` command hits our `pod install` from `bin/postInstall` first which ends up bombing if things aren't correct. We should do one of the following:
1. Copy the guts of `npx pod-install` into our `postInstall` script to automagically fix things
2. Skip our initial pod install and let `npx pod-install` which we already run during `new` take care of business for igniting new apps (see #2284)
3. Remove `pod install` from `postInstall` in favor of `npx pod-install`
> fix(boilerplate): podfile lock hermes version mismatch

- src/commands/new.ts
- Moves renaming of the react-native application to before dependencies are installed
- A bug was masked with `npx pod-install` being run after the rename that helped fix things, so now that we moved it to postInstall, rename must occur first
- This is only relevant to `yarn ios`
> fix(cli): move rename before install deps

- boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
- Closes #2274 
- Fixes an issue where if the user was dragging the drawer open and let's go without meeting the threshold, the icon could get stuck in a mid animation state
- The same could occur when fully open and beginning to drag it closed but release early where it would remain open
| Before | After |
| ------- | ------- |
| <img width="300" src="https://user-images.githubusercontent.com/374022/202740411-721d77b1-8b62-422e-96fa-a73ef4fc4654.gif" /> | <img width="300" src="https://user-images.githubusercontent.com/374022/202740630-e7c2a75e-03ab-4db7-9305-4cf796052fdd.gif" /> |
> fix(demo): fixed stuck drawer icon when releasing drag near 50%

- boilerplate/app/components/Toggle.tsx
- boilerplate/app/screens/DemoShowroomScreen/demos/DemoToggle.tsx
- docs/Components-Toggle.md
@robinheinze reported that the app she is working on has a weird screen offset when the Toggle is used. The reason for that is this issue: https://github.com/software-mansion/react-native-reanimated/issues/3368
The Toggle switch-variant uses reanimated's `FadeIn`. This was added to give the switch time to calculate the knob width to determine its position along the track. This was needed in case the component overrides specified a percentage width for the knob. 
I think it's reasonable to only allow point values for knob width customization. This cleans up the switch code and remove the need for measuring, which in effect, removes the need for the FadeIn.
This PR also separates the Types for the different Toggle variants for better prop hover descriptions and prop matches. 
This PR also …
> Simplifies Toggle's switch-variant to not require measuring logic. Adds icon customization to Toggle's checkbox-variant.

- boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
- On super large displays, the DrawerLayout for web was still covering most of the entire window provided you weren't working with a maximized window. It now is 1/3 of the screen like a normal nav area on web
> fix(boilerplate): updated web drawer layout width

- boilerplate/app/screens/DemoPodcastListScreen.tsx
While writing up a recipe for adding Maestro to an Ignite app, I noticed that we added an accessibility label to the android Podcast Card but not for iOS. This is helpful for running e2e tests.
> fix: adds accessibility label for ios to match android

- boilerplate/app/navigators/DemoNavigator.tsx
- boilerplate/app/screens/LoginScreen.tsx
I have added size property for icons that exist in the tab bar in order to be shown when running expo:web. 
PR for this issue : https://github.com/infinitered/ignite/issues/2357
>  fix(icons): add size to every icon in the tab navigator in order to appear in web navigator using expo:web command

- boilerplate/babel.config.js
- boilerplate/ios/Podfile.lock
- boilerplate/package.json
Running `yarn expo:web` was causing the following fatal error in the browser. This PR adds a babel plugin to handle the reanimated on web.
```
log.js:24 [HMR] Waiting for update signal from WDS...
utils.ts:24 Uncaught Error: Module build failed (from ./node_modules/@expo/webpack-config/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/joshuayoes/Code/ignite/boilerplate/node_modules/react-native-reanimated/lib/index.web.js: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
[0m [90m 4 |[39m [36mexport[39m [33m*[39m [36mfrom[39m [32m'./reanimated1'[39m[33m;[39m[0m
[0m [90m 5 |[39m [36mexport[39m [33m*[39m [36mfrom[39m [32m'./reanimated2'[39m[33m;[39m[0m
[0m[31m[1m>[22m[39m[90m 6 |[39m [36mexport[39m …
```
> Fix `yarn expo:web`

- boilerplate/app/navigators/navigationUtilities.ts
The previous version was detected as invalid with a nightly version of TS (5.1), you can see the reported error [here](https://github.com/microsoft/TypeScript/issues/53122#issuecomment-1457229048)
> Fixed a cast of arguments passed to `navigate`

- boilerplate/app/models/helpers/setupRootStore.ts
- boilerplate/app/navigators/AppNavigator.tsx
- boilerplate/app/navigators/navigationUtilities.ts
- boilerplate/app/services/reactotron/reactotron.ts
- boilerplate/app/utils/crashReporting.ts
- boilerplate/app/utils/storage/storage.ts
- boilerplate/app/utils/useHeader.tsx
This PR strongly types our `navigationRef` with our actual app stack types, and updates the `navigate` utility function to have the correct type. 
This also addresses the typescript 5.1 error described in this PR: https://github.com/infinitered/ignite/pull/2393
Additionally, this PR also removes explicit `any` type usages for Ignite 🥳
> Strongly type navigationRef, update navigate() utility args type

- boilerplate/app/navigators/AppNavigator.tsx
- boilerplate/app/navigators/DemoNavigator.tsx
- boilerplate/ignite/templates/screen/NAMEScreen.tsx.ejs
- test/vanilla/ignite-new.test.ts
- Fixes DemoNavigator tab icons all being set to component due to #2361 
- Fixes Screen generator with incorrect return Type
- Opt for NativeStackScreenProps over StackScreenProps for consistency
- Proper generic param for route
- Updates generator to automate putting screen params in right spots
- Take care of adding to AppStackParamList
- and `<Stack.Screen />`  (as long as `--skip-index-file` is not passed)
> feat(generators): enhanced screen gen

- boilerplate/app/navigators/AppNavigator.tsx
This uses the colors of the app to set the background
color of the software navigation bar buttons for Android.
On Android, the navigation bar background color can be set to match the background color of the app. This PR uses the background color from `colors.background` and uses it as the background color of the navigation bar software buttons.
> Android Only - Navigation Bar Background Color

- boilerplate/app/screens/ErrorScreen/ErrorBoundary.tsx
Co-authored-by: yulolimum <yulian@infinite.red>
When you use the `ErrorBoundary` with the `catchErrors` prop set to `never`, this will cause the application to infinitely render. This is due to setting the `error` and `errorInfo` state, but not checking whether catch is enabled. This causes the render function to re-render the children that will then trigger another exception, the `componentShouldUpdate` passes because it is a new error, and start the process again.
Special thanks to @yulolimum for helping me come up with a simple solution.
> Fix: Error Boundary Infinite Loop

- boilerplate/app/devtools/ReactotronConfig.ts
Reactotron's `trackGlobalError` core plugin already listens to errors reported LogBox, so this PR removes double reporting from Reactotron error.
> fix(devtools): remove reactotron error swap

- boilerplate/app/screens/LoginScreen.tsx
The current LoginScreen has two separate useEffect calls: one for form pre-fill and one for cleanup. I found the separation confusing.
In this PR, I've merged these calls to make their relationship clearer. Maybe this change could help future users navigate the boilerplate a little bit easier?
Cheers,
- gaida
> (boilerplate): Merge useEffect calls in LoginScreen for clarity

- boilerplate/app.config.ts
- boilerplate/package.json
- boilerplate/plugins/withSplashScreen.ts
- boilerplate/tsconfig.json
- docs/Expo-and-Ignite.md
- docs/Folder-Structure.md
- docs/Guide.md
- Adds scaffolding for writing TypeScript Expo Config Plugins (via `ts-node`) within your project without needing to transpile to JS
- Adds documented Config Plugin, `withSplashScreen`, to address Android 12 issues with `expo-splash-screen`
- Updates some documentation related to Expo and Ignite
> feat(boilerplate): config plugin scaffolding

- boilerplate/app/models/helpers/setupRootStore.ts
Fixes the following issue:
[mobx-state-tree] Error while converting `null` to `RootStore`: value `null` is not assignable to type: `RootStore` (Value is not a plain object).
> Fix: Error while converting `null` to `RootStore`

- src/commands/new.ts
The `cd` output on a new project uses the `projectName`, but you can override the default `targetPath`, making that command incorrect.  This changes to use the `targetPath` so you can copy/paste if you changed the path and it will work
> Correct cd command when targetPath has changed

- boilerplate/ios/Podfile.lock
- boilerplate/package.json
Fixes #2500.
Expo bumped `@expo/webpack-config` to require Expo 49 in this PR, which broke our tests. https://github.com/expo/expo-cli/pull/4747
This freezes the version of `@expo/webpack-config` to [18.1.2](https://www.npmjs.com/package/@expo/webpack-config/v/18.1.2) to bring it back to Expo 48.
Note that in Ignite v9, `@expo/webpack-config` will be entirely removed (we'll be using Metro on web), so this is just a temporary patch.
> Specifies version of @expo/webpack-config to avoid dependency failure

- boilerplate/app/i18n/fr.ts
- boilerplate/app/i18n/i18n.ts
- test/vanilla/__snapshots__/ignite-remove-demo.test.ts.snap
I am writing slides for a talk about the power of GitHub copilot. 
One feature is the translation
https://davidl.fr/courses/copilot.html#89
I needed an example 
So let's ship a real feature 🚀 
here is the prompt I used (and I double-checked if it makes sense in 🇫🇷)
> transform this translation file to `fr.ts`
> translate the text to french, except for the property
> feat(boilerplate): add french to i18n

- boilerplate/app/utils/formatDate.ts
- boilerplate/package.json
Tests failed on my local machine, but the failure seems unrelated to the content I changed in this PR.
Because react-native doesn’t tree-shake, importing things from `date-fns` bundles ALL of the `date-fns` library, which is quite heavy.
Changing from the syntax `import { Locale, format, parseISO } from "date-fns”` to importing them individually like:
```ts
import type Locale from "date-fns/locale"
import format from "date-fns/format"
import parseISO from "date-fns/parseISO"
```
Saves us 0.41 megabytes in the production bundle size of an ignited app. That’s a HUGE savings for such a small syntax change.
I also added scripts to the boilerplate to use `react-native-bundle-visualizer` through `npx` (which is how i determined this bundle filesize savings).
Before this PR: `yarn …
> fix: `date-fns` import syntax adding almost ½ megabyte to production bundle sizes

- src/commands/new.ts
This is pulling out a commit from #2513 so that we can get this fix in for the new architecture with that PR stalled for now.
`@react-native-async-storage/async-storage` requires ios 13.4 as a minimum deployment target when using the new architecture.
> fix: ios compiling issue when the user specifies the new architecture

- boilerplate/app/i18n/i18n.ts
`Localization.isRTL` is deprecated.
The deprecation notice for `expo-localization`'s `Localization.isRTL` is the synchronous function call `Localization.getLocales()`. This gets an array of the user’s preferred languages with the first element in the array being their preferred language. This array object contains everything we need to determine their `i18n.locale` and if the language is `rtl` or `ltr`.
As you can see in this video, I'm switching back and forth between English and Arabic (with a little debug notice alert that is not included in this PR, just so we can see what's going on) and the `isRTL` functionality remains the same.
Debug code for my little alert:
```tsx
Alert.alert(
"Preferred Languages:",
locales.map((l) => `${l.languageTag} (${l.textDirection})`).join(", "),
)
```
> fix: `Localization.isRTL` is deprecated.

- boilerplate/metro.config.js
- As reported on #2446, the `metro.config.js` was not baselined with the Expo default config
- https://github.com/infinitered/ignite/pull/2446#issuecomment-1761352677
> fix(boilerplate): inherit default metro from expo

- boilerplate/jest.config.js
- Closes #2490
- Jest config needed to know about the TS path aliases to utilize them within the tests
You can now import like so without jest breaking:
```
import { delay } from "app/utils/delay"
```
> fix(jest): map ts paths

- boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
Fix demo screen : drawer opens unexpectedly on mount due to route.params check always truthy inside useEffect
close #2535
> demo screen fix drawer opened by default

- docs/Generators.md
- src/commands/new.ts
- Closes #2253
- This attempts to autocorrect an EOL issue with the generator template files by doing the following:
- Checks to see if running on Windows
- Looks for the `unix2dos` cli utility
- If found, applies this to each of the template files found from the boilerplate
- If not found or application fails, will output a warning at the end of terminal output to check the EOL in templates
- Added extra debug logging
- Updated documentation to make note about this issue with Windows
This was manually tested by doing the following:
1. Clone `ignite-cli` project on a Windows machine
2. Convert `boilerplate\ignite\templates\**\*.ts*.ejs` files EOL to LF on purpose (likely CRLF after cloning)
3. Generate a new Pizza App locally, ie:
`node bin/ignite new PizzaWin --overwrite --debug …
> fix(cli): win EOL conversion for gen templates

- boilerplate/bunfig.toml
- src/commands/new.ts
- Related to #2522
- `bun` version 1.0.10 no longer has any peer dep install issues, so removing this `bunfig.toml` and related cli `new.ts` code (for removal when not utilizing `bun` as the package manager) for easier maintenance
> chore: remove bunfig disabling peer install

- boilerplate/app.json
- boilerplate/package.json
- src/commands/new.ts
- src/tools/expoGoCompatibility.ts
- add ignite version in `app.json` (this needs to become automated if possible)
- latest expo version has go compatible with rn 72.6 so we bump to that
> chore: update rn version, expo compat

- src/commands/new.ts
- src/commands/remove-demo-markup.ts
- src/tools/demo.ts
- @jamonholmgren was looking to remove demo markup automatically if keeping the demo in place
- turns out `remove-demo-markup` never removed `remove-file` comments but now it does :D
> fix(cli): remove demo markup if keeping demo files

- src/commands/new.ts
- Closes #2559 
- `pnpm` had some troubles and requires additional config
> fix(cli): pnpm npmrc

- boilerplate/package.json
- Closes #2564 until TS Node fixes their issue with TypeScript 5.3.2
- We know TS 5.2.2 worked fine as that's the version we tested Ignite 9 on for months
> fix(boilerplate): TS version lock

- src/commands/new.ts
- src/tools/demo.ts
- Closes #2544
- If the user decides to remove the demo application, there are a handful of dependencies that we can clean up out of the way that go unused with just the basic Welcome screen
> feat(cli): remove unused deps upon demo removal

- boilerplate/package.json
- Adds `expo-dev-client` to boilerplate deps to get Expo's dev menu, build ready for EAS dev client builds etc
> fix(boilerplate): add expo-dev-client

- boilerplate/package.json
- Enables `eslint-plugin-reactotron` to watch for console.tron.x calls not wrapped by `__DEV__` conditionals
> fix(boilerplate): set up eslint-plugin-reactotron

- boilerplate/package.json
- Updates `ts-node` to get the bug fix where `extends` was broken, therefore locking us to 5.2.2 version of `typescript`
- Updates `typescript` to 5.3.2
- Locks `react-native-drawer-layout` to alpha1 because 3 is causing some issues
> fix(boilerplate): ts-node version

- boilerplate/app/navigators/navigationUtilities.ts
`BackButton` is only on android, so instead of checking if the platform isn't iOS, check that it isn't android
Fixes #2596
> fixes #2596 back button error on web

- boilerplate/app/components/AutoImage.tsx
Small fix on a broken link: 
Prev:
https://github.com/infinitered/ignite/blob/master/docs/Components-AutoImage.md
Now:
https://github.com/infinitered/ignite/blob/master/docs/boilerplate/components/AutoImage.md
> Fix documentation link on AutoImage

- boilerplate/app/components/Button.tsx
- boilerplate/app/screens/DemoShowroomScreen/demos/DemoButton.tsx
- docs/boilerplate/components/Button.md
I was copying Ignite's `Button` component into my own codebase and wanted to have a disabled `Button` visually indicated with some custom styles. This change was really helpful for me, so I wanted to propose it to y'all while I wait for my CI to pass haha.
No worries if you're not interested, I imagine folks could style this from outside by syncing up some conditional styles with any conditions they use to set the `disabled` prop, but I kind of like that this reads the `disabled` prop directly at author-time and behaves as expected.
Let me know what ya think. Happy to rework anything you'd like. Thanks one way or another!
I had one set of test failures, but I don't think they're related to this change. I get the same results on the `master` branch in my fork.
<details>
Output: 
```sh
in …
```
> feat: add props for disabled styles in Button component

- test/vanilla/ignite-new.test.ts
If you have your `git diff` configured with an external diff tool, the tests will not pass because it relies on the output of the internal `git diff` command. This updates  the command lines arguments for consistency to force `git` to use the internal diff tool always for the spec. (Docs: https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---no-ext-diff)
> feat(only-use-internal-diff)

- src/tools/expoGoCompatibility.ts
- Closes #2600 
- Removes `expo-dev-client` from the package.json in the spot where we look to revert later dependencies to the Expo Go compatible ones
```
ignite/bin/ignite new ignite-dev-client --yes
cd ignite-dev-client
cat package.json|grep "expo-dev-client"
yarn ios
```
> fix(cli): remove expo-dev-client for Expo Go

- docs/cli/Ignite-CLI.md
- src/commands/new.ts
- test/vanilla/ignite-new.test.ts
- Adds an extra step in the decision tree for `ignite-cli new`: `Do you want to use Expo?`
- Adds `cng` workflow type to replace `prebuild`, to match [Expo's naming](https://docs.expo.dev/workflow/continuous-native-generation/). Deprecated `prebuild` for potential future removal. 
Note: References new Ignite Cookbook recipe from https://github.com/infinitered/ignite-cookbook/pull/116
> feat(cli): split expo workflow decision tree, use 'cng' instead of 'prebuild'

- boilerplate/app/utils/useSafeAreaInsetsStyle.ts
Simple one updating the docs link inside `useSafeAreaInsetsStyle.ts`.
|  Before 😢 | After 🙂 |
| --|--|
| ![before](https://github.com/infinitered/ignite/assets/47733004/31ab5917-be7e-4eba-85a0-2720a7bea147) | ![after](https://github.com/infinitered/ignite/assets/47733004/d0dc2347-a883-42ad-8bdf-af2ee72575a0) |
> Fixed doc link inside `useSafeAreaInsetsStyle`

- boilerplate/app/models/helpers/useStores.ts
`useInitialRootStore` callback should be optional for cases where the callback isn't needed. 
Discovered after Igniting new project for use with Expo Router: 
```
const { rehydrated } = useInitialRootStore() // TS error
if (!rehydrated) {
return null
}
```
> fix(typescript): useInitialRootStore callback should be optional

- boilerplate/.maestro/FavoritePodcast.yaml
Demo app only returns 10 most recent podcasts from the API call. 
Our Maestro test was failing because it was searching for a podcast episode further back, which wasn't displayed. 
Rather than hardcoding an episode title, which would go out-of-date every few months, I updated the test to scroll down a bit and dynamically grab a visible episode.
> fix(maestro): update maestro test dynamically select a podcast

- boilerplate/test/setup.ts
This line was breaking potential React Native Testing Library support, and isn't needed for the original boilerplate test anymore. 
Bye, felicia!
> fix(jest): remove jest.useFakeTimers in setup

- boilerplate/app/i18n/i18n.ts
On certain older platforms, the `systemLocale` returned by `expo-localization` might be invalid, leading to a crash when `systemLocale.languageTag` or `systemLocale.textDirection` are referenced. This PR just adds optional chaining for these references and defaults to `en-US` if there is a problem.
Also changed the default locale from `en` to `en-US` to fix an Apple TV issue, but this may have already been dealt with in #2622 .
Reviewers: if desired, we could add `console.warn()` calls if this condition is encountered, but `expo-localization` is already writing Android logcats if there are errors.
> fix (localization): Guard against i18n errors for older Android platforms

- docs/boilerplate/App.tsx.md
- docs/boilerplate/Boilerplate.md
- docs/boilerplate/android.md
- docs/boilerplate/app.json.md
- docs/boilerplate/app/_category_.json
- docs/boilerplate/app/app.md
- docs/boilerplate/app/devtools/Devtools.md
- docs/boilerplate/app/devtools/_category_.json
- docs/boilerplate/assets.md
- docs/boilerplate/eas.json.md
- docs/boilerplate/ignite.md
- docs/boilerplate/ignite/Ignite.md
- docs/boilerplate/ios.md
- docs/boilerplate/maestro.md
- docs/boilerplate/plugins/Plugins.md
- docs/boilerplate/plugins/_category_.json
- docs/boilerplate/plugins/withSplashScreen.md
- docs/boilerplate/test/Test.md
- docs/boilerplate/test/_category_.json
- Updated Boilerplate.md to reflect current project structure
- Added docs for several files / directories. Some may need more detail, but open to opinions!
- Updated ordering to reflect alphabetical filesystem, for consistency (open to opinions here)
A few files that are included in a new project, but we don't currently have docs for:
- babel.config.js
- jest.config.js
- metro.config.js
- react-native.config.js
- tsconfig.json 
- package.json
- README
Open to opinions on whether we want to exhaustively document every file or not. (do any of these files contain customizations that are worth documenting?)
> feat(docs): Add docs for ignite boilerplate files

- boilerplate/jest.config.js
- Closes #2605
- Better RNTL support out of box
- testEnvironment `jsdom` should only be used for web (which although we support, isn't our main target)
> fix(boilerplate): jest.config.js remove jsdom test env

- boilerplate/package.json
- docs/boilerplate/android.md
- docs/boilerplate/ios.md
- Removes `yarn prebuild` script in favor of just using the clean one, no real need for it, and likely will run into more problems using it than without
> fix(boilerplate): remove `yarn prebuild` script in favor of clean

- boilerplate/app/components/Toggle.tsx
- Closes #2637
- Replaces usage of `marginStart` for where to put the knob in favor of `translateX`
https://github.com/infinitered/ignite/assets/374022/4bfa3b07-f3c9-442e-9603-57f2272b49f3
> fix(components): switch animation slide on web

- boilerplate/App.tsx
- boilerplate/package.json
- Fixes an issue where hot reloading doesn't work on web due to using metro bundler (to prep for expo-router), which requires an explicit import to enable it
- Related issue at Expo: https://github.com/expo/expo/issues/23104#issuecomment-1689566248
- Discussed in partner channel, it cannot be included by default because it breaks webpack support
> fix(boilerplate): web hmr fixes

- src/commands/new.ts
- Fixes an issue found by @lindboe that `xcode.env.local` gets a temporary ref to npm/yarn executables when prebuild is run by an alias over the `npx` variation
> fix(cli): prebuild via npx over alias

- README.md
Helps address #2663. 
More updates needed, but this is a nice start.
> Clean up README getting started a bit

- src/commands/generate/splash-screen.ts
- [ x ] `yarn test` **jest** tests pass with new tests, if relevant
- [ x ] `yarn lint` **eslint** checks pass with new code, if relevant
- [ x ] `yarn format:check` **prettier** checks pass with new code, if relevant
- [ x ] `README.md` (or relevant documentation) has been updated with your changes
Update the output of a splash screen generator to notify users they should run prebuild:clean command to ensure their changes are reflected.
> add prebuild:clean to splash screen gen output

- boilerplate/app/app.tsx
- boilerplate/metro.config.js
This tweaks the metro config to add support for .cjs so we support Firebase.js out of the box with no other config changes.
Also adds some comments for inline requires.
> fix(metro): Add support for cjs extension in metro.config.js

- boilerplate/app/screens/DemoCommunityScreen.tsx
This PR fixes a small alignment issue on the DemoCommunityScreen where icons are not vertically centered in their rows. Tested in Expo Go, iOS 17.5 , with the [Expo 51 patch](https://github.com/infinitered/ignite/pull/2683) applied.
| Before | After|
|-|-|
| <img width=250 src="https://github.com/infinitered/ignite/assets/7883508/0144bf52-e038-49f5-8c5b-86891afda8f3" /> | <img width=250 src="https://github.com/infinitered/ignite/assets/7883508/85450a7b-027c-42b9-8197-690214467ce6" /> |
> Fix icon alignment on DemoCommunityScreen

- src/commands/new.ts
> fix(cli): better support for yarn 2+

- boilerplate/app/navigators/navigationUtilities.ts
On the dev env, if you try to start the app from a deep link because the navigation persists, it will get ignored by the navigation
> fix(boilerplate): fix deep link not working with navigation persist

- boilerplate/app/i18n/i18n.ts
- boilerplate/app/i18n/jp.ts
- docs/boilerplate/app/i18n/Internationalization.md
- test/vanilla/__snapshots__/ignite-remove-demo.test.ts.snap
Hi all! This PR is to add another language (Japanese) to the boilerplate. I have translated all the texts under the translation object. I haven't gone any further than the i18n files for the sake of the scope of this PR, but it might be beneficial to translate the descriptions under component's demo ([example](https://github.com/infinitered/ignite/blob/e883593ffc1fb3b4349330dc477ff0296954b3cc/boilerplate/app/screens/DemoShowroomScreen/demos/DemoCard.tsx#L11)) in the future. I can try to hook them up to i18n file after this PR.
> feature: add Japanese translation to boilerplate

- boilerplate/.maestro/Login.yaml
- boilerplate/app/i18n/ar.ts
- boilerplate/app/i18n/en.ts
- boilerplate/app/i18n/fr.ts
- boilerplate/app/i18n/ko.ts
- boilerplate/app/screens/LoginScreen.tsx
- Changes `Sign In` copy to `Log In` so it's consistent with the screen filename, `Login.tsx`
- When viewing `Sign In` running the app your first instinct is to cmd+p for `Signin.tsx` but it doesn't exist
- We might need to check the translations for ko, ar and fr - but I guess the filenames are in English so maybe doesn't make a difference
> fix(log-in): sign in -> log in for consistency with filename

- boilerplate/babel.config.js
- boilerplate/package.json
Since my upgrade to Expo 51.0.17 my EAS local build for iOS didn't work anymore. I had to change the entrypoint in the package.json. A brand new Expo project had it configured that way, instead of the old reference to node_modules
Along the way I saw the babel-proposal being incorporated into babel, so changed the devDependencies.
> Fix entrypoint for SDK 51. Update babel transforms

- boilerplate/package.json
As per #2712 , patch-package is a bit too old. I also noticed it was fixed to the specific version. I don't see a big reason for this as it is not the type of project that would break api in minor version updates so I've let it be updateable.
> fix(boilerplate): bump patch-package version

- boilerplate/app/i18n/jp.ts
- Updates the `jp` language string file signIn key to logIn
> fix(boilerplate): refactor signIn key to logIn

- src/commands/new.ts
- src/tools/demo.ts
While testing fixes to component testing config, I found that a project generated with `ignite-cli@latest` and `--removeDemo` would have an error when installing a new dependency, because there was a patch for `react-native-drawer-layout`, which had been removed from the project:
```
patch-package 8.0.0
Applying patches...
Error: Patch file found for package react-native-drawer-layout which is not present at node_modules/react-native-drawer-layout
---
```
So now, in addition to removing demo-only dependencies, we'll remove any matching patch files from the project.
> Remove demo patches along with dependencies

- docs/cli/Ignite-CLI.md
- docs/concept/MobX-State-Tree.md
- src/commands/new.ts
- test/vanilla/ignite-new-expo-router.test.ts
- Updates `--mst` to `--state=mst|none` with default of `mst`
- Refactors remove-mst-markup/code command to read same as remove demo block
> fix(cli): reworks --mst to --state=mst

- boilerplate/app/app.tsx
- boilerplate/app/utils/gestureHandler.native.ts
- boilerplate/app/utils/gestureHandler.ts
- Removes unnecessary `<GestureHandlerRootView />` from `app.tsx`
- This wrapper is only necessary if specifically using the Gesture Handler API (which the demo application does not)
- Coached by @satya164 in this [Twitter thread](https://x.com/satya164/status/1821493278245548051)
> fix(boilerplate): remove GestureHandlerRootView

- boilerplate/package.json
- boilerplate/patches/@expo+metro-runtime+3.2.2.patch
Updates the RN version in use to fix an issue that was preventing all Android builds: https://github.com/expo/expo/issues/31005.
Once I upgraded, though, I ran into another issue: the JS bundle fails to load with:
```
iOS Bundling failed 3255ms node_modules/expo/AppEntry.js (1892 modules)
Unable to resolve "react-native/Libraries/Utilities/DevLoadingView" from "node_modules/@expo/metro-runtime/build/LoadingView.native.js"
```
This is in a conditional in LoadingView.native.js that should load the correct one, and does, so this appears to be an issue with conditional requires. I'm not sure how to fix that underlying issue just yet, so patching for now.
Will file a ticket to follow up with better long-term fixes, including potentially pinning the template version in use.
> [v10] Fix expo template with RN upgrade

- boilerplate/app/screens/WelcomeScreen.tsx
- boilerplate/app/theme/styles.ts
- boilerplate/app/utils/useHeader.tsx
- test/vanilla/__snapshots__/ignite-remove-demo.test.ts.snap
To fix Android build issue, depends on https://github.com/infinitered/ignite/pull/2745.
Android and iOS were both jumping when navigating from the Welcome screen to the Demo Showroom screen (although in different directions, and Android was less severe).
I found this issue was prevented when we use the `StatusBar` component on the WelcomeScreen as well as DemoShowroom, so converted WelcomeScreen to use the built-in `Screen` component, which includes `StatusBar`.
However, that raised another issue: when navigating from the Login screen to the Welcome screen, the "fixed" `Screen` component on Welcome screen would render the wrong height; it would be slightly too tall.
The `useHeader` hook was using useEffect, which means that header height wouldn't be set until the second render, so when …
> Fix screen jump from Welcome screen to Demo screen

- boilerplate/app/i18n/demo-ja.ts
- boilerplate/app/i18n/i18n.ts
- boilerplate/app/i18n/ja.ts
- test/vanilla/__snapshots__/ignite-remove-demo.test.ts.snap
I'm so sorry I just realized the locale code for Japanese was `ja` while the shortened name of the language itself is `jp`🙏 This PR fixes the locale applied in the `i18n.ts` to fix the bug that jp language isn't recognized by i18n. I sware this is the final PR for the series of translations
> fix: change locale code for Japanese to ja

- .gitignore
- boilerplate/.gitignore
Add the `.yarn` cache folder within the root `.gitignore` and bootstrap's `.gitignore`, to avoid the potential of git adding these files to the repo.
> Add yarn cache to gitignore

- boilerplate/package.json
- Closes #2747
- Must test with `--packager=npm` and see a successful project generates (currently CI doesn't test this)
> fix(boilerplate): react-test-renderer devDep for RNTL + npm

- boilerplate/app/devtools/ReactotronConfig.ts
- boilerplate/src/app/_layout.tsx
- src/commands/new.ts
- src/tools/dependencies.ts
- As described by @markrickert, when using the prompts to set the following scenario (yarn, no demo, git repo, install deps, no MST, expo router, new arch) - MST was not removed properly
- With proper MST removal, the `lint` step failed inside of the ReactotronConfig leaving in `clear` from `@/utils/storage` which we were no longer needing, so I added the proper MST removal directives around that)
- Also occurs in the main `_layout` file when in the `expo-router` scenario
- When opting into the new architecture, some libraries need to be updated (for example `react-native-mmkv` from 2 to 3), the `new` command has updates for this
> fix(cli): improper MST removal when using CLI prompt, new arch compat

- boilerplate/app/app.tsx
- boilerplate/app/i18n/i18n.ts
- boilerplate/app/i18n/translate.ts
- boilerplate/app/models/Episode.test.ts
- boilerplate/app/utils/formatDate.ts
- boilerplate/package.json
While updating date-fns to v4, I ran into a few issues with language switching.
The previous way we had of loading languages with i18n-js doesn't work with i18next. `hasOwnProperty` does not work with `i18n.languages`, as it's an array. `i18n.languages` is also empty on init, as it's only an array of the currently configured languages to use (preferred, then fallback), not all supported languages.
Instead I created a function to pick the first locale from device locales that we support, and configure i18n with that.
This we fix by referring to i18n from the library, we don't need to store it in a variable in `i18n.ts`.
Here I just needed to update some import paths, but while I was there, I also added support for more of our supported locales, and conditionally load only the locale …
> Fix language switching and update date-fns to v4

- boilerplate/src/app/_layout.tsx
- Fixes an issue in v10 where i18next wasn't initialized in an Expo Router project
> fix(expo-router): initialize i18n

- .gitignore
- boilerplate/test/setup.ts
- test/_test-helpers.ts
- test/vanilla/ignite-new-expo-router.test.ts
- test/vanilla/ignite-new.test.ts
We needed `ignite new` output to be printed by failing tests when developing; otherwise you have to generate the app at least twice to see why a given test is failing.
The way to get jest to print the output we want is by throwing it when the command fails. However, when we tried this, we found it was possible for the output to be so large for certain errors that it can hit node’s max buffer size, which *also* means you don’t get to view the error (and get a red herring error on top of that.)
That means we should stream the output with `spawn`, to manage output that's too large. In this PR, we stream it to a file so there’s always at least a partial record of the output, even if we fail to be able to print it to the console.
Existing tests expect a string of command output to test …
> Stream test command output to file for debugging purposes

- boilerplate/app/components/Icon.tsx
I noticed the icons on the community screen weren't updating for dark mode.
Color isn't explicitly set by those icons, but it matches text color in our design system by default.
Here I explicitly assign a default color for icons, and make sure it updates with the theme.
| Before | After |
|--------|--------|
|  <img src="https://github.com/user-attachments/assets/bf440a93-e4ad-4be8-95c8-908c051540f3" width=250 /> | <img src="https://github.com/user-attachments/assets/f4546613-bbf9-455c-8c99-89999b3363c9" width=250 />
> Make icon default color explicit, and respond to dark mode

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates Ignite's PR template with:
* Add a new check to enforce maintainers to test features
* Add new section for before/after screenshots
> Update PR description to add feature checks and possible screenshots/videos

- boilerplate/app/utils/useAppTheme.ts
> chore: v10 typo: `setImperativeThemeing` becomes `setImperativeTheming`

- boilerplate/app/components/Toggle/Checkbox.tsx
- boilerplate/app/components/Toggle/Switch.tsx
- boilerplate/app/screens/DemoShowroomScreen/demos/DemoToggle.tsx
This PR addresses two issues: 
* In the Demo for the Toggle Showcase, two sections are not displayed properly (statuses & style). I added `$styles.flexWrap` to fix it.
* Then the custom properties of `Checkbox` and `Switch` were not pass down to the `CheckboxInput` and the `SwitchInput`, this notably broke the feature to pass down a custom icons. (There might be a more elegant way to fix this)
| ![Screenshot 2024-10-13 at 11 42 39](https://github.com/user-attachments/assets/8d08a84b-871d-48cb-85f3-9f155b69e5c9)  | ![Screenshot 2024-10-13 at 11 44 15](https://github.com/user-attachments/assets/d55d2434-49cd-4f6c-bf58-1acee3e8d8d9) |
| ![Screenshot …
> fix(boilerplate): fix Toggle's Checkbox and Switch custom props

- src/commands/new.ts
- src/tools/react-native.ts
Fixes #2816.
This PR replaces the `rm` and `mv` shell commands in project creation with `gluegun (fs-jetpack)` filesystem calls to ensure compatibility with Windows (Since there's no `mv` and `rm` in Windows CMD).
> refactor: replace shell commands with filesystem API in project creation

- src/commands/new.ts
- Closes #2819
- For some reason, even though we specify `value` in the `choices` array, the value was being set from the `name` property. I wonder if we need to check this upstream in gluegun.
- This fixes the issue where if you chose manual via the prompts, it still wouldn't remove `ios` and `android` dirs from the git ignore file (as it should have)
> fix(cli): fix issue with workflow prompt values

- boilerplate/src/app/_layout.tsx
- boilerplate/src/app/index.tsx
- In [this community slack thread](https://infiniteredcommunity.slack.com/archives/C41PK1LAY/p1729709197546449) it was brought up that the `KeyboardProvider` was omitted from the expo-router template
- This PR fixes that and also aligns the expo-router layout file to be consistent with the app navigator from the main template
- This also restyles the Welcome screen properly so the theming system works out of the box in the expo-router template
> fix(boilerplate): expo-router keyboard provider + theme fix

- boilerplate/.eslintrc.js
- boilerplate/package.json
Disables prop-types rule from eslint-plugin-react recommended config.
I thought this was already disabled since I hadn't seen errors with it, but ran into one today.
| [Insert before screenshot/video] | [Insert after screenshot/video] |
> Disable prop-types in linter

- boilerplate/app/app.tsx
- boilerplate/app/screens/WelcomeScreen.tsx
- Closes #2829
- Closes #2828
- The reasons this occurred is when some different linting rules were applied (due to conditionals getting longer, prettier update, etc) the previous `@mst` mark up to remove / adjust syntax lines no longer worked. These changes fix that.
1. Observe failure via `npx ignite-cli@10.0.3 new PizzaLint --overwrite --packager=npm --yes --debug --install-deps false --state none --remove-demo`
2. Checkout this branch
3. Observe no failure via `ignite/bin/ignite new PizzaLint --overwrite --packager=npm --yes --debug --install-deps false --state none --remove-demo` where the first `ignite` directory is this GitHub project
> fix(boilerplate): reworks some mst removal decorators

- boilerplate/app/components/AutoImage.tsx
- boilerplate/app/components/Card.tsx
- boilerplate/app/components/EmptyState.tsx
- boilerplate/app/components/Header.tsx
- boilerplate/app/components/Icon.tsx
- boilerplate/app/components/ListItem.tsx
- boilerplate/app/components/Text.tsx
- boilerplate/app/components/TextField.tsx
- boilerplate/app/components/Toggle/Checkbox.tsx
- boilerplate/app/components/Toggle/Radio.tsx
- boilerplate/app/components/Toggle/Switch.tsx
- boilerplate/app/components/Toggle/Toggle.tsx
This fixes broken links in the boilerplate components.
> Fix broken component example links

- boilerplate/package.json
- src/commands/new.ts
This would resolve one of the issues in https://github.com/infinitered/ignite/issues/2840, although there are additional problems with the Expo Router template.
This is a little bit of a sledgehammer approach, but I wanted to start with the simple solution and we can enhance it if that seems necessary.
In https://github.com/infinitered/ignite/pull/2823, we added the `--legacy-peer-deps` flag for `npm install` commands. This fixed a problem upstream from https://github.com/standard/eslint-config-standard/issues/412, but I believe it has opened up a new problem for users who choose to use Expo Router and npm. Based on the [issues that Expo Router + ESLint has experienced with how bun resolves peer dependencies](https://github.com/expo/expo/issues/29150), I am guessing the legacy peer …
> fix: include ajv in devDependencies for Expo Router and npm

- boilerplate/react-native.config.js
- Removes the interop fabric definition for FlashList, since the New Architeture is now supported by that library
- I believe this is automatically handled by Expo now anyway
```
warn The "project.ios.unstable_reactLegacyComponentNames" config option is not necessary anymore for React Native 0.74 and does nothing. Please remove it from the "react-native.config.js" file.
warn The "project.android.unstable_reactLegacyComponentNames" config option is not necessary anymore for React Native 0.74 and does nothing. Please remove it from the "react-native.config.js" file
```
> fix(boilerplate): remove interop definition for FlashList

- boilerplate/package.json
- src/commands/new.ts
- Trying to fix the issue where Expo makes a release and `npx expo install --fix`, which is part of the new command, causes tests to fail due to it's console output
> fix(cli): catch expo install --fix tripping test

- boilerplate/ignite/templates/component/NAME.tsx.ejs
- src/tools/react-native.ts
- test/vanilla/ignite-new-expo-router.test.ts
- Closes #2853
- Updates test to make sure this doesn't regress again
> fix: component generator template off in expo-router

- boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
- boilerplate/app/screens/WelcomeScreen.tsx
- boilerplate/app/utils/gestureHandler.ts
- boilerplate/app/utils/useHeader.tsx
- Closes #2807
- Addresses `useEffect` issue highlighted here: https://github.com/react-navigation/react-navigation/issues/11748
- Addresses `setImmediate` issue highlighted here: https://github.com/necolas/react-native-web/issues/1891#issuecomment-887502705
- Fixes `WelcomeScreen` displaying on Web properly
- Keyboard controller does not have issues with these latest deps (I've branched from the SDK 52 feature branch), so the fix is more straightforward than #2809
- Made an adjustment to the `toggleDrawer` being fired in `handleScroll` because it was getting caught in a loop (set state is bad in an effect anyway). So the drawer doesn't close upon clicking a nav item but it's much nicer than it not working (plus we have plans to remove the drawer from the demo application)
| Before …
> fix(boilerplate): web platform fixes

- boilerplate/app/components/AutoImage.tsx
@markrickert recently made a change to this component on our client project to use [`PixelRatio.roundToNearestPixel`](https://reactnative.dev/docs/pixelratio#roundtonearestpixel) for the sizing from `useAutoImage`. No visible changes in the simulator, but it seems like a nice touch to clean up any trailing values in the auto image math.
| <img src="https://github.com/user-attachments/assets/55d2a1ae-b149-4e80-a0e0-caf8e519e421" width="300" /> | <img src="https://github.com/user-attachments/assets/ac216c95-3554-4c04-9fa9-687c4f9f4b9e" width="300" />  |
| …
> fix: use PixelRatio for AutoImage values

- boilerplate/App.tsx
- boilerplate/package.json
- Closes #2875
- We had an old `main` value from the Expo Go days and while it worked in standard repos, it would not work properly in a monorepo out of the box. This fixes that.
- Follow [https://ignitecookbook.com/docs/recipes/SettingUpYarnMonorepo](Setting Up Yarn Monorepo] cookbook recipe
- Note: in doing so I had to make some touch ups to the recipe, which can be found in [this PR](https://github.com/infinitered/ignite-cookbook/pull/184) if not yet published
- Observe the `Before` screenshot below
- Follow [https://docs.expo.dev/guides/monorepos/#create-our-first-app](monorepo guide)
- Upon generating the app template, make sure to generate the app via `npx create-expo-app@latest --template react-navigation/template` to get a proper React Navigation template - otherwise `expo-router` …
> fix(boilerplate): main entry point

- .gitignore
- src/commands/new.ts
- src/tools/react-native.test.ts
- src/tools/react-native.ts
- test/vanilla/ignite-new.test.ts
- Closes #2890 2890
- Looks at the `packagerName` in use for the install and updates the generated README.md with the proper install and run commands
| ![image](https://github.com/user-attachments/assets/ff534ca4-cd9d-4d2f-aaf0-6f5c664d57bb) | ![image](https://github.com/user-attachments/assets/92cb2b39-6474-47ca-9cb3-878058326659) |
> fix(cli): update run commands in boilerplate README depending on packager

- boilerplate/app/components/Text.test.tsx
basic render function uses a new api with `screen.query`
https://callstack.github.io/react-native-testing-library/docs/api/render
> The modern and recommended way of accessing queries is to use the screen object exported by the @testing-library/react-native package. This object will contain methods of all available queries bound to the most recently rendered UI.
> test: migrate RNTL Text to screen api

- boilerplate/app.json
Expo defines `android.allowBackup` as `true` by default. 😱  https://docs.expo.dev/versions/latest/config/app/#allowbackup
This should be opt-in behavior, imho. Setting this value to false will prevent apps from automatically backing up the app’s documents directory to google drive on the user’s behalf. 
Developers should have to opt into this behavior by manually changing this to true or removing the value from the `app.json` file.
> fix: add `android.allowBackup: false` to expo app config

- docs/cli/Ignite-CLI.md
- src/commands/new.ts
- Closes #2916 
- Moves the `Remove demo code` prompt after nav and state mgmt questions which can force it's removal
- Warns the user better about demo code being removed
- Updates docs to mention this as well
> fix(cli): reorder demo app question

- .circleci/config.yml
* Updates the Infinite Red docs CircleCI orb from v0.4.9 to v0.5.0 and adds SSH key fingerprint configuration.
N/A
> update ir-docs orb version and specify SSH key

- boilerplate/app/components/Header.tsx
- boilerplate/app/components/Icon.tsx
- boilerplate/app/screens/LoginScreen.tsx
- docs/boilerplate/app/components/Icon.md
There were two issues at play here:
1. Icon's `style` prop overrides the Wrapped `TouchableOpacity`'s `style` prop with an incompatible `StyleProp<ImageStyle>`
2. Icon changed the wrapper used based on the presence of the `onPress` prop, which made accurate typing and linting difficult.
See
https://github.com/infinitered/ignite/issues/2888#issuecomment-2738096598 for more information.
This commit fixes #2888 by simply separating `Icon` into `PressableIcon` and `Icon` components, with simplified prop types for each, and updates the docs to reflect the change.
- Issues:  #2888
> fix(boilerplate) Fix Icon Type definitions

- docs/README.md
Edited the component library link in `/docs/README.md` to fix an issue where it linked to `/docs/docs`, an invalid URL. This results in `ignite/docs/README.md` needing to differ from `ignite/README.md`, however the link now works as expected. It could be changed to an absolute link to keep the two README files the same if that's needed.
> Fixed Broken Link in Documentation

- boilerplate/app/components/ListItem.tsx
This pull request improves the `ListItem` component, focusing on enhancing flexibility by dynamically choosing between `TouchableOpacity` and `View` based on the presence of touchable props. 
- Issues: fixes #2859
| ![Simulator Screen Recording - iPhone 16 Pro - 2025-04-30 at 18 20 58](https://github.com/user-attachments/assets/f4f84373-2209-4bc5-82b5-7270015a8863) | ![Simulator Screen Recording - iPhone 16 Pro - 2025-04-30 at 18 20 23](https://github.com/user-attachments/assets/2600d297-aaa7-4fa8-813c-afce5c94a428) |
> feat(ListItem): Improve ListItem component to dynamically choose between TouchableOpacity and View based on touchable props

- docs/README.md
CircleCI failed on that last merge to master in #2945. This should fix the remaining broken links so docusauras can deploy the docs without  error.
CI failed with:
https://app.circleci.com/pipelines/github/infinitered/ignite/4013/workflows/ea30949e-b664-4781-8124-c61cfa465ff2/jobs/4837
```
[cause]: Error: Docusaurus found broken links!
Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
Exhaustive list of all broken links found:
- Broken link on source page path = /ignite-cli/:
-> linking to LICENSE/ (resolved as: /ignite-cli/LICENSE/)
```
> chore(docs): followup on #2945: borken docusauras links

- boilerplate/app/i18n/translate.ts
updated the doc for i18n translate to reflect proper usage of the translation keys
- Its a quick small change to rename the example key which is present in the translate.ts file for i18n translations.
- I am starting out the development of my own RN project and came across the ignite project and was exploring the project whenI found this tiny issue.
> fix(boilerplate): updated i18n translate

- boilerplate/test/i18n.test.ts
The tests were failing on #2924 but i thought it was just the CI being flaky… surely changing one word in a comment wouldn’t cause the entire test suite to hang! So i merged it. 
_Boy was I wrong._ Turns out that the i18n tests actually greps the filesystem looking for instances of the `translate()` function, extracts their keys, and then compares those keys to the list inside the translation files.
[This `grep` command](https://github.com/infinitered/ignite/blob/master/boilerplate/test/i18n.test.ts#L49) doesn’t take commented code into consideration so it sees these blocks of code as equally valid instances of the `translate()`function:
```typescript
translate("key1")
// translate("key2")
/**
* translate("key3")
*/
```
So the test will look for `["key1", "key2", "key3"]` and make sure …
> fix(tests): fix i18n tests [skip ci]

- src/commands/new.ts
- Closes #2947
- This actually worked if you use the CLI switches, ie: `--state none` but failed during the prompts
- `useDefault` is only meant to apply the default value if `--yes` is applied, so even though we skipped the prompt for removing the demo application (as intended, because the user wanted to remove MST), we didn't later remove the code, only markup
- Since our tests utilize the CLI, this fell through the cracks, need to better emulate following prompts at some point would be a good follow up to this.
> fix(cli): correct mobx removal when using prompts

- boilerplate/.eslintrc.js
- boilerplate/app/components/Text.tsx
- boilerplate/app/components/TextField.tsx
- boilerplate/app/screens/LoginScreen.tsx
- boilerplate/test/setup.ts
Adds two useful rules to the eslint config for `no-restricted-imports`:
1. We include `react-native-safe-area-view` and should always use the `SafeAreaView` from that library instead of from `react-native`
2. We have our own custom `Text`, `TextField` (TextInput), and `Button` components. Add rules to disallow these from `react-native` to ensure developers are using the components that ship with ignite and not importing from react-native.
> chore(linter): Add some more rules to the no-restricted-import rule

- boilerplate/app/components/Button.tsx
Fixing type for Button's `pressedTextPresets`. Change from ViewStyle to TextStyle. This was a minor change that I caught will review types a project created by Ignite.
> fix(boilerplate): Button text uses TextStyle instead of ViewStyle

- boilerplate/app.config.ts
- test/vanilla/ignite-new.test.ts
I added this default config to the boilerplate in the typescript file instead of the json file so i could put comments on the code.
🌈 🙌 With tests! 🙌 🌈 
- Issues: Closes #2674
> feat(ios): add a default iOS privacyManifest

- boilerplate/app/app.tsx
- boilerplate/app/navigators/AppNavigator.tsx
This PR resolved a bug that was recently reported [here](https://github.com/infinitered/ignite/issues/2923) that describes an error being thrown when the `ErrorBoundary` component is rendered outside of the `ThemeProvider`.
> fix(boilerplate): Move Error Boundary Inside Theme Provider

- boilerplate/app/components/EmptyState.tsx
- boilerplate/app/screens/WelcomeScreen.tsx
- boilerplate/src/app/index.tsx
This PR sets the tint color for the welcome eyes image without a `isDark` check.
- Issues: closes #2841
| ![Simulator Screen Recording - iPhone 16 Pro - 2025-05-21 at 16 08 31](https://github.com/user-attachments/assets/c54194eb-4132-4163-b7c7-aa9a22d351f2) | ![Simulator Screen Recording - iPhone 16 Pro - 2025-05-21 at 16 06 23](https://github.com/user-attachments/assets/d44ff3c8-f7c9-467f-a626-edb418d16d53) |
> fix(boilerplate): fixes the tintColor of the image on the welcome screen

- boilerplate/package.json
- package.json
- Updates `package.json` node engine to be 20+ to be aligned with Expo 53 recommendation
> fix(boilerplate,cli): node engine

- docs/QuickStart.md
A new Quick Start guide that gets to the point a bit more with regards to setup, new app and publishing an app. 
This should address the needs defined in #2663 
|                           |                           |
| ![image](https://github.com/user-attachments/assets/6d360b32-9e8d-49df-8894-0fee8e33c5eb) | ![image](https://github.com/user-attachments/assets/0c083d65-6603-4586-b89c-df81204522f3) |
> docs(quick-start): fixes #2663

- boilerplate/app/navigators/navigationUtilities.ts
This fixes a small warning where the ref was not given an initial value.
> Fix: useRef initial value

- boilerplate/app/navigators/navigationUtilities.ts
I came across this bug while I was updating versions of my app.  I would love another set of eyes on this
The `useBackButtonHandler` function in `navigationUtilities.ts` was using the deprecated `BackHandler.removeEventListener()` method, which causes a runtime error in React Native 0.79.2 with Expo ^53.0.0
`TypeError: _reactNative.BackHandler.removeEventListener is not a function`
This occurs because `BackHandler.removeEventListener()` was removed from the React Native API starting in version 0.71.
Updated the code to use the modern `BackHandler` API where `addEventListener()` returns a `NativeEventSubscription` object with a `remove()` method.
**Before:**
```typescript
BackHandler.addEventListener("hardwareBackPress", onBackPress)
return () => …
```
> Fix BackHandler.removeEventListener Deprecation Error

- boilerplate/package.json
- src/commands/new.ts
- src/tools/packager.ts
- src/tools/react-native.test.ts
There's an issue when providing the version in the `expo.install.excludes` keys, which might be related to the -nightly suffix as it doesn't fall into some of the prerelease tags (not 100% on this).
Looking at [the docs](https://docs.expo.dev/versions/latest/config/package-json/#installexclude), it seems like they may have migrated away from providing the specific version in the key anyway? This doesn't match with Expo's test cases on the matter, but it is what the docs say now.
- Closes #3000 
In addition to this, I updated the `expo-router` version we slide into the template from the new command. This wasn't required, as `expo install --fix` actually would have fixed it anyway, should the worklets install would have actually been excluded.
Note how it says it is skipping them, but it …
> fix: update worklets exclude to drop version
